services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: toro
      POSTGRES_USER: toro
      POSTGRES_PASSWORD: toro_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - toro-net

  redis:
    image: redis:alpine
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - toro-net

  nats-common: &nats-common
    image: nats:2.9-alpine
    networks:
      - toro-net

  nats-1:
    <<: *nats-common
    command: >
      -js  -sd /data  --cluster_name=${NATS_CLUSTER_NAME}  --name=nats-1  --cluster=nats://0.0.0.0:${NATS_CLUSTER_PORT}  --routes=nats://nats-2:${NATS_CLUSTER_PORT},nats://nats-3:${NATS_CLUSTER_PORT}  --http_port=8222
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats_1_data:/data

  nats-2:
    <<: *nats-common
    command: >
      -js  -sd /data  --cluster_name=${NATS_CLUSTER_NAME}  --name=nats-2  --cluster=nats://0.0.0.0:${NATS_CLUSTER_PORT}  --routes=nats://nats-1:${NATS_CLUSTER_PORT},nats://nats-3:${NATS_CLUSTER_PORT} 
    ports:
      - "4223:4222"
    volumes:
      - nats_2_data:/data

  nats-3:
    <<: *nats-common
    command: >
      -js  -sd /data  --cluster_name=${NATS_CLUSTER_NAME}  --name=nats-3  --cluster=nats://0.0.0.0:${NATS_CLUSTER_PORT}  --routes=nats://nats-1:${NATS_CLUSTER_PORT},nats://nats-2:${NATS_CLUSTER_PORT} 
    ports:
      - "4224:4222"
    volumes:
      - nats_3_data:/data

  svix-redis:
    image: redis:alpine
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - svix_redis_data:/data
    networks:
      - toro-net

  svix-server:
    image: svix/svix-server:v1.84.1
    restart: always
    environment:
      SVIX_QUEUE_TYPE: redis
      SVIX_DB_DSN: postgresql://toro:toro_password@db:5432/toro
      SVIX_REDIS_DSN: redis://svix-redis:6379
      SVIX_JWT_SECRET: ${SVIX_JWT_SECRET}
    ports:
      - "8071:8071"
    depends_on:
      - svix-redis
      - db
    networks:
      - toro-net

  app-django:
    build:
      context: ..
      dockerfile: container/django/Dockerfile
    environment:
      POSTGRES_DB: toro
      POSTGRES_USER: toro
      POSTGRES_PASSWORD: toro_password
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379
      NATS_URL: nats://nats-1:4222,nats://nats-2:4222,nats://nats-3:4222
    ports:
      - "8002:8000"
    depends_on:
      - redis
      - db
    volumes:
      - ..:/app
      - django_static:/app/staticfiles
    networks:
      - toro-net

  nginx:
    build:
      context: ../
      dockerfile: container/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app-django
    volumes:
      - django_static:/app/staticfiles
    networks:
      - toro-net

volumes:
  postgres_data:
  redis_data:
  django_static:
  nats_1_data:
  nats_2_data:
  nats_3_data:
  svix_redis_data:


networks:
  toro-net:
    driver: bridge
