"""
LLM Semantic Scoring Engine.

This module is responsible for orchestrating the LLM request. It takes the 
mathematically plausible candidates generated by the heuristics and asks the 
LLM to assign a semantic `utility` score to each one based on textual evidence.
"""
import logging
from typing import List, Optional
from pydantic import BaseModel
from openai import AsyncOpenAI
import os

from reconciliation_prod.domain.bank import BankItem
from reconciliation_prod.domain.book import BookItem
from reconciliation_prod.domain.hypothesis import ReconciliationHypothesis
from reconciliation_prod.reconciliation.candidate_generation import generate_plausible_candidates

logger = logging.getLogger(__name__)

from reconciliation_prod.reconciliation.prompt import SYSTEM_PROMPT

class ScoredHypothesesResponse(BaseModel):
    """
    Structured output schema for the LLM's response.
    """
    hypotheses: List[ReconciliationHypothesis]

async def run_semantic_engine(
    problem_id: str,
    currency: str,
    bank_items: List[BankItem],
    book_items: List[BookItem],
    scenario_evidence: str,
    llm_client: AsyncOpenAI,
    model_name: str = "gpt-5.4-mini"
) -> List[ReconciliationHypothesis]:
    """
    Executes a single-shot LLM reasoning pass to score candidates semantically.
    
    This function:
    1. Generates deterministic candidate strings using Bipartite Graph Partitioning.
    2. Constructs a prompt with the state, evidence, and candidates.
    3. Invokes the OpenAI LLM with a strict Pydantic response format.
    
    Args:
        problem_id (str): A unique identifier for the reconciliation scenario.
        currency (str): The primary currency of the items.
        bank_items (List[BankItem]): The open bank lines.
        book_items (List[BookItem]): The open ledger items.
        scenario_evidence (str): Any textual context (e.g. emails, metadata).
        llm_client (AsyncOpenAI): The instantiated OpenAI client.
        model_name (str): The model to use (default: gpt-5.4-mini).
        
    Returns:
        List[ReconciliationHypothesis]: A list of hypotheses with LLM-assigned 
                                        utility scores (0-1000).
    """
    if not bank_items or not book_items:
        logger.info(f"No bank items or book items provided for {problem_id}. Returning empty hypotheses.")
        return []

    plausible_candidates = generate_plausible_candidates(bank_items, book_items)

    context = (
        f"SCENARIO: {problem_id}\n"
        f"CURRENCY: {currency}\n\n"
        f"BANK ITEMS:\n{[b.model_dump_json() for b in bank_items]}\n\n"
        f"BOOK ITEMS:\n{[j.model_dump_json() for j in book_items]}\n\n"
        f"EVIDENCE:\n{scenario_evidence}\n\n"
        f"--- PRE-CALCULATED PLAUSIBLE CANDIDATES ---\n"
        f"The following mathematically valid combinations were found. "
        f"Use the evidence to SCORE them (assigning utility) and generate hypotheses for them. "
        f"If a bank item appears in multiple overlapping candidates, generate a hypothesis for EACH one.\n"
        f"{plausible_candidates}\n\n"
        f"Please output a JSON object conforming to the schema."
    )

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": context}
    ]

    logger.info(f"Invoking LLM Semantic Engine for {problem_id}")
    
    response = await llm_client.beta.chat.completions.parse(
        model=model_name,
        messages=messages,
        response_format=ScoredHypothesesResponse,
    )

    parsed_response = response.choices[0].message.parsed
    if parsed_response is None:
        logger.error("LLM failed to parse response into expected schema.")
        return []
        
    return parsed_response.hypotheses
