# Generated by Django 5.2.10 on 2026-01-17 19:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_agent', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Curency code')),
                ('analysis_timeframe_hours', models.PositiveIntegerField(default=24, help_text='Number of hours back in time this user considers when performing analysis')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('profile_is_private', models.BooleanField(blank=True, default=False)),
                ('notification_is_on', models.BooleanField(default=True)),
                ('localization_is_on', models.BooleanField(default=True)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=56, null=True)),
                ('user_bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('private_key', models.CharField(blank=True, db_column='PrivateKey', default=uuid.uuid4, help_text='The private key is actually a password salt', max_length=256)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_since', models.DateTimeField(blank=True, null=True)),
                ('handle', models.CharField(blank=True, max_length=50, null=True)),
                ('trading_style', models.CharField(blank=True, max_length=50, null=True)),
                ('alpace_supplementary_info', models.JSONField(blank=True, default=dict, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('like', 'Like'), ('follow', 'Follow'), ('share', 'Share'), ('tag', 'Tag'), ('user_viewed_influencer', 'User_viewed_influencer')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.BigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', 'object_id', 'user'], name='users_activ_activit_c55c2b_idx'), models.Index(fields=['content_type', 'object_id'], name='users_activ_content_b971ef_idx')],
                'unique_together': {('user', 'activity_type', 'content_type', 'object_id')},
            },
        ),
    ]
