# Generated by Django 5.2.10 on 2026-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='users_activ_activit_c55c2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='users_activ_content_b971ef_idx',
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('subscribe', 'Subscribe')], default='subscribe', max_length=32),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'content_type', 'object_id'], name='users_activ_activit_340bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'activity_type'], name='users_activ_user_id_add752_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
