# Generated by Django 6.0.1 on 2026-01-18 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_activity_users_activ_activit_c55c2b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_uuid',
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
