# Generated by Django 5.2.10 on 2026-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_uuid_alter_activity_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alpace_supplementary_info',
            new_name='alpaca_supplementary_info',
        ),
    ]
