# Generated by Django 5.2.10 on 2026-01-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_alpace_supplementary_info_user_alpaca_supplementary_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alpaca_supplementary_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trading_style',
        ),
        migrations.AddField(
            model_name='user',
            name='plan_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_payment_method',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_payment_method_validity_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_payment_method_validity_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_tier',
            field=models.CharField(default='free', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_tier_validity_auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_tier_validity_auto_renew_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_tier_validity_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_tier_validity_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
