# Generated by Django 5.1 on 2025-08-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='currency',
            field=models.CharField(default='USD', max_length=3, verbose_name='Curency code'),
        ),
    ]
