# Generated by Django 5.1 on 2025-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_entitymodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidtransaction',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
