# Generated by Django 5.1 on 2025-10-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_plaidtransaction_is_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulegroup',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='miss_count',
        ),
        migrations.RemoveField(
            model_name='rulegroup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='keywords',
            field=models.TextField(blank=True, help_text='Indexed keywords for fast rule retrieval.'),
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='ledger.rulegroup'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='field',
            field=models.CharField(choices=[('description', 'Description'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('memo', 'Memo'), ('amount', 'Amount'), ('role', 'Account Role'), ('uuid', 'Account UUID'), ('date', 'Transaction Date'), ('time', 'Transaction Time'), ('mcc', 'Merchant Category Code'), ('category', 'Bank Category'), ('invoice_text', 'Invoice/Receipt Text')], max_length=32),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='ledger.rulegroup'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='operator',
            field=models.CharField(choices=[('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('equals', 'Equals'), ('in', 'In List'), ('not_in', 'Not In List'), ('regex', 'Regex'), ('startswith', 'Starts With'), ('endswith', 'Ends With'), ('is_null', 'Is Null / Empty'), ('is_not_null', 'Is Not Null / Empty'), ('gt', 'Greater Than'), ('lt', 'Less Than')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='value',
            field=models.TextField(blank=True, help_text='Condition value. Comma-separated for IN/NOT_IN.'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='logic',
            field=models.CharField(choices=[('AND', 'All (AND)'), ('OR', 'Any (OR)')], default='AND', max_length=3),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='match_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Lower values run first.'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='target_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.accountmodel'),
        ),
    ]
