# Generated by Django 5.1 on 2025-11-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_rulegroup_confidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulegroup',
            options={'ordering': ['priority', 'pk']},
        ),
        migrations.AddField(
            model_name='rulegroup',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='The entity that owns this rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_groups', to='ledger.entitymodel'),
        ),
        migrations.AlterField(
            model_name='ruleauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ruleauditlog',
            name='match_info',
            field=models.JSONField(default=dict, help_text='Verbose match explanation: output of RuleGroup.explain_match()'),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='operator',
            field=models.CharField(choices=[('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('equals', 'Equals'), ('in', 'In List'), ('not_in', 'Not In List'), ('regex', 'Regex'), ('startswith', 'Starts With'), ('endswith', 'Ends With'), ('contains_cs', 'Contains (Case-Sensitive)'), ('equals_cs', 'Equals (Case-Sensitive)'), ('is_null', 'Is Null'), ('is_not_null', 'Is Not Null'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rulecondition',
            name='value',
            field=models.TextField(blank=True, help_text='Condition value. Use JSON array for IN/NOT_IN, e.g., ["val1", "val2"]'),
        ),
        migrations.AlterField(
            model_name='rulegroup',
            name='keywords',
            field=models.TextField(blank=True, help_text='Space-separated keywords for fast rule retrieval. Can be auto-generated.'),
        ),
        migrations.AddConstraint(
            model_name='rulegroup',
            constraint=models.UniqueConstraint(fields=('entity', 'name'), name='unique_rule_name_per_entity'),
        ),
    ]
