# Generated by Django 5.1 on 2025-11-10 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_rulegroup_options_rulegroup_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCountModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(blank=True, max_length=150, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('num_requests', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='ledger_toke_created_bbd1db_idx')],
            },
        ),
    ]
