# Generated by Django 5.1 on 2025-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_tokencountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencountmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
