# Generated by Django 5.1 on 2025-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_tokencountmodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokencountmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='tokencountmodel',
            name='ledger_toke_created_bbd1db_idx',
        ),
        migrations.AddIndex(
            model_name='tokencountmodel',
            index=models.Index(fields=['created_at'], name='ledger_toke_created_50713a_idx'),
        ),
    ]
