# Generated by Django 5.1 on 2025-11-13 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_tokencountmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedJobModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card_statement', 'Credit Card Statement'), ('debit_card_statement', 'Debit Card Statement'), ('quickbooks', 'QuickBooks'), ('sap', 'SAP'), ('xerox', 'Xerox'), ('other', 'Other')], max_length=255)),
                ('s3_signed_url', models.URLField()),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('xls', 'XLS'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('json', 'JSON'), ('xml', 'XML'), ('html', 'HTML')], max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Imported Job',
                'verbose_name_plural': 'Imported Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransactionModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.importedjobmodel')),
            ],
            options={
                'verbose_name': 'Imported Transaction',
                'verbose_name_plural': 'Imported Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importedjobmodel',
            index=models.Index(fields=['entity'], name='ledger_impo_entity__131989_idx'),
        ),
        migrations.AddIndex(
            model_name='importedtransactionmodel',
            index=models.Index(fields=['imported_job'], name='ledger_impo_importe_38c4a6_idx'),
        ),
    ]
