# Generated by Django 5.1 on 2025-11-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_importedjobmodel_importedtransactionmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedjobmodel',
            name='s3_signed_url',
        ),
        migrations.AddField(
            model_name='importedjobmodel',
            name='operation_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('transaction_upload', 'Transaction Upload'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('payment', 'Payment')], default='bank_statement', max_length=255),
            preserve_default=False,
        ),
    ]
