# Generated by Django 5.1 on 2025-11-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_importedjobmodel_s3_signed_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedjobmodel',
            name='file_type',
            field=models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('xls', 'xls'), ('pdf', 'pdf'), ('docx', 'docx'), ('doc', 'doc'), ('txt', 'txt'), ('json', 'json'), ('xml', 'xml'), ('html', 'html')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedjobmodel',
            name='operation_type',
            field=models.CharField(choices=[('bank_statement', 'bank statement'), ('receipt', 'receipt'), ('invoice', 'invoice'), ('transaction_upload', 'transaction upload'), ('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer'), ('payment', 'payment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedjobmodel',
            name='source',
            field=models.CharField(choices=[('bank_statement', 'bank Statement'), ('credit_card_statement', 'credit card statement'), ('debit_card_statement', 'debit card statement'), ('quickbooks', 'quickbooks'), ('sap', 'sap'), ('xerox', 'xerox'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='importedjobmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
    ]
