# Generated by Django 5.1 on 2026-02-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_importedjobmodel_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='is_ephemeral',
            field=models.BooleanField(default=False, verbose_name='Is Ephemeral'),
        ),
    ]
