# Generated by Django 6.0.6 on 2026-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_entitymodel_is_ephemeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmodel',
            name='bill_items',
            field=models.ManyToManyField(through='ledger.ItemTransactionModel', through_fields=('bill_model', 'item_model'), to='ledger.itemmodel', verbose_name='Bill Items'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_items',
            field=models.ManyToManyField(through='ledger.ItemTransactionModel', through_fields=('invoice_model', 'item_model'), to='ledger.itemmodel', verbose_name='Invoice Items'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_items',
            field=models.ManyToManyField(through='ledger.ItemTransactionModel', through_fields=('po_model', 'item_model'), to='ledger.itemmodel', verbose_name='Purchase Order Items'),
        ),
    ]
