# Generated by Django 5.1.15 on 2026-09-09 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_alter_billmodel_bill_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingRevision',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bookkeeping_revision', serialize=False, to='ledger.entitymodel')),
                ('revision', models.BigIntegerField(default=0, help_text='Monotonically increasing durable persistence revision.', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bookkeeping Revision',
                'verbose_name_plural': 'Bookkeeping Revisions',
                'db_table': 'ledger_bookkeeping_revision',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingClassificationDecision',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=1.0)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('evidence_refs', models.JSONField(default=list)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dag_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ase_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_decision', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_classification_decisions', to='ledger.accountmodel')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_classification_decisions', to='ledger.billmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_classification_decisions', to='ledger.entitymodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_classification_decisions', to='ledger.invoicemodel')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='ledger.bookkeepingclassificationdecision')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_classification_decisions', to='ledger.transactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Classification Decision',
                'verbose_name_plural': 'Bookkeeping Classification Decisions',
                'db_table': 'ledger_bookkeeping_classification_decision',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingClassificationInvalidation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_invalidation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidations', to='ledger.bookkeepingclassificationdecision')),
            ],
            options={
                'verbose_name': 'Bookkeeping Classification Invalidation',
                'verbose_name_plural': 'Bookkeeping Classification Invalidations',
                'db_table': 'ledger_bookkeeping_classification_invalidation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingEvidenceAssertion',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('document_ids', models.JSONField(default=list)),
                ('source', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_creation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_evidence_assertions', to='ledger.billmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_evidence_assertions', to='ledger.entitymodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_evidence_assertions', to='ledger.invoicemodel')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='ledger.bookkeepingevidenceassertion')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_evidence_assertions', to='ledger.transactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Evidence Assertion',
                'verbose_name_plural': 'Bookkeeping Evidence Assertions',
                'db_table': 'ledger_bookkeeping_evidence_assertion',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingEvidenceInvalidation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_invalidation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidations', to='ledger.bookkeepingevidenceassertion')),
            ],
            options={
                'verbose_name': 'Bookkeeping Evidence Invalidation',
                'verbose_name_plural': 'Bookkeeping Evidence Invalidations',
                'db_table': 'ledger_bookkeeping_evidence_invalidation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingPaymentApplication',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_amount_units', models.BigIntegerField(help_text='Total payment amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('direction', models.CharField(help_text='Bank movement direction (e.g. BANK_INFLOW, BANK_OUTFLOW).', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision', models.IntegerField(help_text='Local state revision at payment execution.', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_payment_applications', to='ledger.entitymodel')),
                ('plaid_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_payment_applications', to='ledger.plaidtransaction')),
                ('staged_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_payment_applications', to='ledger.stagedtransactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Payment Application',
                'verbose_name_plural': 'Bookkeeping Payment Applications',
                'db_table': 'ledger_bookkeeping_payment_application',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingPaymentApplicationAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_units', models.BigIntegerField(help_text='Allocated amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_application_allocations', to='ledger.billmodel')),
                ('cash_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_application_allocations', to='ledger.transactionmodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_application_allocations', to='ledger.invoicemodel')),
                ('payment_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ledger.bookkeepingpaymentapplication')),
            ],
            options={
                'verbose_name': 'Bookkeeping Payment Application Allocation',
                'verbose_name_plural': 'Bookkeeping Payment Application Allocations',
                'db_table': 'ledger_bookkeeping_payment_application_allocation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingReconciliation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('evidence_refs', models.JSONField(default=list)),
                ('source_hypothesis_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source_hypothesis_state_revision', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_hypothesis_utility', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('source_hypothesis_generated_at', models.DateTimeField(blank=True, null=True)),
                ('source_hypothesis_admissibility', models.CharField(blank=True, max_length=50, null=True)),
                ('source_hypothesis_allocation_support', models.CharField(blank=True, max_length=50, null=True)),
                ('semantic_rationale', models.TextField(blank=True, max_length=4000, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_creation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_reconciliations', to='ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Reconciliation',
                'verbose_name_plural': 'Bookkeeping Reconciliations',
                'db_table': 'ledger_bookkeeping_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingReconciliationBankAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_units', models.BigIntegerField(help_text='Allocated amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('plaid_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_allocations', to='ledger.plaidtransaction')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_allocations', to='ledger.bookkeepingreconciliation')),
                ('staged_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_allocations', to='ledger.stagedtransactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Reconciliation Bank Allocation',
                'verbose_name_plural': 'Bookkeeping Reconciliation Bank Allocations',
                'db_table': 'ledger_bookkeeping_reconciliation_bank_allocation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingReconciliationBookAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_units', models.BigIntegerField(help_text='Allocated amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_allocations', to='ledger.bookkeepingreconciliation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_allocations', to='ledger.transactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Reconciliation Book Allocation',
                'verbose_name_plural': 'Bookkeeping Reconciliation Book Allocations',
                'db_table': 'ledger_bookkeeping_reconciliation_book_allocation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingReconciliationInvalidation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=4000)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_invalidation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidations', to='ledger.bookkeepingreconciliation')),
            ],
            options={
                'verbose_name': 'Bookkeeping Reconciliation Invalidation',
                'verbose_name_plural': 'Bookkeeping Reconciliation Invalidations',
                'db_table': 'ledger_bookkeeping_reconciliation_invalidation',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingRoutingDecision',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('utility', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('solver_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_creation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_routed_decisions', to='ledger.bankaccountmodel')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_routing_decisions', to='ledger.billmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_routing_decisions', to='ledger.entitymodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_routing_decisions', to='ledger.invoicemodel')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='ledger.bookkeepingroutingdecision')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookkeeping_routing_decisions', to='ledger.transactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Routing Decision',
                'verbose_name_plural': 'Bookkeeping Routing Decisions',
                'db_table': 'ledger_bookkeeping_routing_decision',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingRoutingInvalidation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_invalidation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('routing_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidations', to='ledger.bookkeepingroutingdecision')),
            ],
            options={
                'verbose_name': 'Bookkeeping Routing Invalidation',
                'verbose_name_plural': 'Bookkeeping Routing Invalidations',
                'db_table': 'ledger_bookkeeping_routing_invalidation',
            },
        ),
        migrations.AddIndex(
            model_name='bookkeepingclassificationdecision',
            index=models.Index(fields=['entity', 'invoice'], name='ledger_book_entity__6a194c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingclassificationdecision',
            index=models.Index(fields=['entity', 'bill'], name='ledger_book_entity__33a0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingclassificationdecision',
            index=models.Index(fields=['entity', 'transaction'], name='ledger_book_entity__26d500_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingclassificationdecision',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__bf0fb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingclassificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', True), ('invoice__isnull', False), ('transaction__isnull', True)), models.Q(('bill__isnull', False), ('invoice__isnull', True), ('transaction__isnull', True)), models.Q(('bill__isnull', True), ('invoice__isnull', True), ('transaction__isnull', False)), _connector='OR'), name='check_classification_target_xor'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingclassificationinvalidation',
            index=models.Index(fields=['classification'], name='ledger_book_classif_5a4416_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingevidenceassertion',
            index=models.Index(fields=['entity', 'invoice'], name='ledger_book_entity__b395a2_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingevidenceassertion',
            index=models.Index(fields=['entity', 'bill'], name='ledger_book_entity__74e4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingevidenceassertion',
            index=models.Index(fields=['entity', 'transaction'], name='ledger_book_entity__9ee7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingevidenceassertion',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__182740_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingevidenceassertion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', True), ('invoice__isnull', False), ('transaction__isnull', True)), models.Q(('bill__isnull', False), ('invoice__isnull', True), ('transaction__isnull', True)), models.Q(('bill__isnull', True), ('invoice__isnull', True), ('transaction__isnull', False)), _connector='OR'), name='check_evidence_target_xor'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingevidenceinvalidation',
            index=models.Index(fields=['assertion'], name='ledger_book_asserti_2102c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingpaymentapplication',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__160768_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plaid_transaction__isnull', False), ('staged_transaction__isnull', True)), models.Q(('plaid_transaction__isnull', True), ('staged_transaction__isnull', False)), _connector='OR'), name='check_payment_app_bank_source_xor'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplication',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount_units__gt', 0)), name='check_payment_app_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('plaid_transaction__isnull', False)), fields=('plaid_transaction',), name='uniq_payment_app_plaid'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('staged_transaction__isnull', False)), fields=('staged_transaction',), name='uniq_payment_app_staged'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingpaymentapplicationallocation',
            index=models.Index(fields=['payment_application'], name='ledger_book_payment_b4da7c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingpaymentapplicationallocation',
            index=models.Index(fields=['cash_transaction'], name='ledger_book_cash_tr_7f377b_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplicationallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', True), ('invoice__isnull', False)), models.Q(('bill__isnull', False), ('invoice__isnull', True)), _connector='OR'), name='check_payment_app_alloc_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingpaymentapplicationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_units__gt', 0)), name='check_payment_app_alloc_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliation',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__e125b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationbankallocation',
            index=models.Index(fields=['reconciliation'], name='ledger_book_reconci_92daeb_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationbankallocation',
            index=models.Index(fields=['plaid_transaction'], name='ledger_book_plaid_t_993c00_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationbankallocation',
            index=models.Index(fields=['staged_transaction'], name='ledger_book_staged__d46706_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbankallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plaid_transaction__isnull', False), ('staged_transaction__isnull', True)), models.Q(('plaid_transaction__isnull', True), ('staged_transaction__isnull', False)), _connector='OR'), name='check_rec_bank_alloc_target_xor'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbankallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_units__gt', 0)), name='check_rec_bank_alloc_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbankallocation',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'plaid_transaction'), name='uniq_rec_plaid_alloc'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbankallocation',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'staged_transaction'), name='uniq_rec_staged_alloc'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationbookallocation',
            index=models.Index(fields=['reconciliation'], name='ledger_book_reconci_b894c8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationbookallocation',
            index=models.Index(fields=['transaction'], name='ledger_book_transac_56cc34_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbookallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_units__gt', 0)), name='check_rec_book_alloc_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingreconciliationbookallocation',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'transaction'), name='uniq_rec_book_alloc'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingreconciliationinvalidation',
            index=models.Index(fields=['reconciliation'], name='ledger_book_reconci_5ab74b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingroutingdecision',
            index=models.Index(fields=['entity', 'invoice'], name='ledger_book_entity__efdc68_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingroutingdecision',
            index=models.Index(fields=['entity', 'bill'], name='ledger_book_entity__583e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingroutingdecision',
            index=models.Index(fields=['entity', 'transaction'], name='ledger_book_entity__d362c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingroutingdecision',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__629118_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingroutingdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bill__isnull', True), ('invoice__isnull', False), ('transaction__isnull', True)), models.Q(('bill__isnull', False), ('invoice__isnull', True), ('transaction__isnull', True)), models.Q(('bill__isnull', True), ('invoice__isnull', True), ('transaction__isnull', False)), _connector='OR'), name='check_routing_target_xor'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingroutinginvalidation',
            index=models.Index(fields=['routing_decision'], name='ledger_book_routing_5a458a_idx'),
        ),
    ]
