# Generated by Django 5.1.15 on 2026-09-18 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_bookkeepingrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingResidualBankClassificationDecision',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CLASSIFIED', 'Classified'), ('HOLD', 'Hold')], max_length=20)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('original_amount_units', models.BigIntegerField(help_text='Original bank statement movement amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('residual_amount_units', models.BigIntegerField(help_text='Residual unmatched movement amount in integer solver units (scale factor 10,000).', validators=[django.core.validators.MinValueValidator(1)])),
                ('direction', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], help_text='Normalized cash movement direction (INFLOW or OUTFLOW).', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('confidence', models.FloatField(blank=True, help_text='Inference confidence reported by the model/evaluator. Policy threshold (0.98) is enforced by application logic.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rationale', models.TextField(blank=True, null=True)),
                ('evidence_refs', models.JSONField(default=list)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('required_evidence', models.JSONField(default=list)),
                ('schema_version', models.CharField(max_length=100)),
                ('dag_id', models.CharField(max_length=100)),
                ('request_semantic_digest', models.CharField(help_text='SHA-256 digest of canonical semantic bank categorization request payload.', max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_decision', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('persistence_revision_at_decision', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ase_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_property', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_classification_decisions', to='ledger.accountmodel')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_classification_decisions', to='ledger.bankaccountmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_residual_bank_classification_decisions', to='ledger.entitymodel')),
                ('staged_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_classification_decisions', to='ledger.stagedtransactionmodel')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='ledger.bookkeepingresidualbankclassificationdecision')),
            ],
            options={
                'verbose_name': 'Bookkeeping Residual Bank Classification Decision',
                'verbose_name_plural': 'Bookkeeping Residual Bank Classification Decisions',
                'db_table': 'ledger_bookkeeping_residual_bank_classification_decision',
            },
        ),
        migrations.CreateModel(
            name='BookkeepingResidualBankClassificationInvalidation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=4000)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_revision_at_invalidation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('persistence_revision_at_invalidation', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField()),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invalidation', to='ledger.bookkeepingresidualbankclassificationdecision')),
            ],
            options={
                'verbose_name': 'Bookkeeping Residual Bank Classification Invalidation',
                'verbose_name_plural': 'Bookkeeping Residual Bank Classification Invalidations',
                'db_table': 'ledger_bookkeeping_residual_bank_classification_invalidation',
            },
        ),
        migrations.AddIndex(
            model_name='bookkeepingresidualbankclassificationdecision',
            index=models.Index(fields=['entity', 'staged_transaction'], name='ledger_book_entity__aa3ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingresidualbankclassificationdecision',
            index=models.Index(fields=['entity', 'bank_account'], name='ledger_book_entity__a7d0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingresidualbankclassificationdecision',
            index=models.Index(fields=['staged_transaction', 'request_semantic_digest'], name='ledger_book_staged__49704a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingresidualbankclassificationdecision',
            index=models.Index(fields=['entity', 'created_at'], name='ledger_book_entity__148ae8_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankclassificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CLASSIFIED', 'HOLD'])), name='check_res_cls_status'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankclassificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['INFLOW', 'OUTFLOW'])), name='check_res_cls_direction'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankclassificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLASSIFIED'), ('account__isnull', False), ('account_code__isnull', False), ('hold_reason__isnull', True), ('confidence__isnull', False), ('confidence__gte', 0.0), ('confidence__lte', 1.0)), models.Q(('status', 'HOLD'), ('account__isnull', True), ('account_code__isnull', True), ('hold_reason__isnull', False), models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR')), _connector='OR'), name='check_res_cls_status_invariants'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankclassificationdecision',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount_units__gt', 0), ('residual_amount_units__gt', 0), ('residual_amount_units__lte', models.F('original_amount_units'))), name='check_res_cls_amounts'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankclassificationdecision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', True)), fields=('staged_transaction',), name='uniq_res_cls_root'),
        ),
        migrations.AddIndex(
            model_name='bookkeepingresidualbankclassificationinvalidation',
            index=models.Index(fields=['classification'], name='ledger_book_classif_e5ac26_idx'),
        ),
    ]
