# Generated by Django 5.1.15 on 2026-09-18 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_bookkeeping_residual_bank_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingResidualBankPosting',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('persistence_revision', models.BigIntegerField(help_text='Authoritative persistence revision when this posting was committed.', validators=[django.core.validators.MinValueValidator(1)])),
                ('posted_at', models.DateTimeField()),
                ('bank_cash_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='residual_posting_bank_leg', to='ledger.transactionmodel')),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posting', to='ledger.bookkeepingresidualbankclassificationdecision')),
                ('contra_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='residual_posting_contra_leg', to='ledger.transactionmodel')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residual_bank_postings', to='ledger.entitymodel')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_posting', to='ledger.journalentrymodel')),
                ('reconciliation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_posting', to='ledger.bookkeepingreconciliation')),
                ('staged_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residual_bank_postings', to='ledger.stagedtransactionmodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Residual Bank Posting',
                'verbose_name_plural': 'Bookkeeping Residual Bank Postings',
                'db_table': 'ledger_bookkeeping_residual_bank_posting',
                'indexes': [models.Index(fields=['entity', 'posted_at'], name='ledger_book_entity__679cd5_idx'), models.Index(fields=['staged_transaction'], name='ledger_book_staged__5a25c2_idx')],
            },
        ),
    ]
