# Generated by Django 5.1.15 on 2026-09-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_bookkeeping_residual_bank_posting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankposting',
            constraint=models.CheckConstraint(condition=models.Q(('persistence_revision__gt', 0)), name='check_res_bank_posting_persistence_rev_positive'),
        ),
        migrations.AddConstraint(
            model_name='bookkeepingresidualbankposting',
            constraint=models.CheckConstraint(condition=models.Q(('bank_cash_transaction', models.F('contra_transaction')), _negated=True), name='check_res_bank_posting_distinct_tx_legs'),
        ),
    ]
