# Generated by Django 5.1.15 on 2026-09-21 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_bookkeepingresidualbankposting_check_res_bank_posting_persistence_rev_positive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingDocumentIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_document_id', models.UUIDField(db_index=True, help_text='UUID referencing toro_core.documents.id', unique=True)),
                ('source_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('source_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('doc_type', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('NEEDS_REVIEW', 'Needs Review'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('accounting_artifact_type', models.CharField(blank=True, default='', help_text='e.g. IMPORT_JOB, BILL, SUPPORTING_DOCUMENT, NONE', max_length=50)),
                ('accounting_artifact_id', models.CharField(blank=True, default='', help_text='Primary key of created accounting record', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_intakes', to='ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Document Intake',
                'verbose_name_plural': 'Bookkeeping Document Intakes',
                'db_table': 'ledger_bookkeeping_document_intake',
                'indexes': [models.Index(fields=['entity', 'status'], name='ledger_book_entity__85d26d_idx'), models.Index(fields=['source_document_id'], name='ledger_book_source__9fdae9_idx')],
            },
        ),
    ]
