# Generated by Django 5.1.15 on 2026-09-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_bookkeepingdocumentintake'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingEntityTrigger',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bookkeeping_trigger_state', serialize=False, to='ledger.entitymodel')),
                ('pending', models.BooleanField(db_index=True, default=False)),
                ('running', models.BooleanField(db_index=True, default=False)),
                ('last_trigger_id', models.CharField(blank=True, default='', max_length=255)),
                ('last_trigger_source', models.CharField(blank=True, default='', max_length=100)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bookkeeping Entity Trigger',
                'verbose_name_plural': 'Bookkeeping Entity Triggers',
                'db_table': 'ledger_bookkeeping_entity_trigger',
            },
        ),
    ]
