# Generated by Django 5.1.15 on 2026-09-22 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_bookkeepingentitytrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookkeepingNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('residual_hold', 'Residual Hold'), ('document_needs_review', 'Document Needs Review')], max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('postmark_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SENT', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookkeeping_notifications', to='ledger.entitymodel')),
            ],
            options={
                'verbose_name': 'Bookkeeping Notification Delivery',
                'verbose_name_plural': 'Bookkeeping Notification Deliveries',
                'db_table': 'ledger_bookkeeping_notification_delivery',
                'indexes': [models.Index(fields=['entity', 'event_type'], name='ledger_book_entity__b760a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'event_id'), name='unique_bookkeeping_notification_event')],
            },
        ),
    ]
