root = "/workspace"
tmp_dir = "/tmp/air"

[build]
  cmd = "go -C go build -mod=mod -o /tmp/air/protocol ./cmd/protocol"
  bin = "/tmp/air/protocol"
  include_dir = ["go", "tap"]
  include_ext = ["go", "yml", "yaml"]
  exclude_dir = ["go/vendor", "tap/vendor"]
  exclude_regex = ["_test.go"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"
