package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nats-io/nats.go"

	"github.com/Yankzy/usetoro/internal/database"
	"github.com/Yankzy/usetoro/tap/pkg/core"
	"github.com/Yankzy/usetoro/tap/pkg/identity"
	"github.com/Yankzy/usetoro/tap/pkg/redux"
)

type BaseAgent struct {
	Logger      *slog.Logger
	Bus         EventBus
	Cfg         AgentConfig
	Mem         MemoryStore
	KP          *identity.KeyPair
	Sub         *nats.Subscription
	AgentType   string
	Topic       string
	QueueGroup  string
	DurableName string
	Handler     nats.MsgHandler
}

type LLMCallback func(currentSeq uint64) ([]json.RawMessage, error)

func (b *BaseAgent) ExecuteGlobalWorkflow(
	ctx context.Context,
	db *database.Queries,
	workflowID pgtype.UUID,
	llmCallback LLMCallback,
) error {
	b.Logger.Info("Step 2: Hydrating initial DB snapshot constraints intrinsically")
	wf, err := db.GetWorkflow(ctx, workflowID)
	
	var currentSeq uint64
	if err != nil {
		currentSeq = 0
	} else {
		currentSeq = uint64(wf.SequenceID)
	}

	b.Logger.Info("Step 3: Toll Booth Micrion checks mapped synchronously via EventBus integrations")

	b.Logger.Info("Step 4: Booting Reasoning Loop")
	patchArray, llmErr := llmCallback(currentSeq)
	if llmErr != nil {
		return fmt.Errorf("llm payload sequence generation failed natively: %w", llmErr)
	}

	b.Logger.Info("Step 5: Executing Entropy checks avoiding system prefix overflows")
	for _, raw := range patchArray {
		var patch map[string]interface{}
		if err := json.Unmarshal(raw, &patch); err != nil {
			return fmt.Errorf("invalid json generated by AI: %v", err)
		}
		path, ok := patch["path"].(string)
		if ok && strings.HasPrefix(path, "/_sys") {
			return fmt.Errorf("system execution error: AI attempted to override /_sys structural boundaries")
		}
	}

	b.Logger.Info("Step 6: Committing verified structural arrays securely onto JetStream targets")
	event := redux.RFC6902Event{
		EventID:    fmt.Sprintf("evt_%d", time.Now().UnixNano()),
		SequenceID: currentSeq,
		Timestamp:  time.Now(),
		Type:       b.AgentType,
		Actor:      b.Cfg.DID,
		PatchArray: patchArray,
	}

	eventBytes, _ := json.Marshal(event)

	var uuidStr string
	if workflowID.Valid {
		uuidBytes, _ := workflowID.Value()
		uuidStr = uuidBytes.(string)
	}
	traceTopic := fmt.Sprintf("workflow.trace.%s", uuidStr)

	if pubErr := b.Bus.Publish(traceTopic, eventBytes); pubErr != nil {
		return fmt.Errorf("failed to publish redux trace to JetStream target: %w", pubErr)
	}

	return nil
}

// NewBaseAgent centralizes the boilerplate for DID generation and registration fields
func NewBaseAgent(logger *slog.Logger, bus EventBus, cfg AgentConfig, mem MemoryStore, agentType, topic, queueGroup, durableName string, handler nats.MsgHandler) *BaseAgent {
	kp, _ := identity.GenerateKeyPair()
	cfg.DID = identity.CreateDID(kp.Public)
	return &BaseAgent{
		Logger:      logger,
		Bus:         bus,
		Cfg:         cfg,
		Mem:         mem,
		KP:          kp,
		AgentType:   agentType,
		Topic:       topic,
		QueueGroup:  queueGroup,
		DurableName: durableName,
		Handler:     handler,
	}
}

func (b *BaseAgent) Start() error {
	b.Logger.Info("🤖 TAP AI Agent Initializing...", "did", b.Cfg.DID, "type", b.AgentType)

	// Register with Almanac
	inbox := core.BuildAgentInbox(b.Cfg.DID)
	regPayload := map[string]interface{}{
		"did":       b.Cfg.DID,
		"endpoints": []string{inbox},
		"capabilities": []map[string]interface{}{
			{"type": b.AgentType},
		},
		"expiry": time.Now().Add(24 * time.Hour).Unix(),
	}
	regBytes, _ := json.Marshal(regPayload)
	_ = b.Bus.Publish("almanac.register", regBytes)

	// Subscribe to the Agent's specific Topic
	sub, err := b.Bus.QueueSubscribe(
		b.Topic,
		b.QueueGroup,
		b.Handler,
		nats.Durable(b.DurableName),
		nats.DeliverAll(),
		nats.AckExplicit(),
	)
	if err != nil {
		return err
	}
	b.Sub = sub

	b.Logger.Info("👂 Listening for messages", "topic", b.Topic, "queue", b.QueueGroup)
	return nil
}

func (b *BaseAgent) Stop() error {
	if b.Sub != nil {
		return nil
	}
	return nil
}
