[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor/

[program:gunicorn]
# Using gunicorn for now, switch to daphne if WS needed in Django
# command=daphne -u /run/daphne/daphne.sock --access-log - --proxy-headers config.asgi:application
command=gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/.logs/gunicorn.log
redirect_stderr=true
stopwaitsecs=60
user=root

[program:celery]
command=celery -A config worker -l info --loglevel=INFO
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/.logs/celery.log
redirect_stderr=true
stopwaitsecs=60
priority=998
user=root

[program:celery-beat]
command=celery -A config beat -l info --pidfile=/tmp/beat.pid --schedule=/tmp/beat-schedule.db
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/.logs/celery-beat.log
redirect_stderr=true
stopwaitsecs=60
priority=997
user=root
[program:webhook-consumer]
command=python manage.py run_consumer
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
stopwaitsecs=60
user=root
