"""
Domain definitions for Reconciliation Hypotheses.

This module defines the structures that represent proposed relationships 
between Bank items and Book items. Hypotheses are generated by candidate heuristics,
scored by the LLM Semantic Engine, and finalized by the CP-SAT Optimizer.
"""
from typing import List, Optional
from pydantic import BaseModel, Field
from .base import Eligibility, AmountUnits

class BankAllocation(BaseModel):
    """
    Represents a specific amount of money allocated from a BankItem.
    """
    bank_item_id: str
    amount_units: AmountUnits

    @property
    def amount_int(self) -> int:
        """Integer representation of the allocated amount."""
        return int(self.amount_units)

class BookAllocation(BaseModel):
    """
    Represents a specific amount of money allocated to a BookItem.
    """
    book_item_id: str
    amount_units: AmountUnits

    @property
    def amount_int(self) -> int:
        """Integer representation of the allocated amount."""
        return int(self.amount_units)

class ReconciliationHypothesis(BaseModel):
    """
    A proposed match grouping one or more BankItems with one or more BookItems.
    
    The optimizer selects a mutually exclusive set of these hypotheses to form 
    the final global state. Overlapping hypotheses compete based on their `utility`.
    """
    id: str
    eligibility: Eligibility = Field(default=Eligibility.SELECTABLE)
    utility: int = Field(
        ..., 
        ge=0, le=1000, 
        description="Relative preference score (0-1000) assigned by the Semantic Engine."
    )
    bank_allocations: List[BankAllocation] = Field(..., min_length=1)
    book_allocations: List[BookAllocation] = Field(..., min_length=1)
    evidence_refs: Optional[List[str]] = Field(default_factory=list)
    semantic_rationale: Optional[str] = Field(
        default=None, 
        description="LLM's textual reasoning for proposing or scoring this match."
    )

    @property
    def total_bank_allocation_int(self) -> int:
        """Sum of all bank allocations in integer solver units."""
        return sum(alloc.amount_int for alloc in self.bank_allocations)
        
    @property
    def total_book_allocation_int(self) -> int:
        """Sum of all book allocations in integer solver units."""
        return sum(alloc.amount_int for alloc in self.book_allocations)