// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: agent_memory.sql

package database

import (
	"context"
)

const createMemoryRule = `-- name: CreateMemoryRule :exec
INSERT INTO toro_core.agent_memory_rules (realm_id, entity_type, entity_value, instruction)
VALUES ($1, 'keyword', $2, $3)
ON CONFLICT (realm_id, entity_type, entity_value)
DO UPDATE SET instruction = EXCLUDED.instruction, created_at = NOW()
`

type CreateMemoryRuleParams struct {
	RealmID     string
	EntityValue string
	Instruction string
}

func (q *Queries) CreateMemoryRule(ctx context.Context, arg CreateMemoryRuleParams) error {
	_, err := q.db.Exec(ctx, createMemoryRule, arg.RealmID, arg.EntityValue, arg.Instruction)
	return err
}

const getMemoryRules = `-- name: GetMemoryRules :many
SELECT entity_value, instruction
FROM toro_core.agent_memory_rules
WHERE realm_id = $1
`

type GetMemoryRulesRow struct {
	EntityValue string
	Instruction string
}

func (q *Queries) GetMemoryRules(ctx context.Context, realmID string) ([]GetMemoryRulesRow, error) {
	rows, err := q.db.Query(ctx, getMemoryRules, realmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemoryRulesRow
	for rows.Next() {
		var i GetMemoryRulesRow
		if err := rows.Scan(&i.EntityValue, &i.Instruction); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
