// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FignodeAseSessionEmailHold struct {
	SessionID     pgtype.UUID
	TransactionID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type FignodeCanonicalVendor struct {
	ID                        pgtype.UUID
	EntityID                  pgtype.UUID
	RealmID                   pgtype.Text
	DisplayName               string
	IceNumber                 pgtype.Text
	DefaultAccount            string
	CreatedAt                 pgtype.Timestamptz
	VendorCode                pgtype.Text
	PayableAccountCode        pgtype.Text
	DefaultExpenseAccountCode pgtype.Text
	DefaultVatRuleCode        pgtype.Text
}

type FignodeClientRequestOutbox struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	SessionID     pgtype.UUID
	ClientID      pgtype.UUID
	RequestType   string
	Context       pgtype.Text
	DagNodeID     string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type FignodeEmployeeProfile struct {
	UserID           pgtype.UUID
	FirstName        pgtype.Text
	LastName         pgtype.Text
	IsManager        bool
	AiAccuracyScore  pgtype.Numeric
	Streak           int32
	StreakLastDate   pgtype.Date
	TotalCleared     int32
	TodayCleared     int32
	TodayClearedDate pgtype.Date
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FignodeFignodeIndustry struct {
	Name      string
	IconEmoji string
	UpdatedAt pgtype.Timestamptz
}

type FignodeLeaderboardSnapshot struct {
	ID         pgtype.UUID
	Period     string
	ComputedAt pgtype.Timestamptz
	Entries    []byte
}

type FignodeMasterMerchant struct {
	ID                  int64
	NormalizedName      string
	PrimaryDomain       string
	LogoUrl             string
	Mcc                 int32
	Naics               string
	DefaultMacroClass   string
	DefaultQboCategory  string
	IrsReceiptThreshold pgtype.Numeric
}

type FignodeMasterPattern struct {
	ID               int64
	CleanedStem      string
	MasterMerchantID int64
	IsIntermediary   bool
}

type FignodeOrderReconciliation struct {
	ID                pgtype.UUID
	EntityID          pgtype.UUID
	RealmID           pgtype.Text
	BankTransactionID pgtype.UUID
	FactureID         pgtype.UUID
	BlID              pgtype.UUID
	BcID              pgtype.UUID
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type FignodeStagingSession struct {
	ID                    pgtype.UUID
	RealmID               pgtype.Text
	Kind                  string
	CreatedBy             pgtype.UUID
	FileName              pgtype.Text
	RowCount              int32
	Status                string
	BankAccountID         pgtype.UUID
	IsAmbiguous           bool
	AmbiguityReason       pgtype.Text
	OutflowIs             string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	SourceDocumentSetHash pgtype.Text
}

type FignodeStagingTransaction struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RowIndex              pgtype.Int4
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	ParsedDate            pgtype.Date
	CashDirection         pgtype.Text
	IsoCurrencyCode       pgtype.Text
	TransactionHash       pgtype.Text
	ErpTransactionID      pgtype.Text
	TransactionID         pgtype.Text
	PendingTransactionID  pgtype.Text
	MerchantName          pgtype.Text
	LogoUrl               pgtype.Text
	Category              pgtype.Text
	IsPending             pgtype.Bool
	PredictedVendorID     pgtype.UUID
	PredictedVendorName   pgtype.Text
	PredictedCustomerID   pgtype.UUID
	PredictedCustomerName pgtype.Text
	PredictedAccountID    pgtype.UUID
	PredictedAccountName  pgtype.Text
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	HumanAction           pgtype.Text
	SwipedBy              pgtype.UUID
	SwipedAt              pgtype.Timestamptz
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	Status                string
	ErrorMessage          pgtype.Text
	ReconciledAt          pgtype.Timestamptz
	ReconciledBy          pgtype.UUID
	RuleGroupID           pgtype.Int4
	MacroClass            pgtype.Text
	AccountType           pgtype.Text
	SyncedAt              pgtype.Timestamptz
	AseExecutionTrace     []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	MoroccanEnrichment    []byte
	Stage2Proposals       []byte
	Stage2CurrentHash     pgtype.Text
	Stage2Outcome         pgtype.Text
	Stage2ReviewStatus    string
	Stage2ApprovedPayload []byte
	Stage2ApprovedHash    pgtype.Text
	Stage2ReviewedBy      pgtype.UUID
	Stage2ReviewedAt      pgtype.Timestamptz
}

type FignodeVendorAlias struct {
	ID                pgtype.UUID
	EntityID          pgtype.UUID
	RealmID           pgtype.Text
	RawVariant        string
	CanonicalVendorID pgtype.UUID
	Source            string
	ConfidenceScore   pgtype.Numeric
}

type MarketingAttribution struct {
	ID              pgtype.UUID
	ConversionID    pgtype.UUID
	EmailLogID      pgtype.UUID
	CampaignID      pgtype.UUID
	ListID          pgtype.UUID
	AttributedValue int32
	CreatedAt       pgtype.Timestamptz
}

type MarketingCampaign struct {
	ID        pgtype.UUID
	Name      string
	TenantID  pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MarketingCampaignStep struct {
	ID              pgtype.UUID
	CampaignID      pgtype.UUID
	StepNumber      int32
	SubjectTemplate string
	BodyTemplate    string
	DelayDuration   pgtype.Interval
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	LandingPageID   pgtype.UUID
	EmailFormID     pgtype.UUID
}

type MarketingConversion struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ProspectID      pgtype.UUID
	CustomerEmail   string
	ConversionValue int32
	Source          pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type MarketingEmailAccount struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
	WarmupPhase       int32
	DomainCreatedAt   pgtype.Timestamptz
	BounceCount       int32
	SpamComplaints    int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type MarketingEmailLog struct {
	ID            pgtype.UUID
	ProspectID    pgtype.UUID
	CampaignID    pgtype.UUID
	NatsMsgID     pgtype.Text
	EventType     string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	ListID        pgtype.UUID
	UserAgent     pgtype.Text
	IpAddress     pgtype.Text
	IsHuman       pgtype.Bool
	LandingPageID pgtype.UUID
	EmailFormID   pgtype.UUID
}

type MarketingLeadForm struct {
	ID        pgtype.UUID
	Website   string
	FormData  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type MarketingList struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type MarketingListSubscriber struct {
	ListID     pgtype.UUID
	ProspectID pgtype.UUID
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type MarketingProspect struct {
	ID            pgtype.UUID
	Email         string
	FirstName     pgtype.Text
	LastName      pgtype.Text
	Metadata      []byte
	CampaignID    pgtype.UUID
	CurrentStepID pgtype.UUID
	Status        string
	TenantID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type MarketingTenantSetting struct {
	TenantID              pgtype.UUID
	AttributionWindowDays int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ShadowErpAccount struct {
	ID                            pgtype.UUID
	ErpID                         string
	RealmID                       string
	Name                          string
	AccountType                   string
	AccountSubType                pgtype.Text
	Classification                pgtype.Text
	FullyQualifiedName            pgtype.Text
	Active                        pgtype.Bool
	SyncToken                     string
	Domain                        pgtype.Text
	CurrencyRefName               pgtype.Text
	CurrencyRefValue              pgtype.Text
	CurrentBalanceWithSubAccounts pgtype.Numeric
	Sparse                        pgtype.Bool
	ErpCreatedTime                pgtype.Timestamptz
	ErpUpdatedTime                pgtype.Timestamptz
	CurrentBalance                pgtype.Numeric
	SubAccount                    pgtype.Bool
	EventSource                   string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	DeletedAt                     pgtype.Timestamptz
	AccountCode                   pgtype.Text
	ParentCode                    pgtype.Text
	IsPosting                     pgtype.Bool
}

// Records when users correct AI predictions for learning and synonym updates
type ShadowErpAiCorrection struct {
	ID      pgtype.UUID
	RealmID string
	UserID  pgtype.UUID
	// The original text that AI tried to match
	RawInput     string
	AiPrediction pgtype.Text
	// The correct entity ID provided by user
	UserCorrection  string
	CorrectionType  string
	ConfidenceScore pgtype.Numeric
	EventSource     string
	CreatedAt       pgtype.Timestamptz
}

type ShadowErpAttachable struct {
	ID             pgtype.UUID
	RealmID        string
	ErpID          string
	FileName       pgtype.Text
	ContentType    pgtype.Text
	Size           pgtype.Numeric
	Note           pgtype.Text
	AttachableRefs []byte
	SyncToken      pgtype.Text
	ErpCreatedTime pgtype.Timestamptz
	ErpUpdatedTime pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ShadowErpBankAccount struct {
	ID                pgtype.UUID
	RealmID           string
	BankName          string
	AccountNumber     string
	Rib               pgtype.Text
	Iban              pgtype.Text
	LedgerAccountCode string
	Currency          pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ShadowErpBankReconciliationState struct {
	ID                      pgtype.UUID
	RealmID                 string
	BankAccountID           pgtype.UUID
	PeriodKey               string
	Revision                int32
	PreviousStateID         pgtype.UUID
	SupersedesStateID       pgtype.UUID
	StateKind               string
	IdempotencyKey          string
	RequestHash             string
	Status                  string
	Currency                string
	StatementOpeningBalance pgtype.Numeric
	BookOpeningBalance      pgtype.Numeric
	BankStatementBalance    pgtype.Numeric
	BookBankBalance         pgtype.Numeric
	OutstandingBookInflows  pgtype.Numeric
	OutstandingBookOutflows pgtype.Numeric
	OutstandingBankNet      pgtype.Numeric
	ExpectedBankBalance     pgtype.Numeric
	Difference              pgtype.Numeric
	StateHash               string
	CreatedBy               pgtype.UUID
	CreatedAt               pgtype.Timestamptz
}

type ShadowErpBankReconciliationStateInvalidation struct {
	ID        pgtype.UUID
	StateID   pgtype.UUID
	Reason    string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ShadowErpBankReconciliationStateMembership struct {
	ID                         pgtype.UUID
	StateID                    pgtype.UUID
	BankStatementLineID        pgtype.UUID
	JournalLineID              pgtype.UUID
	Disposition                string
	ReconciliationMatchGroupID pgtype.UUID
	CarryForward               bool
	ReviewReason               pgtype.Text
	CreatedAt                  pgtype.Timestamptz
}

type ShadowErpBankStatementLine struct {
	ID                         pgtype.UUID
	RealmID                    string
	BankAccountID              pgtype.UUID
	SourceDocumentID           pgtype.UUID
	LineIndex                  int32
	ExternalReference          pgtype.Text
	OperationDate              pgtype.Date
	ValueDate                  pgtype.Date
	Direction                  string
	Amount                     pgtype.Numeric
	Currency                   string
	Description                string
	CounterpartyName           pgtype.Text
	SourceStagingTransactionID pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
}

type ShadowErpBill struct {
	ID          pgtype.UUID
	ErpID       string
	RealmID     string
	VendorID    pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	EventSource string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpClientDossier struct {
	ID                    pgtype.UUID
	RealmID               string
	FiduciaireID          pgtype.UUID
	DossierCode           string
	CompanyName           string
	IceNumber             pgtype.Text
	SageTemplateProfileID pgtype.UUID
	EventSource           string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// Mirror of QBO CompanyInfo; keyed by realm_id. One row per connected QBO company.
type ShadowErpCompanyInfo struct {
	ID                   pgtype.UUID
	RealmID              string
	ErpID                string
	SyncToken            string
	CompanyName          string
	LegalName            pgtype.Text
	Domain               pgtype.Text
	Country              pgtype.Text
	FiscalYearStartMonth pgtype.Text
	CompanyStartDate     pgtype.Date
	SupportedLanguages   pgtype.Text
	CompanyAddr          []byte
	LegalAddr            []byte
	PrimaryPhone         pgtype.Text
	Email                pgtype.Text
	WebAddr              pgtype.Text
	NameValues           []byte
	Industry             pgtype.Text
	IndustryIcon         pgtype.Text
	BusinessModel        pgtype.Text
	MindsetHint          pgtype.Text
	EventSource          string
	ErpCreatedTime       pgtype.Timestamptz
	ErpUpdatedTime       pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ShadowErpCustomer struct {
	ID                    pgtype.UUID
	ErpID                 string
	RealmID               string
	DisplayName           string
	SyncToken             string
	Industry              pgtype.Text
	IndustryIcon          pgtype.Text
	CustomerDescription   pgtype.Text
	CustomerUrl           pgtype.Text
	EventSource           string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CustomerCode          pgtype.Text
	IceNumber             pgtype.Text
	ReceivableAccountCode pgtype.Text
	RevenueAccountCode    pgtype.Text
	DefaultVatRuleCode    pgtype.Text
}

type ShadowErpDeposit struct {
	ID              pgtype.UUID
	ErpID           string
	RealmID         string
	SyncToken       string
	TxnDate         pgtype.Date
	TotalAmount     pgtype.Numeric
	TargetAccountID string
	Lines           []byte
	Domain          pgtype.Text
	Sparse          pgtype.Bool
	ErpCreatedTime  pgtype.Timestamptz
	ErpUpdatedTime  pgtype.Timestamptz
	RuleID          pgtype.Int4
	EventSource     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ShadowErpInvoice struct {
	ID          pgtype.UUID
	ErpID       string
	RealmID     string
	CustomerID  pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	EventSource string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpJournal struct {
	ID                 pgtype.UUID
	RealmID            string
	JournalCode        string
	JournalName        string
	JournalType        string
	DefaultAccountCode pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ShadowErpJournalEntry struct {
	ID                         pgtype.UUID
	RealmID                    string
	JournalID                  pgtype.UUID
	EntryDate                  pgtype.Date
	Currency                   string
	PieceReference             string
	Label                      string
	SourceBankStatementLineID  pgtype.UUID
	SourceStagingTransactionID pgtype.UUID
	SourceTreatmentPayload     []byte
	SourceTreatmentHash        pgtype.Text
	SourceWorkflowTraceID      pgtype.Text
	ApprovedBy                 pgtype.UUID
	ApprovedAt                 pgtype.Timestamptz
	Status                     string
	CreatedAt                  pgtype.Timestamptz
}

type ShadowErpJournalLine struct {
	ID                   pgtype.UUID
	JournalEntryID       pgtype.UUID
	LineIndex            int32
	AccountID            pgtype.UUID
	AuxiliaryAccountCode pgtype.Text
	Label                string
	Debit                pgtype.Numeric
	Credit               pgtype.Numeric
	CreatedAt            pgtype.Timestamptz
}

type ShadowErpPayment struct {
	ID                 pgtype.UUID
	ErpID              string
	RealmID            string
	SyncToken          string
	TxnDate            pgtype.Date
	TotalAmount        pgtype.Numeric
	UnappliedAmount    pgtype.Numeric
	CustomerID         pgtype.Text
	DepositToAccountID pgtype.Text
	Lines              []byte
	RuleID             pgtype.Int4
	EventSource        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type ShadowErpPurchase struct {
	ID              pgtype.UUID
	ErpID           string
	RealmID         string
	SyncToken       string
	TxnDate         pgtype.Date
	TotalAmount     pgtype.Numeric
	PaymentType     pgtype.Text
	SourceAccountID string
	EntityID        pgtype.Text
	Lines           []byte
	RuleID          pgtype.Int4
	EventSource     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ShadowErpReconciliationMatchGroup struct {
	ID                pgtype.UUID
	IdempotencyKey    string
	RequestHash       string
	RealmID           string
	BankAccountID     pgtype.UUID
	Currency          string
	ItemType          string
	Direction         string
	Amount            pgtype.Numeric
	BankReferenceDate pgtype.Date
	BookReferenceDate pgtype.Date
	PolicyMaxDays     int32
	PolicySnapshot    []byte
	EvidenceRanking   []byte
	Status            string
	CreatedBy         pgtype.UUID
	CreatedByKind     string
	CreatedAt         pgtype.Timestamptz
	ConfirmedBy       pgtype.UUID
	ConfirmedAt       pgtype.Timestamptz
}

type ShadowErpReconciliationMatchMember struct {
	ID                  pgtype.UUID
	MatchGroupID        pgtype.UUID
	BankStatementLineID pgtype.UUID
	JournalLineID       pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

type ShadowErpReconciliationMatchWindow struct {
	ID         pgtype.UUID
	RealmID    string
	ItemType   string
	MaxDays    int32
	AgeingDays int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ShadowErpReconciliationReviewQueue struct {
	ID                  pgtype.UUID
	DedupeKey           string
	RealmID             string
	BankAccountID       pgtype.UUID
	BankStatementLineID pgtype.UUID
	JournalLineID       pgtype.UUID
	MatchGroupID        pgtype.UUID
	Reason              string
	PolicySnapshot      []byte
	Status              string
	ResolvedBy          pgtype.UUID
	ResolvedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type ShadowErpReconciliationTask struct {
	ID                 pgtype.UUID
	RealmID            string
	PeriodLabel        string
	Status             string
	EmailThreadID      pgtype.Text
	MissingDocsSummary []byte
	Discrepancies      []byte
	EventSource        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type ShadowErpRuleAuditLog struct {
	ID            int32
	RealmID       string
	TransactionID pgtype.UUID
	RuleGroupID   pgtype.Int4
	Matched       bool
	// Verbose match explanation: JSON containing condition-level results (maps to MatchExplanation struct)
	MatchInfo           []byte
	HumanReadableReason string
	CreatedAt           pgtype.Timestamptz
}

type ShadowErpRuleCondition struct {
	ID          int32
	RuleGroupID int32
	Field       string
	Operator    string
	Value       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShadowErpRuleGroup struct {
	ID             int32
	RealmID        string
	Name           string
	Logic          string
	Priority       int32
	Keywords       pgtype.Text
	Active         bool
	TargetEntityID pgtype.UUID
	Allocations    []byte
	Direction      string
	RequiresReview bool
	ParentID       pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ShadowErpSageImportTemplate struct {
	ID            pgtype.UUID
	RealmID       string
	TemplateName  string
	Delimiter     string
	DateFormat    string
	ColumnMapping []byte
	EventSource   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ShadowErpSalesReceipt struct {
	ID                 pgtype.UUID
	ErpID              string
	RealmID            string
	SyncToken          string
	TxnDate            pgtype.Date
	TotalAmount        pgtype.Numeric
	CustomerID         pgtype.Text
	DepositToAccountID pgtype.Text
	DocNumber          pgtype.Text
	Lines              []byte
	RuleID             pgtype.Int4
	EventSource        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type ShadowErpStage2TreatmentAccountMapping struct {
	ID        pgtype.UUID
	RealmID   string
	Intent    string
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ShadowErpTreasuryAccountMapping struct {
	ID           pgtype.UUID
	RealmID      string
	TreasuryRole string
	AccountID    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type ShadowErpVatRule struct {
	ID                pgtype.UUID
	RealmID           string
	VatCode           string
	Description       string
	Rate              pgtype.Numeric
	InputAccountCode  string
	OutputAccountCode string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// Tracks Pinecone vector database sync state per ERP realm
type ShadowErpVectorSyncState struct {
	RealmID string
	// Last Chart of Accounts sync to Pinecone
	LastCoaSync      pgtype.Timestamptz
	LastVendorSync   pgtype.Timestamptz
	LastCustomerSync pgtype.Timestamptz
	// Number of account vectors in Pinecone
	CoaVectorCount      pgtype.Int4
	VendorVectorCount   pgtype.Int4
	CustomerVectorCount pgtype.Int4
	EventSource         string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ShadowErpVendor struct {
	ID                        pgtype.UUID
	ErpID                     string
	RealmID                   string
	DisplayName               string
	SyncToken                 string
	LastKnownAccountID        pgtype.UUID
	AiSynonyms                []byte
	Industry                  pgtype.Text
	IndustryIcon              pgtype.Text
	VendorDescription         pgtype.Text
	VendorUrl                 pgtype.Text
	EventSource               string
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	DeletedAt                 pgtype.Timestamptz
	VendorCode                pgtype.Text
	IceNumber                 pgtype.Text
	PayableAccountCode        pgtype.Text
	DefaultExpenseAccountCode pgtype.Text
	DefaultVatRuleCode        pgtype.Text
}

type ToroCoreAgentConfiguration struct {
	ID           pgtype.UUID
	Name         string
	Description  pgtype.Text
	SystemPrompt string
	SdkClient    string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreAgentMemoryRule struct {
	ID          pgtype.UUID
	RealmID     string
	EntityType  string
	EntityValue string
	Instruction string
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type ToroCoreAseDag struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Name            string
	DagConfig       []byte
	HyperParameters []byte
	Prompts         []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ToroCoreAseDagVersion struct {
	ID              pgtype.UUID
	DagID           pgtype.UUID
	VersionNumber   int32
	DagConfig       []byte
	HyperParameters []byte
	Prompts         []byte
	CreatedAt       pgtype.Timestamptz
}

type ToroCoreAseVectorMemory struct {
	ID          pgtype.UUID
	RealmID     string
	Namespace   string
	SourceType  string
	RawText     string
	Embedding   string
	SourceRowID pgtype.UUID
	Metadata    []byte
	EmbeddedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ToroCoreConversation struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	Source       string
	ExternalID   string
	FromHandle   string
	ToHandle     string
	ReplyTo      pgtype.Text
	InReplyTo    pgtype.Text
	Subject      pgtype.Text
	BodyText     pgtype.Text
	BodyHtml     pgtype.Text
	StrippedText pgtype.Text
	Metadata     []byte
	Role         string
	Delivered    []byte
	Bounced      []byte
	Opened       []byte
	Clicked      []byte
	Complained   []byte
	SessionID    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreConversationSession struct {
	ID                pgtype.UUID
	EntityID          pgtype.UUID
	ExternalID        pgtype.Text
	Source            string
	ParticipantHandle string
	ToroHandle        string
	Subject           pgtype.Text
	Status            string
	SystemPrompt      pgtype.Text
	ContextJson       []byte
	LastActivityAt    pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ToroCoreDocument struct {
	ID            pgtype.UUID
	SessionID     string
	DocumentType  string
	FileName      string
	MimeType      string
	S3Url         string
	Sha256        pgtype.Text
	OcrStatus     string
	RawOcrJson    []byte
	ExtractedText pgtype.Text
	SenderEmail   pgtype.Text
	SourceChannel string
	Metadata      []byte
	ProcessedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ToroCoreEnterpriseAgentAlias struct {
	ID         pgtype.UUID
	DomainID   pgtype.UUID
	AgentAlias string
	TargetDid  string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToroCoreEnterpriseDomain struct {
	ID                      pgtype.UUID
	EntityID                pgtype.UUID
	DomainName              string
	DkimPrivateKeyEncrypted string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ToroCoreEnterpriseFact struct {
	FactID     pgtype.UUID
	SessionID  string
	Namespace  string
	EntityType string
	Uri        string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToroCoreEnterpriseRelationship struct {
	RelationshipID pgtype.UUID
	SessionID      string
	Namespace      string
	FromFactID     pgtype.UUID
	ToFactID       pgtype.UUID
	RelationType   string
	Weight         float64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ToroCoreEntity struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	EntityType  string
	ErpProvider pgtype.Text
	ErpTenantID pgtype.Text
	PlanTier    pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ToroCoreErpConnection struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	ErpSystem    string
	RealmID      string
	AccessToken  string
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	// Timestamp of last successful CDC sync. Used as changedSince parameter for CDC API calls. Max lookback is 30 days per QBO limits.
	LastSyncTimestamp pgtype.Timestamptz
	// Timestamp of last successful Account webhook. Used by CDC to fetch only missed events.
	LastWebhookAccount pgtype.Timestamptz
	// Timestamp of last successful Vendor webhook. Used by CDC to fetch only missed events.
	LastWebhookVendor pgtype.Timestamptz
	// Timestamp of last successful Customer webhook. Used by CDC to fetch only missed events.
	LastWebhookCustomer pgtype.Timestamptz
	// Timestamp of last successful Invoice webhook. Used by CDC to fetch only missed events.
	LastWebhookInvoice pgtype.Timestamptz
	// Timestamp of last successful Bill webhook. Used by CDC to fetch only missed events.
	LastWebhookBill pgtype.Timestamptz
	// Timestamp of last successful Purchase/Transaction webhook. Used by CDC to fetch only missed events.
	LastWebhookTransaction  pgtype.Timestamptz
	LastWebhookDeposit      pgtype.Timestamptz
	LastWebhookPayment      pgtype.Timestamptz
	LastWebhookSalesReceipt pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ToroCoreFinancialConnectionAttempt struct {
	ID               pgtype.UUID
	EntityID         pgtype.UUID
	FcSessionID      string
	StripeCustomerID string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ToroCoreForeignServiceRunningTotal struct {
	ID                         pgtype.UUID
	RealmID                    string
	ProviderID                 pgtype.UUID
	FiscalYear                 int32
	FiscalMonth                int32
	CumulativeGrossInvoicedMad pgtype.Numeric
	CumulativeRasWithheldMad   pgtype.Numeric
	CumulativeNetPaidMad       pgtype.Numeric
	TransactionCount           int32
	DgiDeclarationStatus       string
	LastTransactionAt          pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
}

type ToroCoreLinkedBankAccount struct {
	ID              pgtype.UUID
	EntityID        pgtype.UUID
	FcSessionID     string
	StripeAccountID string
	InstitutionName string
	Last4           pgtype.Text
	Subcategory     pgtype.Text
	Status          string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ToroCoreLlmPricingModel struct {
	ID              pgtype.UUID
	Model           string
	Provider        string
	InputCostPer1m  pgtype.Numeric
	OutputCostPer1m pgtype.Numeric
	CacheCostPer1m  pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ToroCoreLlmTurnMetric struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	ConversationID  pgtype.UUID
	DagID           pgtype.Text
	NodeID          pgtype.Text
	AgentID         pgtype.Text
	Model           string
	Provider        pgtype.Text
	InputTokens     int32
	OutputTokens    int32
	TotalTokens     int32
	CostUsd         pgtype.Numeric
	Entropy         pgtype.Float8
	Confidence      pgtype.Float8
	StateTransition pgtype.Text
	HoldReason      pgtype.Text
	CampaignID      pgtype.UUID
	ProspectID      pgtype.UUID
	StepNumber      pgtype.Int4
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	PayerTenantID   pgtype.UUID
}

type ToroCoreMasterMerchant struct {
	ID                 pgtype.UUID
	NormalizedName     string
	LegalName          pgtype.Text
	CountryCode        string
	MerchantCategory   string
	Ice                pgtype.Text
	IdentifiantFiscal  pgtype.Text
	RegistreCommerce   pgtype.Text
	CnssNumber         pgtype.Text
	PrimaryDomain      pgtype.Text
	LogoUrl            pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
	DefaultTvaAccount  string
	IsTvaDeductible    bool
	IsForeignService   bool
	RasApplicable      bool
	RasRate            pgtype.Numeric
	ConfidenceWeight   pgtype.Numeric
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ToroCoreMasterPattern struct {
	ID               pgtype.UUID
	MasterMerchantID pgtype.UUID
	CleanedStem      string
	PatternType      string
	RegexPattern     pgtype.Text
	IsIntermediary   bool
	MatchCount       int64
	CreatedAt        pgtype.Timestamptz
}

type ToroCoreMoroccanMerchantMultilingualAlias struct {
	ID               pgtype.UUID
	MasterMerchantID pgtype.UUID
	AliasVariant     string
	ScriptType       string
	LanguageCode     string
	IsPrimary        bool
	ConfidenceScore  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
}

type ToroCoreNonResidentForeignProvider struct {
	ID                     pgtype.UUID
	MasterMerchantID       pgtype.UUID
	ProviderName           string
	HeadquartersCountry    string
	TaxResidencyStatus     string
	VatWithholdingRate     pgtype.Numeric
	ServiceType            string
	PcgmExpenseAccount     string
	PcgmWithholdingAccount string
	IsActive               bool
	StatutoryLegalBasis    string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ToroCoreRefreshToken struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ToroCoreScheduledJob struct {
	ID           pgtype.UUID
	QueueSubject string
	PayloadJson  []byte
	FireAt       pgtype.Timestamptz
	Status       string
	CreatedAt    pgtype.Timestamptz
	FiredAt      pgtype.Timestamptz
}

type ToroCoreSlackTenantMapping struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	SlackTeamID      string
	SlackAccessToken string
	SlackBotUserID   string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ToroCoreStalledMessage struct {
	ID              pgtype.UUID
	AgentDid        string
	OriginalSubject string
	Payload         []byte
	ErrorReason     string
	CreatedAt       pgtype.Timestamptz
}

type ToroCoreStripeCheckoutSession struct {
	ID              pgtype.UUID
	EntityID        pgtype.UUID
	StripeSessionID string
	AmountCents     int64
	ProductName     string
	Status          string
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ToroCoreSystemVectorConfig struct {
	ID                      int32
	EmbeddingProvider       string
	EmbeddingModel          string
	RetrievalTopK           int32
	HydratorIntervalSeconds int32
	HydratorBatchSize       int32
	HydratorMinConfidence   float64
	ScannNumLeaves          int32
	UpdatedAt               pgtype.Timestamptz
}

type ToroCoreTeamInvite struct {
	ID        pgtype.UUID
	Token     string
	Email     string
	TenantID  string
	FirmName  string
	IsUsed    bool
	CreatedAt pgtype.Timestamptz
}

type ToroCoreTelemetryEvent struct {
	Time       pgtype.Timestamptz
	TraceID    pgtype.UUID
	EntityID   pgtype.UUID
	Service    string
	EventType  string
	DurationMs pgtype.Int4
	Meta       []byte
}

type ToroCoreToroThreadsMapping struct {
	ID                   pgtype.UUID
	ConversationID       pgtype.UUID
	TenantID             pgtype.UUID
	SlackChannelID       string
	SlackParentTs        string
	EmailLatestMessageID string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ToroCoreTransaction struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	ExternalID   string
	AmountMicros int64
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ToroCoreUser struct {
	ID                 pgtype.UUID
	EntityID           pgtype.UUID
	Email              string
	PasswordHash       string
	FullName           pgtype.Text
	Role               pgtype.Text
	UserType           string
	IsActive           pgtype.Bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	VcooActiveBlockers []string
	VcooHistory        []byte
	VcooState          []byte
}

type ToroCoreWallet struct {
	ID                     pgtype.UUID
	EntityID               pgtype.UUID
	TotalPurchasedMicrions int64
	TotalBurnedMicrions    int64
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ToroCoreWalletTransaction struct {
	ID              pgtype.UUID
	WalletID        pgtype.UUID
	TransactionType string
	MicrionAmount   int64
	UsdAmount       pgtype.Int8
	StripeSessionID pgtype.Text
	NatsRevision    pgtype.Int8
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
}

type ToroCoreWebhooksProviderconnection struct {
	ID            pgtype.UUID
	ConnectionID  string
	WebhookSecret string
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ToroCoreWorkflow struct {
	ID         pgtype.UUID
	EntityID   pgtype.UUID
	State      []byte
	SequenceID int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToroCoreWorkflowBlueprint struct {
	Name         string
	UserID       pgtype.UUID
	TriggerTopic string
	Definition   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreWorkflowDispatchOutbox struct {
	ID             pgtype.UUID
	WorkflowID     pgtype.UUID
	StepID         string
	ConversationID string
	TargetSubject  string
	Envelope       []byte
	Status         string
	Attempts       int32
	NextAttemptAt  pgtype.Timestamptz
	LeasedUntil    pgtype.Timestamptz
	LastError      pgtype.Text
	DeliveredAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ToroCoreWorkflowHistory struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	Role       string
	Content    []byte
	CreatedAt  pgtype.Timestamptz
}
