// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentPerformanceHourly struct {
	Bucket        interface{}
	AgentID       interface{}
	TotalTasks    int64
	AvgConfidence float64
	TotalCost     int64
}

type ShadowErpAccount struct {
	ID                            pgtype.UUID
	QboID                         string
	RealmID                       string
	Name                          string
	AccountType                   string
	AccountSubType                pgtype.Text
	Classification                pgtype.Text
	FullyQualifiedName            pgtype.Text
	Active                        pgtype.Bool
	SyncToken                     string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	DeletedAt                     pgtype.Timestamptz
	Domain                        pgtype.Text
	CurrencyRefName               pgtype.Text
	CurrencyRefValue              pgtype.Text
	CurrentBalanceWithSubAccounts pgtype.Numeric
	Sparse                        pgtype.Bool
	QboCreatedTime                pgtype.Timestamptz
	QboUpdatedTime                pgtype.Timestamptz
	CurrentBalance                pgtype.Numeric
	SubAccount                    pgtype.Bool
}

// Records when users correct AI predictions for learning and synonym updates
type ShadowErpAiCorrection struct {
	ID      pgtype.UUID
	RealmID string
	UserID  pgtype.UUID
	// The original text that AI tried to match
	RawInput     string
	AiPrediction pgtype.Text
	// The correct entity ID provided by user
	UserCorrection  string
	CorrectionType  string
	ConfidenceScore pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
}

type ShadowErpBill struct {
	ID          pgtype.UUID
	QboID       string
	RealmID     string
	VendorID    pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpCustomer struct {
	ID          pgtype.UUID
	QboID       string
	RealmID     string
	DisplayName string
	SyncToken   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpInvoice struct {
	ID          pgtype.UUID
	QboID       string
	RealmID     string
	CustomerID  pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpProposedTransaction struct {
	ID                 pgtype.UUID
	RealmID            string
	SourceType         string
	RawAmount          pgtype.Numeric
	RawDate            pgtype.Date
	RawDescription     pgtype.Text
	PredictedVendorID  pgtype.UUID
	PredictedAccountID pgtype.UUID
	ConfidenceScore    pgtype.Numeric
	AiReasoning        pgtype.Text
	QboTransactionID   pgtype.Text
	SyncStatus         pgtype.Text
	ErrorMessage       pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ShadowErpRuleAuditLog struct {
	ID            int32
	RealmID       string
	TransactionID pgtype.UUID
	RuleGroupID   pgtype.Int4
	Matched       bool
	// Verbose match explanation: JSON containing condition-level results (maps to MatchExplanation struct)
	MatchInfo           []byte
	HumanReadableReason string
	CreatedAt           pgtype.Timestamptz
}

type ShadowErpRuleCondition struct {
	ID          int32
	RuleGroupID int32
	Field       string
	Operator    string
	Value       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShadowErpRuleGroup struct {
	ID              int32
	RealmID         string
	Name            string
	Logic           string
	Priority        int32
	Keywords        pgtype.Text
	Active          bool
	TargetAccountID pgtype.UUID
	TargetVendorID  pgtype.UUID
	ParentID        pgtype.Int4
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Tracks Pinecone vector database sync state per ERP realm
type ShadowErpVectorSyncState struct {
	RealmID string
	// Last Chart of Accounts sync to Pinecone
	LastCoaSync      pgtype.Timestamptz
	LastVendorSync   pgtype.Timestamptz
	LastCustomerSync pgtype.Timestamptz
	// Number of account vectors in Pinecone
	CoaVectorCount      pgtype.Int4
	VendorVectorCount   pgtype.Int4
	CustomerVectorCount pgtype.Int4
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ShadowErpVendor struct {
	ID                 pgtype.UUID
	QboID              string
	RealmID            string
	DisplayName        string
	SyncToken          string
	LastKnownAccountID pgtype.UUID
	AiSynonyms         []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
}

type TelemetryEvent struct {
	Time       pgtype.Timestamptz
	TraceID    pgtype.UUID
	EntityID   pgtype.UUID
	Service    string
	EventType  string
	DurationMs pgtype.Int4
	Meta       []byte
}

type ToroCoreAgentMemoryRule struct {
	ID          pgtype.UUID
	RealmID     string
	EntityType  string
	EntityValue string
	Instruction string
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type ToroCoreEntity struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	EntityType  string
	ErpProvider pgtype.Text
	ErpTenantID pgtype.Text
	PlanTier    pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ToroCoreQboConnection struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	RealmID      string
	AccessToken  string
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	// Timestamp of last successful CDC sync. Used as changedSince parameter for CDC API calls. Max lookback is 30 days per QBO limits.
	LastSyncTimestamp pgtype.Timestamptz
	// Timestamp of last successful Account webhook. Used by CDC to fetch only missed events.
	LastWebhookAccount pgtype.Timestamptz
	// Timestamp of last successful Vendor webhook. Used by CDC to fetch only missed events.
	LastWebhookVendor pgtype.Timestamptz
	// Timestamp of last successful Customer webhook. Used by CDC to fetch only missed events.
	LastWebhookCustomer pgtype.Timestamptz
	// Timestamp of last successful Invoice webhook. Used by CDC to fetch only missed events.
	LastWebhookInvoice pgtype.Timestamptz
	// Timestamp of last successful Bill webhook. Used by CDC to fetch only missed events.
	LastWebhookBill pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ToroCoreRefreshToken struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ToroCoreTransaction struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	ExternalID   string
	AmountMicros int64
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ToroCoreUser struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	Email        string
	PasswordHash string
	FullName     pgtype.Text
	Role         pgtype.Text
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreWebhooksProviderconnection struct {
	ID            pgtype.UUID
	ConnectionID  string
	WebhookSecret string
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
