package workers

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"github.com/nats-io/nats.go"


	"github.com/Yankzy/usetoro/internal/config"
	"github.com/Yankzy/usetoro/internal/database"
	"github.com/Yankzy/usetoro/internal/erp/sage/pnm"
	"github.com/Yankzy/usetoro/tap/pkg/core"
)

// FileGeneratorPayload defines the input structure for file generation.
type FileGeneratorPayload struct {
	FileType   string                 `json:"file_type"`   // "pdf", "csv", "pnm", "txt"
	FileName   string                 `json:"file_name"`   // e.g., "reconciliation.pnm"
	SessionID  string                 `json:"session_id"`  // Associated session ID
	RealmID    string                 `json:"realm_id"`    // Tenant / realm ID
	Header     []string               `json:"header"`      // Used for CSV headers
	Rows       [][]string             `json:"rows"`        // Used for CSV rows
	PNMLines   []pnm.JournalEntryLine `json:"pnm_lines"`   // Used for PNM generation
	PDFContent string                 `json:"pdf_content"` // Text or structured content for PDF/TXT
}

// FileGeneratorResult defines the output generated by the worker.
type FileGeneratorResult struct {
	FileType      string                 `json:"file_type"`
	FileName      string                 `json:"file_name"`
	ContentType   string                 `json:"content_type"`
	ContentLength int                    `json:"content_length"`
	ContentBase64 string                 `json:"content_base64"`
	Attachment    map[string]interface{} `json:"attachment"`
}

type FileGeneratorWorker struct {
	logger *slog.Logger
	cfg    *config.Config
	nc     *nats.Conn
	db     *database.Queries
}

func init() {
	RegisterFactory(func(deps Dependencies) (Worker, error) {
		return &FileGeneratorWorker{
			logger: deps.Logger.With("worker", "file_generator"),
			cfg:    deps.Config,
			nc:     deps.Queue,
			db:     deps.Store.Queries,
		}, nil
	})
}

func (w *FileGeneratorWorker) Init(ctx context.Context) error {
	w.logger.Info("FileGeneratorWorker initialized")
	return nil
}

func (w *FileGeneratorWorker) Subscriptions() []SubscriptionConfig {
	_, workerCfg := w.cfg.Workers.GetForWorker(w)
	activityType := workerCfg.ActivityType
	if activityType == "" {
		activityType = "workers.file_generator"
	}

	subject := workerCfg.Subject
	if subject == "" {
		if derived, err := core.BuildWorkerInboxFromActivity(activityType); err == nil {
			subject = derived
		} else {
			subject = "worker.inbox.file_generator"
		}
	}

	group := workerCfg.Group
	if group == "" {
		group = "worker-inbox-file_generator-group"
	}

	return []SubscriptionConfig{
		{
			Subject: subject,
			Group:   group,
			Options: []nats.SubOpt{
				nats.Durable(durableFromSubject(subject)),
				nats.DeliverAll(),
				nats.AckExplicit(),
			},
		},
	}
}

// Handle routes request payload to specific generator methods via switch statement.
func (w *FileGeneratorWorker) Handle(ctx context.Context, msg *nats.Msg) error {
	var env core.Envelope
	if err := json.Unmarshal(msg.Data, &env); err != nil {
		w.logger.Error("FileGeneratorWorker: failed to unmarshal envelope", "error", err)
		return err
	}

	if env.Performative != core.REQUEST {
		return nil
	}

	var payload FileGeneratorPayload
	if err := json.Unmarshal(env.Body, &payload); err != nil {
		w.logger.Error("FileGeneratorWorker: failed to unmarshal payload body", "error", err)
		return err
	}

	fileTypeNormalized := strings.ToLower(strings.TrimSpace(payload.FileType))
	if fileTypeNormalized == "" {
		w.logger.Error("FileGeneratorWorker: missing file_type")
		return fmt.Errorf("missing file_type")
	}

	w.logger.Info("FileGeneratorWorker: processing request", "file_type", fileTypeNormalized, "file_name", payload.FileName)

	var (
		fileBytes   []byte
		fileName    string
		contentType string
		err         error
	)

	// Switch statement routing to distinct generation methods
	switch fileTypeNormalized {
	case "pnm":
		fileBytes, fileName, contentType, err = w.GeneratePNM(payload)
	case "csv":
		fileBytes, fileName, contentType, err = w.GenerateCSV(payload)
	case "pdf":
		fileBytes, fileName, contentType, err = w.GeneratePDF(payload)
	case "txt", "text":
		fileBytes, fileName, contentType, err = w.GenerateTXT(payload)
	default:
		w.logger.Error("FileGeneratorWorker: unsupported file_type", "file_type", payload.FileType)
		return fmt.Errorf("unsupported file_type: %s", payload.FileType)
	}

	if err != nil {
		w.logger.Error("FileGeneratorWorker: generation failed", "file_type", fileTypeNormalized, "error", err)
		return err
	}

	base64Content := base64.StdEncoding.EncodeToString(fileBytes)

	result := FileGeneratorResult{
		FileType:      fileTypeNormalized,
		FileName:      fileName,
		ContentType:   contentType,
		ContentLength: len(fileBytes),
		ContentBase64: base64Content,
		Attachment: map[string]interface{}{
			"Name":          fileName,
			"ContentType":   contentType,
			"ContentLength": len(fileBytes),
			"Content":       base64Content,
		},
	}

	w.logger.Info("FileGeneratorWorker: successfully generated file", "file_name", fileName, "size_bytes", len(fileBytes))

	// Respond via NATS reply topic if present
	if msg.Reply != "" && w.nc != nil {
		resBytes, _ := json.Marshal(result)
		if err := w.nc.Publish(msg.Reply, resBytes); err != nil {
			w.logger.Error("FileGeneratorWorker: failed to publish reply", "error", err)
		}
	}

	return nil
}

// Distinct Method: GeneratePNM creates Sage 100 (.PNM) journal entry import files.
func (w *FileGeneratorWorker) GeneratePNM(payload FileGeneratorPayload) ([]byte, string, string, error) {
	lines := payload.PNMLines
	if len(lines) == 0 && len(payload.Rows) > 0 {
		// Convert generic rows to JournalEntryLines if provided
		now := time.Now()
		for _, row := range payload.Rows {
			if len(row) >= 6 {
				lines = append(lines, pnm.JournalEntryLine{
					JournalCode: row[0],
					Date:        now,
					GeneralAcc:  row[1],
					PieceRef:    row[2],
					Libelle:     row[3],
					Debit:       parseFloat(row[4]),
					Credit:      parseFloat(row[5]),
				})
			}
		}
	}

	if len(lines) == 0 {
		return nil, "", "", fmt.Errorf("cannot generate pnm file with 0 journal lines")
	}

	pnmBytes := pnm.FormatPNM(lines, pnm.DefaultTemplate())

	fileName := payload.FileName
	if fileName == "" {
		fileName = "import_sage.pnm"
	} else if !strings.HasSuffix(strings.ToLower(fileName), ".pnm") {
		fileName = fileName + ".pnm"
	}

	return pnmBytes, fileName, "text/plain", nil
}

// Distinct Method: GenerateCSV creates comma/semicolon separated spreadsheet files.
func (w *FileGeneratorWorker) GenerateCSV(payload FileGeneratorPayload) ([]byte, string, string, error) {
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	header := payload.Header
	rows := payload.Rows

	if len(rows) == 0 {
		return nil, "", "", fmt.Errorf("cannot generate csv file with 0 data rows")
	}

	if len(header) == 0 {
		header = []string{"JournalCode", "Date", "GeneralAccount", "AuxAccount", "PieceRef", "Libelle", "Debit", "Credit"}
	}

	if len(header) > 0 {
		if err := writer.Write(header); err != nil {
			return nil, "", "", fmt.Errorf("failed to write csv header: %w", err)
		}
	}

	for _, row := range rows {
		if err := writer.Write(row); err != nil {
			return nil, "", "", fmt.Errorf("failed to write csv row: %w", err)
		}
	}

	writer.Flush()
	if err := writer.Error(); err != nil {
		return nil, "", "", fmt.Errorf("csv writer flush error: %w", err)
	}

	fileName := payload.FileName
	if fileName == "" {
		fileName = "export.csv"
	} else if !strings.HasSuffix(strings.ToLower(fileName), ".csv") {
		fileName = fileName + ".csv"
	}

	return buf.Bytes(), fileName, "text/csv", nil
}


// Distinct Method: GeneratePDF creates standard PDF documents.
func (w *FileGeneratorWorker) GeneratePDF(payload FileGeneratorPayload) ([]byte, string, string, error) {
	content := payload.PDFContent
	if content == "" && len(payload.Rows) > 0 {
		if len(payload.Rows) == 0 {
			return nil, "", "", fmt.Errorf("cannot generate pdf file with 0 rows")
		}
		var lines []string
		if len(payload.Header) > 0 {
			lines = append(lines, strings.Join(payload.Header, " | "))
		}
		for _, row := range payload.Rows {
			lines = append(lines, strings.Join(row, " | "))
		}
		content = strings.Join(lines, "\n")
	}
	if content == "" {
		content = "Document export for " + payload.FileName
	}

	// Format minimal valid PDF 1.4 stream
	pdfBytes := formatMinimalPDFStream(content)

	fileName := payload.FileName
	if fileName == "" {
		fileName = "document.pdf"
	} else if !strings.HasSuffix(strings.ToLower(fileName), ".pdf") {
		fileName = fileName + ".pdf"
	}

	return pdfBytes, fileName, "application/pdf", nil
}

// Distinct Method: GenerateTXT creates plain text files.
func (w *FileGeneratorWorker) GenerateTXT(payload FileGeneratorPayload) ([]byte, string, string, error) {
	content := payload.PDFContent
	if content == "" && len(payload.Rows) > 0 {
		var lines []string
		for _, row := range payload.Rows {
			lines = append(lines, strings.Join(row, "\t"))
		}
		content = strings.Join(lines, "\n")
	}

	fileName := payload.FileName
	if fileName == "" {
		fileName = "export.txt"
	} else if !strings.HasSuffix(strings.ToLower(fileName), ".txt") {
		fileName = fileName + ".txt"
	}

	return []byte(content), fileName, "text/plain", nil
}

// formatMinimalPDFStream builds a minimal, valid PDF binary byte stream.
func formatMinimalPDFStream(textContent string) []byte {
	lines := strings.Split(strings.TrimSpace(textContent), "\n")
	var textStream bytes.Buffer
	for _, line := range lines {
		// Escape parenthesis
		cleanLine := strings.ReplaceAll(line, "(", "\\(")
		cleanLine = strings.ReplaceAll(cleanLine, ")", "\\)")
		textStream.WriteString(fmt.Sprintf("(%s) Tj\n0 -14 Td\n", cleanLine))
	}

	stream := fmt.Sprintf("BT\n/F1 10 Tf\n50 730 Td\n%sET", textStream.String())
	streamLen := len(stream)

	pdf := fmt.Sprintf(`%%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length %d >>
stream
%s
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000227 00000 n 
0000000299 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
%d
%%%%EOF`, streamLen, stream, 349+streamLen)

	return []byte(pdf)
}

func parseFloat(s string) float64 {
	var val float64
	fmt.Sscanf(strings.ReplaceAll(s, ",", ""), "%f", &val)
	return val
}
