package workers

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	"github.com/Yankzy/usetoro/internal/config"
	"github.com/Yankzy/usetoro/internal/database"
	"github.com/Yankzy/usetoro/internal/services/enrichment"
	"github.com/Yankzy/usetoro/tap/pkg/core"
	"github.com/Yankzy/usetoro/tap/workflows"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/nats-io/nats.go"
)

// MoroccanEnrichmentPayload defines the incoming task payload for Moroccan CEE enrichment.
type MoroccanEnrichmentPayload struct {
	SessionID string `json:"session_id"`
	RealmID   string `json:"realm_id,omitempty"`
	EntityID  string `json:"entity_id,omitempty"`
}

// MoroccanEnrichmentResult defines the output proof data generated by the worker.
type MoroccanEnrichmentResult struct {
	SessionID      string  `json:"session_id"`
	RealmID        string  `json:"realm_id"`
	Status         string  `json:"status"`
	TotalProcessed int     `json:"total_processed"`
	EnrichedCount  int     `json:"enriched_count"`
	DurationMS     float64 `json:"duration_ms"`
}

// MoroccanEnrichmentWorker is a dedicated, deterministic background worker that executes
// the Moroccan Cognitive Financial Enrichment Engine (CEE-MA) and persists results directly
// into fignode.staging_transactions before DAG execution.
type MoroccanEnrichmentWorker struct {
	logger *slog.Logger
	cfg    *config.Config
	nc     *nats.Conn
	db     *database.Queries
	dbPool *pgxpool.Pool
	engine *enrichment.MoroccanEnrichmentEngine
}

func init() {
	RegisterFactory(func(deps Dependencies) (Worker, error) {
		return &MoroccanEnrichmentWorker{
			logger: deps.Logger.With("worker", "moroccan_enrichment"),
			cfg:    deps.Config,
			nc:     deps.Queue,
			db:     deps.Store.Queries,
			dbPool: deps.DBPool,
			engine: enrichment.NewMoroccanEnrichmentEngine(),
		}, nil
	})
}

func (w *MoroccanEnrichmentWorker) Init(ctx context.Context) error {
	w.logger.Info("MoroccanEnrichmentWorker initialized")
	return nil
}

func (w *MoroccanEnrichmentWorker) Subscriptions() []SubscriptionConfig {
	activityType := "workers.pcm.moroccan_enrichment"
	subject := "worker.inbox.pcm_moroccan_enrichment"
	if derived, err := core.BuildWorkerInboxFromActivity(activityType); err == nil {
		subject = derived
	}
	group := "worker-inbox-pcm_moroccan_enrichment-group"

	return []SubscriptionConfig{
		{
			Subject: subject,
			Group:   group,
			Options: []nats.SubOpt{
				nats.Durable(durableFromSubject(subject)),
				nats.DeliverAll(),
				nats.AckExplicit(),
			},
		},
	}
}

func (w *MoroccanEnrichmentWorker) Handle(ctx context.Context, msg *nats.Msg) error {
	start := time.Now()
	reqEnv, payload, err := w.parseInboundMessage(msg)
	if err != nil {
		w.logger.Error("MoroccanEnrichmentWorker: failed to parse payload", "error", err)
		return err
	}

	if payload.SessionID == "" {
		w.logger.Error("MoroccanEnrichmentWorker: missing session_id in payload")
		return fmt.Errorf("missing session_id")
	}

	w.logger.Info("MoroccanEnrichmentWorker: starting deterministic enrichment",
		"session_id", payload.SessionID,
		"realm_id", payload.RealmID,
	)

	var pgSessionID pgtype.UUID
	if err := pgSessionID.Scan(payload.SessionID); err != nil {
		w.logger.Error("MoroccanEnrichmentWorker: invalid session_id UUID", "session_id", payload.SessionID, "error", err)
		return err
	}

	// 1. Fetch pending staging transactions for this session
	txns, err := w.fetchPendingTransactions(ctx, pgSessionID)
	if err != nil {
		w.logger.Error("MoroccanEnrichmentWorker: failed to fetch staging transactions", "session_id", payload.SessionID, "error", err)
		return err
	}

	if len(txns) == 0 {
		w.logger.Info("MoroccanEnrichmentWorker: no pending staging transactions found for session", "session_id", payload.SessionID)
		return w.publishCompletionProof(&payload, &reqEnv, 0, 0, time.Since(start), msg.Reply)
	}

	// 2. Process transactions deterministically via CEE-MA
	enrichedCount := 0
	for _, tx := range txns {
		rawAmtStr := strings.ReplaceAll(tx.RawAmount, ",", "")
		rawAmtStr = strings.ReplaceAll(rawAmtStr, " ", "")
		amount, _ := strconv.ParseFloat(rawAmtStr, 64)
		if amount < 0 {
			amount = -amount
		}

		direction := enrichment.CashOutflow
		if tx.CashDirection.Valid && strings.ToUpper(tx.CashDirection.String) == "INFLOW" {
			direction = enrichment.CashInflow
		}

		txDate := time.Now()
		if tx.ParsedDate.Valid {
			txDate = tx.ParsedDate.Time
		}

		accCode := "514100" // Default Banque (5141)
		if tx.AccountType.Valid && strings.Contains(strings.ToUpper(tx.AccountType.String), "CASH") {
			accCode = "516100" // Caisse (5161)
		}

		rawDesc := ""
		if tx.RawDescription.Valid {
			rawDesc = tx.RawDescription.String
		}

		rawTxn := enrichment.RawTransaction{
			TransactionID:   uuid.UUID(tx.ID.Bytes).String(),
			RawDescription:  rawDesc,
			Amount:          amount,
			Currency:        "MAD",
			CashDirection:   direction,
			TransactionDate: txDate,
			AccountCode:     accCode,
		}

		// Run Moroccan Cognitive Enrichment Engine
		envelope := w.engine.EnrichTransaction(ctx, payload.RealmID, rawTxn)

		// Persist enriched envelope directly to database row
		if err := w.persistEnrichment(ctx, tx.ID, envelope); err != nil {
			w.logger.Error("MoroccanEnrichmentWorker: failed to persist enrichment", "row_id", uuid.UUID(tx.ID.Bytes).String(), "error", err)
			continue
		}
		enrichedCount++
	}

	elapsed := time.Since(start)
	w.logger.Info("MoroccanEnrichmentWorker: completed deterministic enrichment",
		"session_id", payload.SessionID,
		"total", len(txns),
		"enriched", enrichedCount,
		"duration_ms", float64(elapsed.Microseconds())/1000.0,
	)

	return w.publishCompletionProof(&payload, &reqEnv, len(txns), enrichedCount, elapsed, msg.Reply)
}

func (w *MoroccanEnrichmentWorker) parseInboundMessage(msg *nats.Msg) (core.Envelope, MoroccanEnrichmentPayload, error) {
	var reqEnv core.Envelope
	var payload MoroccanEnrichmentPayload

	if err := json.Unmarshal(msg.Data, &reqEnv); err == nil && reqEnv.Performative == core.REQUEST {
		_ = core.UnmarshalTaskPayload(reqEnv.Body, &payload)
		return reqEnv, payload, nil
	}

	if err := json.Unmarshal(msg.Data, &payload); err == nil && payload.SessionID != "" {
		return reqEnv, payload, nil
	}

	// Try wrapping map format {"session_id": "...", "realm_id": "..."}
	var rawMap map[string]interface{}
	if err := json.Unmarshal(msg.Data, &rawMap); err == nil {
		if sid, ok := rawMap["session_id"].(string); ok {
			payload.SessionID = sid
		}
		if rid, ok := rawMap["realm_id"].(string); ok {
			payload.RealmID = rid
		}
		if eid, ok := rawMap["entity_id"].(string); ok {
			payload.EntityID = eid
		}
		return reqEnv, payload, nil
	}

	return reqEnv, payload, fmt.Errorf("unsupported message format")
}

func (w *MoroccanEnrichmentWorker) fetchPendingTransactions(ctx context.Context, sessionID pgtype.UUID) ([]database.FignodeStagingTransaction, error) {
	if w.dbPool != nil {
		rows, err := w.dbPool.Query(ctx, `
			SELECT id, session_id, raw_date, parsed_date, raw_description, raw_amount,
			       cash_direction, iso_currency_code, transaction_hash, erp_transaction_id,
			       transaction_id, pending_transaction_id, merchant_name, logo_url, category,
			       is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id,
			       predicted_customer_name, predicted_account_id, predicted_account_name,
			       confidence_score, ai_reasoning, human_action, swiped_by, swiped_at,
			       override_vendor_id, override_customer_id, override_account_id, duplicate_of,
			       is_recurring, split_suggestion, status, error_message, reconciled_at,
			       reconciled_by, rule_group_id, macro_class, account_type, synced_at,
			       ase_execution_trace, created_at, updated_at
			FROM fignode.staging_transactions
			WHERE session_id = $1
			ORDER BY created_at ASC
		`, sessionID)
		if err != nil {
			return nil, err
		}
		defer rows.Close()

		var txns []database.FignodeStagingTransaction
		for rows.Next() {
			var t database.FignodeStagingTransaction
			if err := rows.Scan(
				&t.ID, &t.SessionID, &t.RawDate, &t.ParsedDate, &t.RawDescription, &t.RawAmount,
				&t.CashDirection, &t.IsoCurrencyCode, &t.TransactionHash, &t.ErpTransactionID,
				&t.TransactionID, &t.PendingTransactionID, &t.MerchantName, &t.LogoUrl, &t.Category,
				&t.IsPending, &t.PredictedVendorID, &t.PredictedVendorName, &t.PredictedCustomerID,
				&t.PredictedCustomerName, &t.PredictedAccountID, &t.PredictedAccountName,
				&t.ConfidenceScore, &t.AiReasoning, &t.HumanAction, &t.SwipedBy, &t.SwipedAt,
				&t.OverrideVendorID, &t.OverrideCustomerID, &t.OverrideAccountID, &t.DuplicateOf,
				&t.IsRecurring, &t.SplitSuggestion, &t.Status, &t.ErrorMessage, &t.ReconciledAt,
				&t.ReconciledBy, &t.RuleGroupID, &t.MacroClass, &t.AccountType, &t.SyncedAt,
				&t.AseExecutionTrace, &t.CreatedAt, &t.UpdatedAt,
			); err != nil {
				return nil, err
			}
			txns = append(txns, t)
		}
		return txns, nil
	}

	if w.db != nil {
		return w.db.GetPendingStagingTransactions(ctx, sessionID)
	}

	return nil, fmt.Errorf("no database connection available")
}

func (w *MoroccanEnrichmentWorker) persistEnrichment(ctx context.Context, rowID pgtype.UUID, envelope enrichment.AnnotatedMoroccanTransactionEnvelope) error {
	envelopeJSON, err := json.Marshal(envelope)
	if err != nil {
		return err
	}

	vendorName := envelope.Counterparty.NormalizedName
	accountName := envelope.PCGMAccounting.AccountLabel
	if accountName == "" {
		accountName = envelope.PCGMAccounting.SuggestedAccount
	}
	score := envelope.ConfidenceScore
	aiReasoning := fmt.Sprintf("Moroccan CEE: %s (%s) -> Account %s (TVA: %.0f%%)",
		envelope.Counterparty.NormalizedName,
		envelope.Counterparty.MerchantCategory,
		envelope.PCGMAccounting.SuggestedAccount,
		envelope.PCGMAccounting.DefaultTVARate*100,
	)
	merchantName := envelope.Counterparty.NormalizedName
	category := envelope.Counterparty.MerchantCategory

	if w.dbPool != nil {
		_, err := w.dbPool.Exec(ctx, `
			UPDATE fignode.staging_transactions
			SET predicted_vendor_name = $2,
			    predicted_account_name = $3,
			    confidence_score = $4,
			    ai_reasoning = $5,
			    merchant_name = $6,
			    category = $7,
			    moroccan_enrichment = $8,
			    status = 'ENRICHED',
			    updated_at = NOW()
			WHERE id = $1
		`, rowID, vendorName, accountName, score, aiReasoning, merchantName, category, envelopeJSON)
		return err
	}

	return nil
}

func (w *MoroccanEnrichmentWorker) publishCompletionProof(
	payload *MoroccanEnrichmentPayload,
	reqEnv *core.Envelope,
	total, enriched int,
	elapsed time.Duration,
	replySubject string,
) error {
	result := MoroccanEnrichmentResult{
		SessionID:      payload.SessionID,
		RealmID:        payload.RealmID,
		Status:         "COMPLETED",
		TotalProcessed: total,
		EnrichedCount:  enriched,
		DurationMS:     float64(elapsed.Microseconds()) / 1000.0,
	}
	resultBytes, _ := json.Marshal(result)

	// 1. Publish to reply topic if requested
	if replySubject != "" && w.nc != nil {
		_ = w.nc.Publish(replySubject, resultBytes)
	}

	// 2. Publish TAP Orchestrator proof
	cid := reqEnv.ConversationID
	if cid != "" && w.nc != nil {
		proof := core.Proof{
			Type:      core.ProofAPI,
			Timestamp: time.Now().Unix(),
			Data:      json.RawMessage(resultBytes),
		}
		replyEnv, envErr := core.NewEnvelope(
			uuid.New().String(),
			"worker.pcm.moroccan_enrichment",
			workflows.OrchestratorInbox,
			cid,
			core.INFORM,
			proof,
		)
		if envErr == nil {
			replyEnvBytes, _ := json.Marshal(replyEnv)
			_ = w.nc.Publish(workflows.OrchestratorInbox, replyEnvBytes)
			w.logger.Info("MoroccanEnrichmentWorker: sent completion proof to TAP Orchestrator", "cid", cid)
		}
	}

	return nil
}
