# Generated by Django 6.0.1 on 2026-01-18 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realm_id', models.CharField(help_text='QuickBooks Realm ID (Company ID)', max_length=255, unique=True)),
                ('_access_token', models.TextField(db_column='access_token', help_text='Encrypted Access Token')),
                ('_refresh_token', models.TextField(db_column='refresh_token', help_text='Encrypted Refresh Token')),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
