// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ase_vector.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingHydrationRows = `-- name: GetPendingHydrationRows :many
SELECT id, realm_id, namespace, source_type, raw_text, source_row_id
FROM toro_core.ase_vector_memory
WHERE embedding IS NULL
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingHydrationRowsRow struct {
	ID          pgtype.UUID
	RealmID     string
	Namespace   string
	SourceType  string
	RawText     string
	SourceRowID pgtype.UUID
}

// Returns rows that have no embedding yet, ordered oldest-first.
// Used by the VectorHydrator to find work each tick.
func (q *Queries) GetPendingHydrationRows(ctx context.Context, limit int32) ([]GetPendingHydrationRowsRow, error) {
	rows, err := q.db.Query(ctx, getPendingHydrationRows, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingHydrationRowsRow
	for rows.Next() {
		var i GetPendingHydrationRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.RealmID,
			&i.Namespace,
			&i.SourceType,
			&i.RawText,
			&i.SourceRowID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPendingVectorRow = `-- name: InsertPendingVectorRow :exec
INSERT INTO toro_core.ase_vector_memory (realm_id, namespace, source_type, raw_text, source_row_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (realm_id, namespace, source_type, source_row_id) DO NOTHING
`

type InsertPendingVectorRowParams struct {
	RealmID     string
	Namespace   string
	SourceType  string
	RawText     string
	SourceRowID pgtype.UUID
	Metadata    []byte
}

// Registers a new source row for future hydration (embedding = NULL).
// The VectorHydrator will pick this up on its next tick.
func (q *Queries) InsertPendingVectorRow(ctx context.Context, arg InsertPendingVectorRowParams) error {
	_, err := q.db.Exec(ctx, insertPendingVectorRow,
		arg.RealmID,
		arg.Namespace,
		arg.SourceType,
		arg.RawText,
		arg.SourceRowID,
		arg.Metadata,
	)
	return err
}
