// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachables.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttachableByERPID = `-- name: GetAttachableByERPID :one
SELECT id, realm_id, erp_id, file_name, content_type, size, note, attachable_refs, sync_token, erp_created_time, erp_updated_time, deleted_at, created_at, updated_at FROM shadow_erp.attachables
WHERE realm_id = $1 AND erp_id = $2 AND deleted_at IS NULL
`

type GetAttachableByERPIDParams struct {
	RealmID string
	ErpID   string
}

func (q *Queries) GetAttachableByERPID(ctx context.Context, arg GetAttachableByERPIDParams) (ShadowErpAttachable, error) {
	row := q.db.QueryRow(ctx, getAttachableByERPID, arg.RealmID, arg.ErpID)
	var i ShadowErpAttachable
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.ErpID,
		&i.FileName,
		&i.ContentType,
		&i.Size,
		&i.Note,
		&i.AttachableRefs,
		&i.SyncToken,
		&i.ErpCreatedTime,
		&i.ErpUpdatedTime,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAttachable = `-- name: SoftDeleteAttachable :exec

UPDATE shadow_erp.attachables
SET deleted_at = $1, updated_at = NOW()
WHERE realm_id = $2 AND erp_id = $3
`

type SoftDeleteAttachableParams struct {
	DeletedAt pgtype.Timestamptz
	RealmID   string
	ErpID     string
}

// restore if previously soft-deleted
func (q *Queries) SoftDeleteAttachable(ctx context.Context, arg SoftDeleteAttachableParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttachable, arg.DeletedAt, arg.RealmID, arg.ErpID)
	return err
}

const upsertAttachable = `-- name: UpsertAttachable :exec
INSERT INTO shadow_erp.attachables (
    realm_id,
    erp_id,
    file_name,
    content_type,
    size,
    note,
    attachable_refs,
    sync_token,
    erp_created_time,
    erp_updated_time
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (realm_id, erp_id) DO UPDATE SET
    file_name = EXCLUDED.file_name,
    content_type = EXCLUDED.content_type,
    size = EXCLUDED.size,
    note = EXCLUDED.note,
    attachable_refs = EXCLUDED.attachable_refs,
    sync_token = EXCLUDED.sync_token,
    erp_created_time = EXCLUDED.erp_created_time,
    erp_updated_time = EXCLUDED.erp_updated_time,
    updated_at = NOW(),
    deleted_at = NULL
`

type UpsertAttachableParams struct {
	RealmID        string
	ErpID          string
	FileName       pgtype.Text
	ContentType    pgtype.Text
	Size           pgtype.Numeric
	Note           pgtype.Text
	AttachableRefs []byte
	SyncToken      pgtype.Text
	ErpCreatedTime pgtype.Timestamptz
	ErpUpdatedTime pgtype.Timestamptz
}

func (q *Queries) UpsertAttachable(ctx context.Context, arg UpsertAttachableParams) error {
	_, err := q.db.Exec(ctx, upsertAttachable,
		arg.RealmID,
		arg.ErpID,
		arg.FileName,
		arg.ContentType,
		arg.Size,
		arg.Note,
		arg.AttachableRefs,
		arg.SyncToken,
		arg.ErpCreatedTime,
		arg.ErpUpdatedTime,
	)
	return err
}
