// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attribution.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListSubscriber = `-- name: AddListSubscriber :one
INSERT INTO marketing.list_subscribers (list_id, prospect_id, status)
VALUES ($1, $2, 'active')
ON CONFLICT (list_id, prospect_id) DO UPDATE SET status = 'active', created_at = CURRENT_TIMESTAMP
RETURNING list_id, prospect_id, status, created_at
`

type AddListSubscriberParams struct {
	ListID     pgtype.UUID
	ProspectID pgtype.UUID
}

func (q *Queries) AddListSubscriber(ctx context.Context, arg AddListSubscriberParams) (MarketingListSubscriber, error) {
	row := q.db.QueryRow(ctx, addListSubscriber, arg.ListID, arg.ProspectID)
	var i MarketingListSubscriber
	err := row.Scan(
		&i.ListID,
		&i.ProspectID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAttribution = `-- name: CreateAttribution :one
INSERT INTO marketing.attributions (conversion_id, email_log_id, campaign_id, list_id, attributed_value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conversion_id, email_log_id, campaign_id, list_id, attributed_value, created_at
`

type CreateAttributionParams struct {
	ConversionID    pgtype.UUID
	EmailLogID      pgtype.UUID
	CampaignID      pgtype.UUID
	ListID          pgtype.UUID
	AttributedValue int32
}

func (q *Queries) CreateAttribution(ctx context.Context, arg CreateAttributionParams) (MarketingAttribution, error) {
	row := q.db.QueryRow(ctx, createAttribution,
		arg.ConversionID,
		arg.EmailLogID,
		arg.CampaignID,
		arg.ListID,
		arg.AttributedValue,
	)
	var i MarketingAttribution
	err := row.Scan(
		&i.ID,
		&i.ConversionID,
		&i.EmailLogID,
		&i.CampaignID,
		&i.ListID,
		&i.AttributedValue,
		&i.CreatedAt,
	)
	return i, err
}

const createConversion = `-- name: CreateConversion :one
INSERT INTO marketing.conversions (tenant_id, prospect_id, customer_email, conversion_value, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, prospect_id, customer_email, conversion_value, source, created_at
`

type CreateConversionParams struct {
	TenantID        pgtype.UUID
	ProspectID      pgtype.UUID
	CustomerEmail   string
	ConversionValue int32
	Source          pgtype.Text
}

func (q *Queries) CreateConversion(ctx context.Context, arg CreateConversionParams) (MarketingConversion, error) {
	row := q.db.QueryRow(ctx, createConversion,
		arg.TenantID,
		arg.ProspectID,
		arg.CustomerEmail,
		arg.ConversionValue,
		arg.Source,
	)
	var i MarketingConversion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProspectID,
		&i.CustomerEmail,
		&i.ConversionValue,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createMarketingList = `-- name: CreateMarketingList :one
INSERT INTO marketing.lists (tenant_id, name)
VALUES ($1, $2)
RETURNING id, tenant_id, name, created_at
`

type CreateMarketingListParams struct {
	TenantID pgtype.UUID
	Name     string
}

func (q *Queries) CreateMarketingList(ctx context.Context, arg CreateMarketingListParams) (MarketingList, error) {
	row := q.db.QueryRow(ctx, createMarketingList, arg.TenantID, arg.Name)
	var i MarketingList
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const findLastTouch = `-- name: FindLastTouch :one
SELECT id, prospect_id, campaign_id, nats_msg_id, event_type, metadata, created_at, list_id, user_agent, ip_address, is_human
FROM marketing.email_logs
WHERE prospect_id = $1
  AND is_human = true
  AND event_type IN ('opened', 'clicked')
  AND created_at >= NOW() - INTERVAL '1 day' * $2::int
ORDER BY created_at DESC
LIMIT 1
`

type FindLastTouchParams struct {
	ProspectID pgtype.UUID
	WindowDays int32
}

func (q *Queries) FindLastTouch(ctx context.Context, arg FindLastTouchParams) (MarketingEmailLog, error) {
	row := q.db.QueryRow(ctx, findLastTouch, arg.ProspectID, arg.WindowDays)
	var i MarketingEmailLog
	err := row.Scan(
		&i.ID,
		&i.ProspectID,
		&i.CampaignID,
		&i.NatsMsgID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
		&i.ListID,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsHuman,
	)
	return i, err
}

const getCampaignRevenueMetrics = `-- name: GetCampaignRevenueMetrics :many
SELECT
    campaign_id,
    COUNT(id) AS total_conversions,
    SUM(attributed_value)::bigint AS total_revenue
FROM marketing.attributions
WHERE campaign_id = $1
GROUP BY campaign_id
`

type GetCampaignRevenueMetricsRow struct {
	CampaignID       pgtype.UUID
	TotalConversions int64
	TotalRevenue     int64
}

func (q *Queries) GetCampaignRevenueMetrics(ctx context.Context, campaignID pgtype.UUID) ([]GetCampaignRevenueMetricsRow, error) {
	rows, err := q.db.Query(ctx, getCampaignRevenueMetrics, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignRevenueMetricsRow
	for rows.Next() {
		var i GetCampaignRevenueMetricsRow
		if err := rows.Scan(&i.CampaignID, &i.TotalConversions, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListRevenueMetrics = `-- name: GetListRevenueMetrics :many
SELECT
    list_id,
    COUNT(id) AS total_conversions,
    SUM(attributed_value)::bigint AS total_revenue
FROM marketing.attributions
WHERE list_id = $1
GROUP BY list_id
`

type GetListRevenueMetricsRow struct {
	ListID           pgtype.UUID
	TotalConversions int64
	TotalRevenue     int64
}

func (q *Queries) GetListRevenueMetrics(ctx context.Context, listID pgtype.UUID) ([]GetListRevenueMetricsRow, error) {
	rows, err := q.db.Query(ctx, getListRevenueMetrics, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListRevenueMetricsRow
	for rows.Next() {
		var i GetListRevenueMetricsRow
		if err := rows.Scan(&i.ListID, &i.TotalConversions, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProspectIDByEmail = `-- name: GetProspectIDByEmail :one
SELECT id
FROM marketing.prospects
WHERE email = $1 AND tenant_id = $2
LIMIT 1
`

type GetProspectIDByEmailParams struct {
	Email    string
	TenantID pgtype.UUID
}

func (q *Queries) GetProspectIDByEmail(ctx context.Context, arg GetProspectIDByEmailParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getProspectIDByEmail, arg.Email, arg.TenantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT tenant_id, attribution_window_days, created_at, updated_at FROM marketing.tenant_settings
WHERE tenant_id = $1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID pgtype.UUID) (MarketingTenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, tenantID)
	var i MarketingTenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.AttributionWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unsubscribeList = `-- name: UnsubscribeList :exec
UPDATE marketing.list_subscribers
SET status = 'unsubscribed'
WHERE list_id = $1 AND prospect_id = $2
`

type UnsubscribeListParams struct {
	ListID     pgtype.UUID
	ProspectID pgtype.UUID
}

func (q *Queries) UnsubscribeList(ctx context.Context, arg UnsubscribeListParams) error {
	_, err := q.db.Exec(ctx, unsubscribeList, arg.ListID, arg.ProspectID)
	return err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO marketing.tenant_settings (tenant_id, attribution_window_days)
VALUES ($1, $2)
ON CONFLICT (tenant_id) DO UPDATE SET
    attribution_window_days = EXCLUDED.attribution_window_days,
    updated_at = CURRENT_TIMESTAMP
RETURNING tenant_id, attribution_window_days, created_at, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID              pgtype.UUID
	AttributionWindowDays int32
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (MarketingTenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings, arg.TenantID, arg.AttributionWindowDays)
	var i MarketingTenantSetting
	err := row.Scan(
		&i.TenantID,
		&i.AttributionWindowDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
