// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleanup.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCleanupRow = `-- name: ApproveCleanupRow :one
WITH updated AS (
    UPDATE fignode.staging_transactions
    SET status = 'APPROVED', updated_at = NOW()
    WHERE fignode.staging_transactions.id = $1
    RETURNING id, session_id, row_index, source_type, raw_description, raw_amount, raw_date, parsed_date, cash_direction, iso_currency_code, transaction_hash, erp_transaction_id, transaction_id, pending_transaction_id, merchant_name, logo_url, category, is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name, confidence_score, ai_reasoning, human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id, duplicate_of, is_recurring, split_suggestion, status, error_message, reconciled_at, reconciled_by, rule_group_id, macro_class, account_type, synced_at, ase_execution_trace, created_at, updated_at, moroccan_enrichment, stage2_proposals, stage2_current_hash, stage2_outcome, stage2_review_status, stage2_approved_payload, stage2_approved_hash, stage2_reviewed_by, stage2_reviewed_at
)
SELECT updated.id, updated.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, updated.source_type, updated.raw_description, updated.raw_amount, updated.raw_date, updated.parsed_date,
        updated.predicted_vendor_id, updated.predicted_customer_id, updated.predicted_account_id,
        updated.confidence_score, updated.ai_reasoning, updated.duplicate_of, updated.is_recurring, updated.split_suggestion,
        updated.override_vendor_id, updated.override_customer_id, updated.override_account_id, updated.status, updated.erp_transaction_id,
        updated.created_at, updated.updated_at
FROM updated
LEFT JOIN fignode.staging_sessions ss ON ss.id = updated.session_id
`

type ApproveCleanupRowRow struct {
	ID                  pgtype.UUID
	SessionID           pgtype.UUID
	RealmID             pgtype.Text
	BankAccountID       pgtype.UUID
	OutflowIs           pgtype.Text
	SourceType          string
	RawDescription      pgtype.Text
	RawAmount           string
	RawDate             pgtype.Text
	ParsedDate          pgtype.Date
	PredictedVendorID   pgtype.UUID
	PredictedCustomerID pgtype.UUID
	PredictedAccountID  pgtype.UUID
	ConfidenceScore     pgtype.Numeric
	AiReasoning         pgtype.Text
	DuplicateOf         pgtype.UUID
	IsRecurring         bool
	SplitSuggestion     []byte
	OverrideVendorID    pgtype.UUID
	OverrideCustomerID  pgtype.UUID
	OverrideAccountID   pgtype.UUID
	Status              string
	ErpTransactionID    pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ApproveCleanupRow(ctx context.Context, id pgtype.UUID) (ApproveCleanupRowRow, error) {
	row := q.db.QueryRow(ctx, approveCleanupRow, id)
	var i ApproveCleanupRowRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RealmID,
		&i.BankAccountID,
		&i.OutflowIs,
		&i.SourceType,
		&i.RawDescription,
		&i.RawAmount,
		&i.RawDate,
		&i.ParsedDate,
		&i.PredictedVendorID,
		&i.PredictedCustomerID,
		&i.PredictedAccountID,
		&i.ConfidenceScore,
		&i.AiReasoning,
		&i.DuplicateOf,
		&i.IsRecurring,
		&i.SplitSuggestion,
		&i.OverrideVendorID,
		&i.OverrideCustomerID,
		&i.OverrideAccountID,
		&i.Status,
		&i.ErpTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bulkApproveByVendor = `-- name: BulkApproveByVendor :many
UPDATE fignode.staging_transactions
SET status = 'APPROVED', updated_at = NOW()
WHERE session_id = $1
  AND predicted_vendor_id = $2
  AND status = 'ENRICHED'
RETURNING id
`

type BulkApproveByVendorParams struct {
	SessionID         pgtype.UUID
	PredictedVendorID pgtype.UUID
}

func (q *Queries) BulkApproveByVendor(ctx context.Context, arg BulkApproveByVendorParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, bulkApproveByVendor, arg.SessionID, arg.PredictedVendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSessionRows = `-- name: CountSessionRows :one
SELECT COUNT(*)
FROM fignode.staging_transactions cs
WHERE cs.session_id = $1
  AND ($2::TEXT IS NULL OR cs.status = $2::TEXT)
`

type CountSessionRowsParams struct {
	SessionID pgtype.UUID
	Status    pgtype.Text
}

func (q *Queries) CountSessionRows(ctx context.Context, arg CountSessionRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionRows, arg.SessionID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCleanupSession = `-- name: CreateCleanupSession :one

INSERT INTO fignode.staging_sessions (realm_id, bank_account_id, kind, created_by, file_name, row_count, status, outflow_is)
VALUES ($5, $6, 'CSV', $1, $2, $3, 'PENDING', $4)
RETURNING id, realm_id, bank_account_id, kind, created_by, file_name, row_count, status, outflow_is, is_ambiguous, ambiguity_reason, created_at, updated_at
`

type CreateCleanupSessionParams struct {
	CreatedBy     pgtype.UUID
	FileName      pgtype.Text
	RowCount      int32
	OutflowIs     string
	RealmID       pgtype.Text
	BankAccountID pgtype.UUID
}

type CreateCleanupSessionRow struct {
	ID              pgtype.UUID
	RealmID         pgtype.Text
	BankAccountID   pgtype.UUID
	Kind            string
	CreatedBy       pgtype.UUID
	FileName        pgtype.Text
	RowCount        int32
	Status          string
	OutflowIs       string
	IsAmbiguous     bool
	AmbiguityReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// =========================================================================
// Cleanup Mode Queries (now stored in fignode schema)
// =========================================================================
func (q *Queries) CreateCleanupSession(ctx context.Context, arg CreateCleanupSessionParams) (CreateCleanupSessionRow, error) {
	row := q.db.QueryRow(ctx, createCleanupSession,
		arg.CreatedBy,
		arg.FileName,
		arg.RowCount,
		arg.OutflowIs,
		arg.RealmID,
		arg.BankAccountID,
	)
	var i CreateCleanupSessionRow
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.BankAccountID,
		&i.Kind,
		&i.CreatedBy,
		&i.FileName,
		&i.RowCount,
		&i.Status,
		&i.OutflowIs,
		&i.IsAmbiguous,
		&i.AmbiguityReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMasterMerchant = `-- name: CreateMasterMerchant :one
INSERT INTO fignode.master_merchants (
    normalized_name, primary_domain, logo_url, mcc, naics, default_macro_class, default_qbo_category, irs_receipt_threshold
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, normalized_name, primary_domain, logo_url, mcc, naics, default_macro_class, default_qbo_category, irs_receipt_threshold
`

type CreateMasterMerchantParams struct {
	NormalizedName      string
	PrimaryDomain       string
	LogoUrl             string
	Mcc                 int32
	Naics               string
	DefaultMacroClass   string
	DefaultQboCategory  string
	IrsReceiptThreshold pgtype.Numeric
}

func (q *Queries) CreateMasterMerchant(ctx context.Context, arg CreateMasterMerchantParams) (FignodeMasterMerchant, error) {
	row := q.db.QueryRow(ctx, createMasterMerchant,
		arg.NormalizedName,
		arg.PrimaryDomain,
		arg.LogoUrl,
		arg.Mcc,
		arg.Naics,
		arg.DefaultMacroClass,
		arg.DefaultQboCategory,
		arg.IrsReceiptThreshold,
	)
	var i FignodeMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.Mcc,
		&i.Naics,
		&i.DefaultMacroClass,
		&i.DefaultQboCategory,
		&i.IrsReceiptThreshold,
	)
	return i, err
}

const createMasterPattern = `-- name: CreateMasterPattern :one
INSERT INTO fignode.master_patterns (
    cleaned_stem, master_merchant_id, is_intermediary
) VALUES (
    $1, $2, $3
) RETURNING id, cleaned_stem, master_merchant_id, is_intermediary
`

type CreateMasterPatternParams struct {
	CleanedStem      string
	MasterMerchantID int64
	IsIntermediary   bool
}

func (q *Queries) CreateMasterPattern(ctx context.Context, arg CreateMasterPatternParams) (FignodeMasterPattern, error) {
	row := q.db.QueryRow(ctx, createMasterPattern, arg.CleanedStem, arg.MasterMerchantID, arg.IsIntermediary)
	var i FignodeMasterPattern
	err := row.Scan(
		&i.ID,
		&i.CleanedStem,
		&i.MasterMerchantID,
		&i.IsIntermediary,
	)
	return i, err
}

const getAiCorrectionByRawInput = `-- name: GetAiCorrectionByRawInput :one
SELECT user_correction, correction_type
FROM shadow_erp.ai_corrections
WHERE realm_id = $1
  AND raw_input  = $2
  AND correction_type = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetAiCorrectionByRawInputParams struct {
	RealmID        string
	RawInput       string
	CorrectionType string
}

type GetAiCorrectionByRawInputRow struct {
	UserCorrection string
	CorrectionType string
}

func (q *Queries) GetAiCorrectionByRawInput(ctx context.Context, arg GetAiCorrectionByRawInputParams) (GetAiCorrectionByRawInputRow, error) {
	row := q.db.QueryRow(ctx, getAiCorrectionByRawInput, arg.RealmID, arg.RawInput, arg.CorrectionType)
	var i GetAiCorrectionByRawInputRow
	err := row.Scan(&i.UserCorrection, &i.CorrectionType)
	return i, err
}

const getApprovedRows = `-- name: GetApprovedRows :many
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning, cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id, cs.status, cs.erp_transaction_id,
       cs.created_at, cs.updated_at
FROM fignode.staging_transactions cs
LEFT JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
WHERE cs.session_id = $1 AND cs.status = 'APPROVED'
ORDER BY cs.parsed_date ASC NULLS LAST, cs.id ASC
`

type GetApprovedRowsRow struct {
	ID                  pgtype.UUID
	SessionID           pgtype.UUID
	RealmID             pgtype.Text
	BankAccountID       pgtype.UUID
	OutflowIs           pgtype.Text
	SourceType          string
	RawDescription      pgtype.Text
	RawAmount           string
	RawDate             pgtype.Text
	ParsedDate          pgtype.Date
	PredictedVendorID   pgtype.UUID
	PredictedCustomerID pgtype.UUID
	PredictedAccountID  pgtype.UUID
	ConfidenceScore     pgtype.Numeric
	AiReasoning         pgtype.Text
	DuplicateOf         pgtype.UUID
	IsRecurring         bool
	SplitSuggestion     []byte
	OverrideVendorID    pgtype.UUID
	OverrideCustomerID  pgtype.UUID
	OverrideAccountID   pgtype.UUID
	Status              string
	ErpTransactionID    pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetApprovedRows(ctx context.Context, sessionID pgtype.UUID) ([]GetApprovedRowsRow, error) {
	rows, err := q.db.Query(ctx, getApprovedRows, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovedRowsRow
	for rows.Next() {
		var i GetApprovedRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.BankAccountID,
			&i.OutflowIs,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.ParsedDate,
			&i.PredictedVendorID,
			&i.PredictedCustomerID,
			&i.PredictedAccountID,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.Status,
			&i.ErpTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCleanupRow = `-- name: GetCleanupRow :one
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning, cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id,
       cs.merchant_name, cs.category,
       cs.status, cs.erp_transaction_id,
       cs.created_at, cs.updated_at
FROM fignode.staging_transactions cs
LEFT JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
WHERE cs.id = $1
`

type GetCleanupRowRow struct {
	ID                  pgtype.UUID
	SessionID           pgtype.UUID
	RealmID             pgtype.Text
	BankAccountID       pgtype.UUID
	OutflowIs           pgtype.Text
	SourceType          string
	RawDescription      pgtype.Text
	RawAmount           string
	RawDate             pgtype.Text
	ParsedDate          pgtype.Date
	PredictedVendorID   pgtype.UUID
	PredictedCustomerID pgtype.UUID
	PredictedAccountID  pgtype.UUID
	ConfidenceScore     pgtype.Numeric
	AiReasoning         pgtype.Text
	DuplicateOf         pgtype.UUID
	IsRecurring         bool
	SplitSuggestion     []byte
	OverrideVendorID    pgtype.UUID
	OverrideCustomerID  pgtype.UUID
	OverrideAccountID   pgtype.UUID
	MerchantName        pgtype.Text
	Category            pgtype.Text
	Status              string
	ErpTransactionID    pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetCleanupRow(ctx context.Context, id pgtype.UUID) (GetCleanupRowRow, error) {
	row := q.db.QueryRow(ctx, getCleanupRow, id)
	var i GetCleanupRowRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RealmID,
		&i.BankAccountID,
		&i.OutflowIs,
		&i.SourceType,
		&i.RawDescription,
		&i.RawAmount,
		&i.RawDate,
		&i.ParsedDate,
		&i.PredictedVendorID,
		&i.PredictedCustomerID,
		&i.PredictedAccountID,
		&i.ConfidenceScore,
		&i.AiReasoning,
		&i.DuplicateOf,
		&i.IsRecurring,
		&i.SplitSuggestion,
		&i.OverrideVendorID,
		&i.OverrideCustomerID,
		&i.OverrideAccountID,
		&i.MerchantName,
		&i.Category,
		&i.Status,
		&i.ErpTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCleanupSession = `-- name: GetCleanupSession :one
SELECT id, realm_id, bank_account_id, kind, created_by, file_name, row_count, status, outflow_is, is_ambiguous, ambiguity_reason, created_at, updated_at
FROM fignode.staging_sessions
WHERE id = $1
`

type GetCleanupSessionRow struct {
	ID              pgtype.UUID
	RealmID         pgtype.Text
	BankAccountID   pgtype.UUID
	Kind            string
	CreatedBy       pgtype.UUID
	FileName        pgtype.Text
	RowCount        int32
	Status          string
	OutflowIs       string
	IsAmbiguous     bool
	AmbiguityReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetCleanupSession(ctx context.Context, id pgtype.UUID) (GetCleanupSessionRow, error) {
	row := q.db.QueryRow(ctx, getCleanupSession, id)
	var i GetCleanupSessionRow
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.BankAccountID,
		&i.Kind,
		&i.CreatedBy,
		&i.FileName,
		&i.RowCount,
		&i.Status,
		&i.OutflowIs,
		&i.IsAmbiguous,
		&i.AmbiguityReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterMerchantByExactPattern = `-- name: GetMasterMerchantByExactPattern :one
SELECT mm.id, mm.normalized_name, mm.primary_domain, mm.logo_url, mm.mcc, mm.naics, mm.default_macro_class, mm.default_qbo_category, mm.irs_receipt_threshold FROM fignode.master_patterns mp
JOIN fignode.master_merchants mm ON mm.id = mp.master_merchant_id
WHERE mp.cleaned_stem = $1 LIMIT 1
`

func (q *Queries) GetMasterMerchantByExactPattern(ctx context.Context, cleanedStem string) (FignodeMasterMerchant, error) {
	row := q.db.QueryRow(ctx, getMasterMerchantByExactPattern, cleanedStem)
	var i FignodeMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.Mcc,
		&i.Naics,
		&i.DefaultMacroClass,
		&i.DefaultQboCategory,
		&i.IrsReceiptThreshold,
	)
	return i, err
}

const getMasterMerchantBySubstringPattern = `-- name: GetMasterMerchantBySubstringPattern :one
SELECT mm.id, mm.normalized_name, mm.primary_domain, mm.logo_url, mm.mcc, mm.naics, mm.default_macro_class, mm.default_qbo_category, mm.irs_receipt_threshold FROM fignode.master_patterns mp
JOIN fignode.master_merchants mm ON mm.id = mp.master_merchant_id
WHERE $1 LIKE CONCAT('%', mp.cleaned_stem, '%') LIMIT 1
`

func (q *Queries) GetMasterMerchantBySubstringPattern(ctx context.Context, cleanedStem string) (FignodeMasterMerchant, error) {
	row := q.db.QueryRow(ctx, getMasterMerchantBySubstringPattern, cleanedStem)
	var i FignodeMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.Mcc,
		&i.Naics,
		&i.DefaultMacroClass,
		&i.DefaultQboCategory,
		&i.IrsReceiptThreshold,
	)
	return i, err
}

const getMasterMerchantByTrigramSimilarity = `-- name: GetMasterMerchantByTrigramSimilarity :one
SELECT mm.id, mm.normalized_name, mm.primary_domain, mm.logo_url, mm.mcc, mm.naics, mm.default_macro_class, mm.default_qbo_category, mm.irs_receipt_threshold FROM fignode.master_patterns mp
JOIN fignode.master_merchants mm ON mm.id = mp.master_merchant_id
WHERE mp.cleaned_stem % $1 AND similarity(mp.cleaned_stem, $1) > 0.75
ORDER BY similarity(mp.cleaned_stem, $1) DESC LIMIT 1
`

func (q *Queries) GetMasterMerchantByTrigramSimilarity(ctx context.Context, cleanedStem string) (FignodeMasterMerchant, error) {
	row := q.db.QueryRow(ctx, getMasterMerchantByTrigramSimilarity, cleanedStem)
	var i FignodeMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.Mcc,
		&i.Naics,
		&i.DefaultMacroClass,
		&i.DefaultQboCategory,
		&i.IrsReceiptThreshold,
	)
	return i, err
}

const getOrCreateSystemSession = `-- name: GetOrCreateSystemSession :one
INSERT INTO fignode.staging_sessions (realm_id, kind, status)
VALUES ($1, 'SYSTEM', 'ACTIVE')
ON CONFLICT (realm_id) WHERE kind = 'SYSTEM' AND realm_id IS NOT NULL
DO UPDATE SET updated_at = NOW()
RETURNING id
`

// Returns the SYSTEM session for a given realm, creating it if it does not exist.
// Used by non-CSV transaction stagers (rule engine, Plaid webhooks) to satisfy the
// session_id linkage now that realm_id has been removed from staging_transactions.
func (q *Queries) GetOrCreateSystemSession(ctx context.Context, realmID pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateSystemSession, realmID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPendingRealmRows = `-- name: GetPendingRealmRows :many
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning,
       cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id,
       cs.merchant_name, cs.category,
       cs.status, cs.erp_transaction_id, cs.created_at, cs.updated_at,
       COALESCE(v.display_name, cs.predicted_vendor_name, '') AS predicted_vendor_name,
       COALESCE(c.display_name, cs.predicted_customer_name, '') AS predicted_customer_name,
       a.name         AS predicted_account_name,
       a.account_type AS predicted_account_type,
       ov.display_name AS override_vendor_name,
       oc.display_name AS override_customer_name,
       oa.name         AS override_account_name
FROM fignode.staging_transactions cs
JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
LEFT JOIN shadow_erp.vendors  v  ON v.id  = cs.predicted_vendor_id
LEFT JOIN shadow_erp.customers c ON c.id  = cs.predicted_customer_id
LEFT JOIN shadow_erp.accounts a  ON a.id  = cs.predicted_account_id
LEFT JOIN shadow_erp.vendors  ov ON ov.id = cs.override_vendor_id
LEFT JOIN shadow_erp.customers oc ON oc.id = cs.override_customer_id
LEFT JOIN shadow_erp.accounts oa ON oa.id = cs.override_account_id
WHERE ss.realm_id = $1 AND cs.status = 'PENDING'
ORDER BY cs.parsed_date ASC NULLS LAST
LIMIT $2
`

type GetPendingRealmRowsParams struct {
	RealmID pgtype.Text
	Limit   int32
}

type GetPendingRealmRowsRow struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RealmID               pgtype.Text
	BankAccountID         pgtype.UUID
	OutflowIs             string
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	ParsedDate            pgtype.Date
	PredictedVendorID     pgtype.UUID
	PredictedCustomerID   pgtype.UUID
	PredictedAccountID    pgtype.UUID
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	MerchantName          pgtype.Text
	Category              pgtype.Text
	Status                string
	ErpTransactionID      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PredictedVendorName   string
	PredictedCustomerName string
	PredictedAccountName  pgtype.Text
	PredictedAccountType  pgtype.Text
	OverrideVendorName    pgtype.Text
	OverrideCustomerName  pgtype.Text
	OverrideAccountName   pgtype.Text
}

func (q *Queries) GetPendingRealmRows(ctx context.Context, arg GetPendingRealmRowsParams) ([]GetPendingRealmRowsRow, error) {
	rows, err := q.db.Query(ctx, getPendingRealmRows, arg.RealmID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingRealmRowsRow
	for rows.Next() {
		var i GetPendingRealmRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.BankAccountID,
			&i.OutflowIs,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.ParsedDate,
			&i.PredictedVendorID,
			&i.PredictedCustomerID,
			&i.PredictedAccountID,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.MerchantName,
			&i.Category,
			&i.Status,
			&i.ErpTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PredictedVendorName,
			&i.PredictedCustomerName,
			&i.PredictedAccountName,
			&i.PredictedAccountType,
			&i.OverrideVendorName,
			&i.OverrideCustomerName,
			&i.OverrideAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSessionRows = `-- name: GetPendingSessionRows :many
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning,
       cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id,
       cs.merchant_name, cs.category,
       cs.status, cs.erp_transaction_id, cs.created_at, cs.updated_at,
       COALESCE(v.display_name, cs.predicted_vendor_name, '') AS predicted_vendor_name,
       COALESCE(c.display_name, cs.predicted_customer_name, '') AS predicted_customer_name,
       a.name         AS predicted_account_name,
       a.account_type AS predicted_account_type,
       ov.display_name AS override_vendor_name,
       oc.display_name AS override_customer_name,
       oa.name         AS override_account_name
FROM fignode.staging_transactions cs
LEFT JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
LEFT JOIN shadow_erp.vendors  v  ON v.id  = cs.predicted_vendor_id
LEFT JOIN shadow_erp.customers c ON c.id  = cs.predicted_customer_id
LEFT JOIN shadow_erp.accounts a  ON a.id  = cs.predicted_account_id
LEFT JOIN shadow_erp.vendors  ov ON ov.id = cs.override_vendor_id
LEFT JOIN shadow_erp.customers oc ON oc.id = cs.override_customer_id
LEFT JOIN shadow_erp.accounts oa ON oa.id = cs.override_account_id
WHERE cs.session_id = $1 AND cs.status = 'PENDING'
ORDER BY cs.parsed_date ASC NULLS LAST, cs.id ASC
`

type GetPendingSessionRowsRow struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RealmID               pgtype.Text
	BankAccountID         pgtype.UUID
	OutflowIs             pgtype.Text
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	ParsedDate            pgtype.Date
	PredictedVendorID     pgtype.UUID
	PredictedCustomerID   pgtype.UUID
	PredictedAccountID    pgtype.UUID
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	MerchantName          pgtype.Text
	Category              pgtype.Text
	Status                string
	ErpTransactionID      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PredictedVendorName   string
	PredictedCustomerName string
	PredictedAccountName  pgtype.Text
	PredictedAccountType  pgtype.Text
	OverrideVendorName    pgtype.Text
	OverrideCustomerName  pgtype.Text
	OverrideAccountName   pgtype.Text
}

func (q *Queries) GetPendingSessionRows(ctx context.Context, sessionID pgtype.UUID) ([]GetPendingSessionRowsRow, error) {
	rows, err := q.db.Query(ctx, getPendingSessionRows, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingSessionRowsRow
	for rows.Next() {
		var i GetPendingSessionRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.BankAccountID,
			&i.OutflowIs,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.ParsedDate,
			&i.PredictedVendorID,
			&i.PredictedCustomerID,
			&i.PredictedAccountID,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.MerchantName,
			&i.Category,
			&i.Status,
			&i.ErpTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PredictedVendorName,
			&i.PredictedCustomerName,
			&i.PredictedAccountName,
			&i.PredictedAccountType,
			&i.OverrideVendorName,
			&i.OverrideCustomerName,
			&i.OverrideAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPotentialTransfers = `-- name: GetPotentialTransfers :many
SELECT tx.id, tx.raw_amount, tx.parsed_date, ss.bank_account_id
FROM fignode.staging_transactions tx
JOIN fignode.staging_sessions ss ON ss.id = tx.session_id
WHERE ss.realm_id = $1
  AND ss.bank_account_id != $2
  AND tx.parsed_date IS NOT NULL
  AND ABS(EXTRACT(EPOCH FROM (tx.parsed_date::TIMESTAMP - $3::TIMESTAMP))) <= 172800
`

type GetPotentialTransfersParams struct {
	RealmID       pgtype.Text
	BankAccountID pgtype.UUID
	Column3       pgtype.Timestamp
}

type GetPotentialTransfersRow struct {
	ID            pgtype.UUID
	RawAmount     string
	ParsedDate    pgtype.Date
	BankAccountID pgtype.UUID
}

func (q *Queries) GetPotentialTransfers(ctx context.Context, arg GetPotentialTransfersParams) ([]GetPotentialTransfersRow, error) {
	rows, err := q.db.Query(ctx, getPotentialTransfers, arg.RealmID, arg.BankAccountID, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPotentialTransfersRow
	for rows.Next() {
		var i GetPotentialTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.RawAmount,
			&i.ParsedDate,
			&i.BankAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealmIDFromEntity = `-- name: GetRealmIDFromEntity :one
SELECT erp_tenant_id 
FROM toro_core.entities 
WHERE id = $1 AND erp_provider = 'qbo'
`

func (q *Queries) GetRealmIDFromEntity(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getRealmIDFromEntity, id)
	var erp_tenant_id pgtype.Text
	err := row.Scan(&erp_tenant_id)
	return erp_tenant_id, err
}

const getRealmIDFromSession = `-- name: GetRealmIDFromSession :one
SELECT realm_id 
FROM fignode.staging_sessions 
WHERE id = $1
`

func (q *Queries) GetRealmIDFromSession(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getRealmIDFromSession, id)
	var realm_id pgtype.Text
	err := row.Scan(&realm_id)
	return realm_id, err
}

const getSessionRows = `-- name: GetSessionRows :many
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning,
       cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id,
       cs.merchant_name, cs.category,
       cs.status, cs.erp_transaction_id, cs.created_at, cs.updated_at,
       COALESCE(v.display_name, cs.predicted_vendor_name, '') AS predicted_vendor_name,
       COALESCE(c.display_name, cs.predicted_customer_name, '') AS predicted_customer_name,
       a.name         AS predicted_account_name,
       a.account_type AS predicted_account_type,
       ov.display_name AS override_vendor_name,
       oc.display_name AS override_customer_name,
       oa.name         AS override_account_name
FROM fignode.staging_transactions cs
LEFT JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
LEFT JOIN shadow_erp.vendors  v  ON v.id  = cs.predicted_vendor_id
LEFT JOIN shadow_erp.customers c ON c.id  = cs.predicted_customer_id
LEFT JOIN shadow_erp.accounts a  ON a.id  = cs.predicted_account_id
LEFT JOIN shadow_erp.vendors  ov ON ov.id = cs.override_vendor_id
LEFT JOIN shadow_erp.customers oc ON oc.id = cs.override_customer_id
LEFT JOIN shadow_erp.accounts oa ON oa.id = cs.override_account_id
WHERE cs.session_id = $1
  AND ($2::TEXT IS NULL OR cs.status = $2::TEXT)
ORDER BY cs.parsed_date ASC NULLS LAST, cs.id ASC
`

type GetSessionRowsParams struct {
	SessionID pgtype.UUID
	Status    pgtype.Text
}

type GetSessionRowsRow struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RealmID               pgtype.Text
	BankAccountID         pgtype.UUID
	OutflowIs             pgtype.Text
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	ParsedDate            pgtype.Date
	PredictedVendorID     pgtype.UUID
	PredictedCustomerID   pgtype.UUID
	PredictedAccountID    pgtype.UUID
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	MerchantName          pgtype.Text
	Category              pgtype.Text
	Status                string
	ErpTransactionID      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PredictedVendorName   string
	PredictedCustomerName string
	PredictedAccountName  pgtype.Text
	PredictedAccountType  pgtype.Text
	OverrideVendorName    pgtype.Text
	OverrideCustomerName  pgtype.Text
	OverrideAccountName   pgtype.Text
}

func (q *Queries) GetSessionRows(ctx context.Context, arg GetSessionRowsParams) ([]GetSessionRowsRow, error) {
	rows, err := q.db.Query(ctx, getSessionRows, arg.SessionID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionRowsRow
	for rows.Next() {
		var i GetSessionRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.BankAccountID,
			&i.OutflowIs,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.ParsedDate,
			&i.PredictedVendorID,
			&i.PredictedCustomerID,
			&i.PredictedAccountID,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.MerchantName,
			&i.Category,
			&i.Status,
			&i.ErpTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PredictedVendorName,
			&i.PredictedCustomerName,
			&i.PredictedAccountName,
			&i.PredictedAccountType,
			&i.OverrideVendorName,
			&i.OverrideCustomerName,
			&i.OverrideAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionRowsPaginated = `-- name: GetSessionRowsPaginated :many
SELECT cs.id, cs.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, cs.source_type, cs.raw_description, cs.raw_amount, cs.raw_date, cs.parsed_date,
       cs.predicted_vendor_id, cs.predicted_customer_id, cs.predicted_account_id,
       cs.confidence_score, cs.ai_reasoning,
       cs.duplicate_of, cs.is_recurring, cs.split_suggestion,
       cs.override_vendor_id, cs.override_customer_id, cs.override_account_id,
       cs.merchant_name, cs.category,
       cs.status, cs.erp_transaction_id, cs.created_at, cs.updated_at,
       COALESCE(v.display_name, cs.predicted_vendor_name, '') AS predicted_vendor_name,
       COALESCE(c.display_name, cs.predicted_customer_name, '') AS predicted_customer_name,
       a.name         AS predicted_account_name,
       a.account_type AS predicted_account_type,
       ov.display_name AS override_vendor_name,
       oc.display_name AS override_customer_name,
       oa.name         AS override_account_name
FROM fignode.staging_transactions cs
LEFT JOIN fignode.staging_sessions ss ON ss.id = cs.session_id
LEFT JOIN shadow_erp.vendors  v  ON v.id  = cs.predicted_vendor_id
LEFT JOIN shadow_erp.customers c ON c.id  = cs.predicted_customer_id
LEFT JOIN shadow_erp.accounts a  ON a.id  = cs.predicted_account_id
LEFT JOIN shadow_erp.vendors  ov ON ov.id = cs.override_vendor_id
LEFT JOIN shadow_erp.customers oc ON oc.id = cs.override_customer_id
LEFT JOIN shadow_erp.accounts oa ON oa.id = cs.override_account_id
WHERE cs.session_id = $1
  AND ($4::TEXT IS NULL OR cs.status = $4::TEXT)
ORDER BY cs.parsed_date ASC NULLS LAST, cs.id ASC
LIMIT $2 OFFSET $3
`

type GetSessionRowsPaginatedParams struct {
	SessionID pgtype.UUID
	Limit     int32
	Offset    int32
	Status    pgtype.Text
}

type GetSessionRowsPaginatedRow struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RealmID               pgtype.Text
	BankAccountID         pgtype.UUID
	OutflowIs             pgtype.Text
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	ParsedDate            pgtype.Date
	PredictedVendorID     pgtype.UUID
	PredictedCustomerID   pgtype.UUID
	PredictedAccountID    pgtype.UUID
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	MerchantName          pgtype.Text
	Category              pgtype.Text
	Status                string
	ErpTransactionID      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	PredictedVendorName   string
	PredictedCustomerName string
	PredictedAccountName  pgtype.Text
	PredictedAccountType  pgtype.Text
	OverrideVendorName    pgtype.Text
	OverrideCustomerName  pgtype.Text
	OverrideAccountName   pgtype.Text
}

func (q *Queries) GetSessionRowsPaginated(ctx context.Context, arg GetSessionRowsPaginatedParams) ([]GetSessionRowsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getSessionRowsPaginated,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionRowsPaginatedRow
	for rows.Next() {
		var i GetSessionRowsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.BankAccountID,
			&i.OutflowIs,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.ParsedDate,
			&i.PredictedVendorID,
			&i.PredictedCustomerID,
			&i.PredictedAccountID,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.MerchantName,
			&i.Category,
			&i.Status,
			&i.ErpTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PredictedVendorName,
			&i.PredictedCustomerName,
			&i.PredictedAccountName,
			&i.PredictedAccountType,
			&i.OverrideVendorName,
			&i.OverrideCustomerName,
			&i.OverrideAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionSummary = `-- name: GetSessionSummary :one
SELECT
    COUNT(*)                                                               AS total_rows,
    COUNT(*) FILTER (WHERE status = 'APPROVED')                           AS approved_rows,
    COUNT(*) FILTER (WHERE status = 'REJECTED')                           AS rejected_rows,
    COUNT(*) FILTER (WHERE status = 'POSTED')                             AS posted_rows,
    COUNT(*) FILTER (WHERE duplicate_of IS NOT NULL)                      AS duplicate_rows,
    COUNT(*) FILTER (WHERE is_recurring)                                  AS recurring_rows,
    COUNT(*) FILTER (WHERE override_vendor_id IS NOT NULL
                        OR override_account_id IS NOT NULL)               AS overridden_rows,
    COALESCE(AVG(confidence_score) FILTER (WHERE confidence_score IS NOT NULL), 0) AS avg_confidence
FROM fignode.staging_transactions
WHERE session_id = $1
`

type GetSessionSummaryRow struct {
	TotalRows      int64
	ApprovedRows   int64
	RejectedRows   int64
	PostedRows     int64
	DuplicateRows  int64
	RecurringRows  int64
	OverriddenRows int64
	AvgConfidence  interface{}
}

func (q *Queries) GetSessionSummary(ctx context.Context, sessionID pgtype.UUID) (GetSessionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSessionSummary, sessionID)
	var i GetSessionSummaryRow
	err := row.Scan(
		&i.TotalRows,
		&i.ApprovedRows,
		&i.RejectedRows,
		&i.PostedRows,
		&i.DuplicateRows,
		&i.RecurringRows,
		&i.OverriddenRows,
		&i.AvgConfidence,
	)
	return i, err
}

const insertCleanupRow = `-- name: InsertCleanupRow :one
INSERT INTO fignode.staging_transactions (
    session_id, row_index, source_type, raw_description, raw_amount, raw_date, parsed_date, status,
    predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name,
    confidence_score, ai_reasoning, duplicate_of, is_recurring, split_suggestion,
    human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id,
    erp_transaction_id, error_message, transaction_id, pending_transaction_id,
    merchant_name, logo_url, category, is_pending
)
VALUES (
    $1, $6, $2, $3, $4, $5, $7, COALESCE($8, 'PENDING'),
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, COALESCE($18, FALSE), $19,
    $20, $21, $22, $23, $24, $25,
    $26, $27, $28, $29,
    $30, $31, $32, COALESCE($33, FALSE)
)
ON CONFLICT (session_id, row_index) WHERE session_id IS NOT NULL AND row_index IS NOT NULL
DO UPDATE SET
    raw_description = EXCLUDED.raw_description,
    raw_amount = EXCLUDED.raw_amount,
    raw_date = EXCLUDED.raw_date,
    updated_at = NOW()
RETURNING id
`

type InsertCleanupRowParams struct {
	SessionID             pgtype.UUID
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Text
	RowIndex              pgtype.Int4
	ParsedDate            pgtype.Date
	Status                interface{}
	PredictedVendorID     pgtype.UUID
	PredictedVendorName   pgtype.Text
	PredictedCustomerID   pgtype.UUID
	PredictedCustomerName pgtype.Text
	PredictedAccountID    pgtype.UUID
	PredictedAccountName  pgtype.Text
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           interface{}
	SplitSuggestion       []byte
	HumanAction           pgtype.Text
	SwipedBy              pgtype.UUID
	SwipedAt              pgtype.Timestamptz
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	ErpTransactionID      pgtype.Text
	ErrorMessage          pgtype.Text
	TransactionID         pgtype.Text
	PendingTransactionID  pgtype.Text
	MerchantName          pgtype.Text
	LogoUrl               pgtype.Text
	Category              pgtype.Text
	IsPending             interface{}
}

func (q *Queries) InsertCleanupRow(ctx context.Context, arg InsertCleanupRowParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCleanupRow,
		arg.SessionID,
		arg.SourceType,
		arg.RawDescription,
		arg.RawAmount,
		arg.RawDate,
		arg.RowIndex,
		arg.ParsedDate,
		arg.Status,
		arg.PredictedVendorID,
		arg.PredictedVendorName,
		arg.PredictedCustomerID,
		arg.PredictedCustomerName,
		arg.PredictedAccountID,
		arg.PredictedAccountName,
		arg.ConfidenceScore,
		arg.AiReasoning,
		arg.DuplicateOf,
		arg.IsRecurring,
		arg.SplitSuggestion,
		arg.HumanAction,
		arg.SwipedBy,
		arg.SwipedAt,
		arg.OverrideVendorID,
		arg.OverrideCustomerID,
		arg.OverrideAccountID,
		arg.ErpTransactionID,
		arg.ErrorMessage,
		arg.TransactionID,
		arg.PendingTransactionID,
		arg.MerchantName,
		arg.LogoUrl,
		arg.Category,
		arg.IsPending,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCleanupSessions = `-- name: ListCleanupSessions :many
SELECT id, realm_id, bank_account_id, kind, created_by, file_name, row_count, status, outflow_is, is_ambiguous, ambiguity_reason, created_at, updated_at
FROM fignode.staging_sessions
WHERE kind = 'CSV'
  AND ($1::TEXT IS NULL OR realm_id = $1::TEXT)
  AND ($2::UUID IS NULL OR created_by = $2::UUID)
ORDER BY created_at DESC
`

type ListCleanupSessionsParams struct {
	RealmID   pgtype.Text
	CreatedBy pgtype.UUID
}

type ListCleanupSessionsRow struct {
	ID              pgtype.UUID
	RealmID         pgtype.Text
	BankAccountID   pgtype.UUID
	Kind            string
	CreatedBy       pgtype.UUID
	FileName        pgtype.Text
	RowCount        int32
	Status          string
	OutflowIs       string
	IsAmbiguous     bool
	AmbiguityReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// Returns CSV sessions for a realm (when realm_id is provided) OR CSV sessions created by a user
// (when realm_id is NULL). Excludes SYSTEM/PLAID sessions which are not user-facing.
func (q *Queries) ListCleanupSessions(ctx context.Context, arg ListCleanupSessionsParams) ([]ListCleanupSessionsRow, error) {
	rows, err := q.db.Query(ctx, listCleanupSessions, arg.RealmID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCleanupSessionsRow
	for rows.Next() {
		var i ListCleanupSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RealmID,
			&i.BankAccountID,
			&i.Kind,
			&i.CreatedBy,
			&i.FileName,
			&i.RowCount,
			&i.Status,
			&i.OutflowIs,
			&i.IsAmbiguous,
			&i.AmbiguityReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCleanupSessionAmbiguous = `-- name: MarkCleanupSessionAmbiguous :exec
UPDATE fignode.staging_sessions
SET is_ambiguous = $2, ambiguity_reason = $3, updated_at = NOW()
WHERE id = $1
`

type MarkCleanupSessionAmbiguousParams struct {
	ID              pgtype.UUID
	IsAmbiguous     bool
	AmbiguityReason pgtype.Text
}

func (q *Queries) MarkCleanupSessionAmbiguous(ctx context.Context, arg MarkCleanupSessionAmbiguousParams) error {
	_, err := q.db.Exec(ctx, markCleanupSessionAmbiguous, arg.ID, arg.IsAmbiguous, arg.AmbiguityReason)
	return err
}

const markRowPosted = `-- name: MarkRowPosted :exec
UPDATE fignode.staging_transactions
SET status = 'POSTED', erp_transaction_id = $2, updated_at = NOW()
WHERE id = $1
`

type MarkRowPostedParams struct {
	ID               pgtype.UUID
	ErpTransactionID pgtype.Text
}

func (q *Queries) MarkRowPosted(ctx context.Context, arg MarkRowPostedParams) error {
	_, err := q.db.Exec(ctx, markRowPosted, arg.ID, arg.ErpTransactionID)
	return err
}

const overrideCleanupRow = `-- name: OverrideCleanupRow :one
WITH updated AS (
    UPDATE fignode.staging_transactions
    SET
        override_vendor_id   = $2,
        override_customer_id = $3,
        override_account_id  = $4,
        status               = 'APPROVED',
        updated_at           = NOW()
    WHERE fignode.staging_transactions.id = $1
    RETURNING id, session_id, row_index, source_type, raw_description, raw_amount, raw_date, parsed_date, cash_direction, iso_currency_code, transaction_hash, erp_transaction_id, transaction_id, pending_transaction_id, merchant_name, logo_url, category, is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name, confidence_score, ai_reasoning, human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id, duplicate_of, is_recurring, split_suggestion, status, error_message, reconciled_at, reconciled_by, rule_group_id, macro_class, account_type, synced_at, ase_execution_trace, created_at, updated_at, moroccan_enrichment, stage2_proposals, stage2_current_hash, stage2_outcome, stage2_review_status, stage2_approved_payload, stage2_approved_hash, stage2_reviewed_by, stage2_reviewed_at
)
SELECT updated.id, updated.session_id, ss.realm_id, ss.bank_account_id, ss.outflow_is, updated.source_type, updated.raw_description, updated.raw_amount, updated.raw_date, updated.parsed_date,
        updated.predicted_vendor_id, updated.predicted_customer_id, updated.predicted_account_id,
        updated.confidence_score, updated.ai_reasoning, updated.duplicate_of, updated.is_recurring, updated.split_suggestion,
        updated.override_vendor_id, updated.override_customer_id, updated.override_account_id, updated.status, updated.erp_transaction_id,
        updated.created_at, updated.updated_at
FROM updated
LEFT JOIN fignode.staging_sessions ss ON ss.id = updated.session_id
`

type OverrideCleanupRowParams struct {
	ID                 pgtype.UUID
	OverrideVendorID   pgtype.UUID
	OverrideCustomerID pgtype.UUID
	OverrideAccountID  pgtype.UUID
}

type OverrideCleanupRowRow struct {
	ID                  pgtype.UUID
	SessionID           pgtype.UUID
	RealmID             pgtype.Text
	BankAccountID       pgtype.UUID
	OutflowIs           pgtype.Text
	SourceType          string
	RawDescription      pgtype.Text
	RawAmount           string
	RawDate             pgtype.Text
	ParsedDate          pgtype.Date
	PredictedVendorID   pgtype.UUID
	PredictedCustomerID pgtype.UUID
	PredictedAccountID  pgtype.UUID
	ConfidenceScore     pgtype.Numeric
	AiReasoning         pgtype.Text
	DuplicateOf         pgtype.UUID
	IsRecurring         bool
	SplitSuggestion     []byte
	OverrideVendorID    pgtype.UUID
	OverrideCustomerID  pgtype.UUID
	OverrideAccountID   pgtype.UUID
	Status              string
	ErpTransactionID    pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) OverrideCleanupRow(ctx context.Context, arg OverrideCleanupRowParams) (OverrideCleanupRowRow, error) {
	row := q.db.QueryRow(ctx, overrideCleanupRow,
		arg.ID,
		arg.OverrideVendorID,
		arg.OverrideCustomerID,
		arg.OverrideAccountID,
	)
	var i OverrideCleanupRowRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RealmID,
		&i.BankAccountID,
		&i.OutflowIs,
		&i.SourceType,
		&i.RawDescription,
		&i.RawAmount,
		&i.RawDate,
		&i.ParsedDate,
		&i.PredictedVendorID,
		&i.PredictedCustomerID,
		&i.PredictedAccountID,
		&i.ConfidenceScore,
		&i.AiReasoning,
		&i.DuplicateOf,
		&i.IsRecurring,
		&i.SplitSuggestion,
		&i.OverrideVendorID,
		&i.OverrideCustomerID,
		&i.OverrideAccountID,
		&i.Status,
		&i.ErpTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectCleanupRow = `-- name: RejectCleanupRow :exec
UPDATE fignode.staging_transactions
SET status = 'REJECTED', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RejectCleanupRow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectCleanupRow, id)
	return err
}

const updateCleanupSessionBankAccount = `-- name: UpdateCleanupSessionBankAccount :exec
UPDATE fignode.staging_sessions
SET bank_account_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCleanupSessionBankAccountParams struct {
	ID            pgtype.UUID
	BankAccountID pgtype.UUID
}

func (q *Queries) UpdateCleanupSessionBankAccount(ctx context.Context, arg UpdateCleanupSessionBankAccountParams) error {
	_, err := q.db.Exec(ctx, updateCleanupSessionBankAccount, arg.ID, arg.BankAccountID)
	return err
}

const updateCleanupSessionRowCount = `-- name: UpdateCleanupSessionRowCount :exec
UPDATE fignode.staging_sessions
SET row_count = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCleanupSessionRowCountParams struct {
	ID       pgtype.UUID
	RowCount int32
}

func (q *Queries) UpdateCleanupSessionRowCount(ctx context.Context, arg UpdateCleanupSessionRowCountParams) error {
	_, err := q.db.Exec(ctx, updateCleanupSessionRowCount, arg.ID, arg.RowCount)
	return err
}

const updateCleanupSessionStatus = `-- name: UpdateCleanupSessionStatus :exec
UPDATE fignode.staging_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCleanupSessionStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateCleanupSessionStatus(ctx context.Context, arg UpdateCleanupSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateCleanupSessionStatus, arg.ID, arg.Status)
	return err
}

const updateRowEnrichment = `-- name: UpdateRowEnrichment :exec
UPDATE fignode.staging_transactions
SET
    predicted_vendor_id     = $1,
    predicted_vendor_name   = COALESCE(NULLIF($2, ''), predicted_vendor_name),
    predicted_customer_id   = $3,
    predicted_customer_name = COALESCE(NULLIF($4, ''), predicted_customer_name),
    predicted_account_id    = $5,
    predicted_account_name  = COALESCE(NULLIF($6, ''), predicted_account_name),
    confidence_score        = $7,
    ai_reasoning            = $8,
    duplicate_of            = $9,
    is_recurring            = $10,
    split_suggestion        = $11,
    merchant_name           = COALESCE(NULLIF($12, ''), merchant_name),
    category                = COALESCE(NULLIF($13, ''), category),
    status                  = COALESCE(NULLIF($14, ''), 'ENRICHED'),
    updated_at              = NOW()
WHERE id = $15
`

type UpdateRowEnrichmentParams struct {
	PredictedVendorID     pgtype.UUID
	PredictedVendorName   interface{}
	PredictedCustomerID   pgtype.UUID
	PredictedCustomerName interface{}
	PredictedAccountID    pgtype.UUID
	PredictedAccountName  interface{}
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	DuplicateOf           pgtype.UUID
	IsRecurring           pgtype.Bool
	SplitSuggestion       []byte
	MerchantName          interface{}
	Category              interface{}
	Status                interface{}
	ID                    pgtype.UUID
}

func (q *Queries) UpdateRowEnrichment(ctx context.Context, arg UpdateRowEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updateRowEnrichment,
		arg.PredictedVendorID,
		arg.PredictedVendorName,
		arg.PredictedCustomerID,
		arg.PredictedCustomerName,
		arg.PredictedAccountID,
		arg.PredictedAccountName,
		arg.ConfidenceScore,
		arg.AiReasoning,
		arg.DuplicateOf,
		arg.IsRecurring,
		arg.SplitSuggestion,
		arg.MerchantName,
		arg.Category,
		arg.Status,
		arg.ID,
	)
	return err
}
