// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateSessionContextJSON = `-- name: UpdateSessionContextJSON :exec
UPDATE toro_core.conversation_sessions
SET context_json = $2
WHERE id = $1
`

type UpdateSessionContextJSONParams struct {
	ID          pgtype.UUID
	ContextJson []byte
}

func (q *Queries) UpdateSessionContextJSON(ctx context.Context, arg UpdateSessionContextJSONParams) error {
	_, err := q.db.Exec(ctx, updateSessionContextJSON, arg.ID, arg.ContextJson)
	return err
}
