// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_engine.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllActiveEmailAccounts = `-- name: GetAllActiveEmailAccounts :many
SELECT id, email, encrypted_password, daily_send_count, daily_send_limit, status, tenant_id
FROM marketing.email_accounts
WHERE status = 'active'
`

type GetAllActiveEmailAccountsRow struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
}

func (q *Queries) GetAllActiveEmailAccounts(ctx context.Context) ([]GetAllActiveEmailAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveEmailAccountsRow
	for rows.Next() {
		var i GetAllActiveEmailAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EncryptedPassword,
			&i.DailySendCount,
			&i.DailySendLimit,
			&i.Status,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWarmingEmailAccounts = `-- name: GetAllWarmingEmailAccounts :many
SELECT id, email, encrypted_password, daily_send_count, daily_send_limit, status, tenant_id, warmup_phase, domain_created_at, bounce_count, spam_complaints
FROM marketing.email_accounts
WHERE status IN ('warming', 'active')
`

type GetAllWarmingEmailAccountsRow struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
	WarmupPhase       int32
	DomainCreatedAt   pgtype.Timestamptz
	BounceCount       int32
	SpamComplaints    int32
}

func (q *Queries) GetAllWarmingEmailAccounts(ctx context.Context) ([]GetAllWarmingEmailAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAllWarmingEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWarmingEmailAccountsRow
	for rows.Next() {
		var i GetAllWarmingEmailAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EncryptedPassword,
			&i.DailySendCount,
			&i.DailySendLimit,
			&i.Status,
			&i.TenantID,
			&i.WarmupPhase,
			&i.DomainCreatedAt,
			&i.BounceCount,
			&i.SpamComplaints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignStep = `-- name: GetCampaignStep :one
SELECT id, campaign_id, step_number, subject_template, body_template, delay_duration, landing_page_id, email_form_id
FROM marketing.campaign_steps
WHERE campaign_id = $1 AND step_number = $2
`

type GetCampaignStepParams struct {
	CampaignID pgtype.UUID
	StepNumber int32
}

type GetCampaignStepRow struct {
	ID              pgtype.UUID
	CampaignID      pgtype.UUID
	StepNumber      int32
	SubjectTemplate string
	BodyTemplate    string
	DelayDuration   pgtype.Interval
	LandingPageID   pgtype.UUID
	EmailFormID     pgtype.UUID
}

func (q *Queries) GetCampaignStep(ctx context.Context, arg GetCampaignStepParams) (GetCampaignStepRow, error) {
	row := q.db.QueryRow(ctx, getCampaignStep, arg.CampaignID, arg.StepNumber)
	var i GetCampaignStepRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.StepNumber,
		&i.SubjectTemplate,
		&i.BodyTemplate,
		&i.DelayDuration,
		&i.LandingPageID,
		&i.EmailFormID,
	)
	return i, err
}

const getEmailAccountByEmail = `-- name: GetEmailAccountByEmail :one
SELECT id, email, encrypted_password, daily_send_count, daily_send_limit, status, tenant_id
FROM marketing.email_accounts
WHERE email = $1
`

type GetEmailAccountByEmailRow struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
}

func (q *Queries) GetEmailAccountByEmail(ctx context.Context, email string) (GetEmailAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmailAccountByEmail, email)
	var i GetEmailAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EncryptedPassword,
		&i.DailySendCount,
		&i.DailySendLimit,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const getEmailAccountByID = `-- name: GetEmailAccountByID :one
SELECT id, email, encrypted_password, daily_send_count, daily_send_limit, status, tenant_id
FROM marketing.email_accounts
WHERE id = $1
`

type GetEmailAccountByIDRow struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
}

func (q *Queries) GetEmailAccountByID(ctx context.Context, id pgtype.UUID) (GetEmailAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailAccountByID, id)
	var i GetEmailAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EncryptedPassword,
		&i.DailySendCount,
		&i.DailySendLimit,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const getEmailLogsForProspect = `-- name: GetEmailLogsForProspect :many
SELECT id, prospect_id, campaign_id, nats_msg_id, event_type, metadata, created_at, landing_page_id, email_form_id
FROM marketing.email_logs
WHERE prospect_id = $1 AND campaign_id = $2
ORDER BY created_at DESC
`

type GetEmailLogsForProspectParams struct {
	ProspectID pgtype.UUID
	CampaignID pgtype.UUID
}

type GetEmailLogsForProspectRow struct {
	ID            pgtype.UUID
	ProspectID    pgtype.UUID
	CampaignID    pgtype.UUID
	NatsMsgID     pgtype.Text
	EventType     string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
	LandingPageID pgtype.UUID
	EmailFormID   pgtype.UUID
}

func (q *Queries) GetEmailLogsForProspect(ctx context.Context, arg GetEmailLogsForProspectParams) ([]GetEmailLogsForProspectRow, error) {
	rows, err := q.db.Query(ctx, getEmailLogsForProspect, arg.ProspectID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmailLogsForProspectRow
	for rows.Next() {
		var i GetEmailLogsForProspectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProspectID,
			&i.CampaignID,
			&i.NatsMsgID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
			&i.LandingPageID,
			&i.EmailFormID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextAvailableEmailAccount = `-- name: GetNextAvailableEmailAccount :one
SELECT id, email, encrypted_password, daily_send_count, daily_send_limit, status, tenant_id
FROM marketing.email_accounts
WHERE status = 'active' AND daily_send_count < daily_send_limit AND tenant_id = $1
ORDER BY daily_send_count ASC
LIMIT 1
`

type GetNextAvailableEmailAccountRow struct {
	ID                pgtype.UUID
	Email             string
	EncryptedPassword string
	DailySendCount    int32
	DailySendLimit    int32
	Status            string
	TenantID          pgtype.UUID
}

func (q *Queries) GetNextAvailableEmailAccount(ctx context.Context, tenantID pgtype.UUID) (GetNextAvailableEmailAccountRow, error) {
	row := q.db.QueryRow(ctx, getNextAvailableEmailAccount, tenantID)
	var i GetNextAvailableEmailAccountRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EncryptedPassword,
		&i.DailySendCount,
		&i.DailySendLimit,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const getProspectByID = `-- name: GetProspectByID :one
SELECT id, email, first_name, last_name, metadata, campaign_id, current_step_id, status, tenant_id
FROM marketing.prospects
WHERE id = $1
`

type GetProspectByIDRow struct {
	ID            pgtype.UUID
	Email         string
	FirstName     pgtype.Text
	LastName      pgtype.Text
	Metadata      []byte
	CampaignID    pgtype.UUID
	CurrentStepID pgtype.UUID
	Status        string
	TenantID      pgtype.UUID
}

func (q *Queries) GetProspectByID(ctx context.Context, id pgtype.UUID) (GetProspectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProspectByID, id)
	var i GetProspectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Metadata,
		&i.CampaignID,
		&i.CurrentStepID,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const hasProspectInteracted = `-- name: HasProspectInteracted :one
SELECT EXISTS (
    SELECT 1 
    FROM marketing.email_logs 
    WHERE prospect_id = $1 
      AND campaign_id = $2 
      AND event_type IN ('clicked', 'replied')
)
`

type HasProspectInteractedParams struct {
	ProspectID pgtype.UUID
	CampaignID pgtype.UUID
}

func (q *Queries) HasProspectInteracted(ctx context.Context, arg HasProspectInteractedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProspectInteracted, arg.ProspectID, arg.CampaignID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementEmailAccountSendCount = `-- name: IncrementEmailAccountSendCount :exec
UPDATE marketing.email_accounts
SET daily_send_count = daily_send_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementEmailAccountSendCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmailAccountSendCount, id)
	return err
}

const logEmailEvent = `-- name: LogEmailEvent :exec
INSERT INTO marketing.email_logs (
    prospect_id, campaign_id, list_id, nats_msg_id, event_type, metadata, user_agent, ip_address, is_human, landing_page_id, email_form_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type LogEmailEventParams struct {
	ProspectID    pgtype.UUID
	CampaignID    pgtype.UUID
	ListID        pgtype.UUID
	NatsMsgID     pgtype.Text
	EventType     string
	Metadata      []byte
	UserAgent     pgtype.Text
	IpAddress     pgtype.Text
	IsHuman       pgtype.Bool
	LandingPageID pgtype.UUID
	EmailFormID   pgtype.UUID
}

func (q *Queries) LogEmailEvent(ctx context.Context, arg LogEmailEventParams) error {
	_, err := q.db.Exec(ctx, logEmailEvent,
		arg.ProspectID,
		arg.CampaignID,
		arg.ListID,
		arg.NatsMsgID,
		arg.EventType,
		arg.Metadata,
		arg.UserAgent,
		arg.IpAddress,
		arg.IsHuman,
		arg.LandingPageID,
		arg.EmailFormID,
	)
	return err
}

const updateEmailAccountStatus = `-- name: UpdateEmailAccountStatus :exec
UPDATE marketing.email_accounts
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateEmailAccountStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateEmailAccountStatus(ctx context.Context, arg UpdateEmailAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountStatus, arg.Status, arg.ID)
	return err
}

const updateEmailAccountWarmup = `-- name: UpdateEmailAccountWarmup :exec
UPDATE marketing.email_accounts
SET daily_send_limit = $1, warmup_phase = $2, bounce_count = $3, spam_complaints = $4, status = $5, updated_at = NOW()
WHERE id = $6
`

type UpdateEmailAccountWarmupParams struct {
	DailySendLimit int32
	WarmupPhase    int32
	BounceCount    int32
	SpamComplaints int32
	Status         string
	ID             pgtype.UUID
}

func (q *Queries) UpdateEmailAccountWarmup(ctx context.Context, arg UpdateEmailAccountWarmupParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountWarmup,
		arg.DailySendLimit,
		arg.WarmupPhase,
		arg.BounceCount,
		arg.SpamComplaints,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateProspectStatus = `-- name: UpdateProspectStatus :exec
UPDATE marketing.prospects
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateProspectStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateProspectStatus(ctx context.Context, arg UpdateProspectStatusParams) error {
	_, err := q.db.Exec(ctx, updateProspectStatus, arg.Status, arg.ID)
	return err
}
