// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrichment.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoreMasterPattern = `-- name: CreateCoreMasterPattern :one
INSERT INTO toro_core.master_patterns (
    master_merchant_id, cleaned_stem, pattern_type, regex_pattern, is_intermediary
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, master_merchant_id, cleaned_stem, pattern_type, regex_pattern, is_intermediary
`

type CreateCoreMasterPatternParams struct {
	MasterMerchantID pgtype.UUID
	CleanedStem      string
	PatternType      string
	RegexPattern     pgtype.Text
	IsIntermediary   bool
}

type CreateCoreMasterPatternRow struct {
	ID               pgtype.UUID
	MasterMerchantID pgtype.UUID
	CleanedStem      string
	PatternType      string
	RegexPattern     pgtype.Text
	IsIntermediary   bool
}

func (q *Queries) CreateCoreMasterPattern(ctx context.Context, arg CreateCoreMasterPatternParams) (CreateCoreMasterPatternRow, error) {
	row := q.db.QueryRow(ctx, createCoreMasterPattern,
		arg.MasterMerchantID,
		arg.CleanedStem,
		arg.PatternType,
		arg.RegexPattern,
		arg.IsIntermediary,
	)
	var i CreateCoreMasterPatternRow
	err := row.Scan(
		&i.ID,
		&i.MasterMerchantID,
		&i.CleanedStem,
		&i.PatternType,
		&i.RegexPattern,
		&i.IsIntermediary,
	)
	return i, err
}

const createMerchantMultilingualAlias = `-- name: CreateMerchantMultilingualAlias :one
INSERT INTO toro_core.moroccan_merchant_multilingual_aliases (
    master_merchant_id, alias_variant, script_type, language_code, is_primary, confidence_score
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, master_merchant_id, alias_variant, script_type, language_code, is_primary, confidence_score
`

type CreateMerchantMultilingualAliasParams struct {
	MasterMerchantID pgtype.UUID
	AliasVariant     string
	ScriptType       string
	LanguageCode     string
	IsPrimary        bool
	ConfidenceScore  pgtype.Numeric
}

type CreateMerchantMultilingualAliasRow struct {
	ID               pgtype.UUID
	MasterMerchantID pgtype.UUID
	AliasVariant     string
	ScriptType       string
	LanguageCode     string
	IsPrimary        bool
	ConfidenceScore  pgtype.Numeric
}

func (q *Queries) CreateMerchantMultilingualAlias(ctx context.Context, arg CreateMerchantMultilingualAliasParams) (CreateMerchantMultilingualAliasRow, error) {
	row := q.db.QueryRow(ctx, createMerchantMultilingualAlias,
		arg.MasterMerchantID,
		arg.AliasVariant,
		arg.ScriptType,
		arg.LanguageCode,
		arg.IsPrimary,
		arg.ConfidenceScore,
	)
	var i CreateMerchantMultilingualAliasRow
	err := row.Scan(
		&i.ID,
		&i.MasterMerchantID,
		&i.AliasVariant,
		&i.ScriptType,
		&i.LanguageCode,
		&i.IsPrimary,
		&i.ConfidenceScore,
	)
	return i, err
}

const findMerchantByExactMultilingualAlias = `-- name: FindMerchantByExactMultilingualAlias :one
SELECT m.id, m.normalized_name, m.legal_name, m.country_code, m.merchant_category, m.ice, m.identifiant_fiscal, m.registre_commerce, m.cnss_number, m.primary_domain, m.logo_url, m.default_pcgm_account, m.default_tva_rate, m.default_tva_account, m.is_tva_deductible, m.is_foreign_service, m.ras_applicable, m.ras_rate, m.confidence_weight,
       a.alias_variant, a.script_type, a.language_code, a.confidence_score
FROM toro_core.moroccan_merchant_multilingual_aliases a
JOIN toro_core.master_merchants m ON a.master_merchant_id = m.id
WHERE LOWER(a.alias_variant) = LOWER($1)
ORDER BY a.is_primary DESC, a.confidence_score DESC
LIMIT 1
`

type FindMerchantByExactMultilingualAliasRow struct {
	ID                 pgtype.UUID
	NormalizedName     string
	LegalName          pgtype.Text
	CountryCode        string
	MerchantCategory   string
	Ice                pgtype.Text
	IdentifiantFiscal  pgtype.Text
	RegistreCommerce   pgtype.Text
	CnssNumber         pgtype.Text
	PrimaryDomain      pgtype.Text
	LogoUrl            pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
	DefaultTvaAccount  string
	IsTvaDeductible    bool
	IsForeignService   bool
	RasApplicable      bool
	RasRate            pgtype.Numeric
	ConfidenceWeight   pgtype.Numeric
	AliasVariant       string
	ScriptType         string
	LanguageCode       string
	ConfidenceScore    pgtype.Numeric
}

func (q *Queries) FindMerchantByExactMultilingualAlias(ctx context.Context, lower string) (FindMerchantByExactMultilingualAliasRow, error) {
	row := q.db.QueryRow(ctx, findMerchantByExactMultilingualAlias, lower)
	var i FindMerchantByExactMultilingualAliasRow
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.LegalName,
		&i.CountryCode,
		&i.MerchantCategory,
		&i.Ice,
		&i.IdentifiantFiscal,
		&i.RegistreCommerce,
		&i.CnssNumber,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.DefaultPcgmAccount,
		&i.DefaultTvaRate,
		&i.DefaultTvaAccount,
		&i.IsTvaDeductible,
		&i.IsForeignService,
		&i.RasApplicable,
		&i.RasRate,
		&i.ConfidenceWeight,
		&i.AliasVariant,
		&i.ScriptType,
		&i.LanguageCode,
		&i.ConfidenceScore,
	)
	return i, err
}

const findMerchantByFuzzyMultilingualAlias = `-- name: FindMerchantByFuzzyMultilingualAlias :many
SELECT m.id, m.normalized_name, m.legal_name, m.country_code, m.merchant_category, m.ice, m.identifiant_fiscal, m.registre_commerce, m.cnss_number, m.primary_domain, m.logo_url, m.default_pcgm_account, m.default_tva_rate, m.default_tva_account, m.is_tva_deductible, m.is_foreign_service, m.ras_applicable, m.ras_rate, m.confidence_weight,
       a.alias_variant, a.script_type, a.language_code, a.confidence_score,
       similarity(a.alias_variant, $1) AS match_similarity
FROM toro_core.moroccan_merchant_multilingual_aliases a
JOIN toro_core.master_merchants m ON a.master_merchant_id = m.id
WHERE a.alias_variant % $1
ORDER BY match_similarity DESC, a.is_primary DESC
LIMIT 5
`

type FindMerchantByFuzzyMultilingualAliasRow struct {
	ID                 pgtype.UUID
	NormalizedName     string
	LegalName          pgtype.Text
	CountryCode        string
	MerchantCategory   string
	Ice                pgtype.Text
	IdentifiantFiscal  pgtype.Text
	RegistreCommerce   pgtype.Text
	CnssNumber         pgtype.Text
	PrimaryDomain      pgtype.Text
	LogoUrl            pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
	DefaultTvaAccount  string
	IsTvaDeductible    bool
	IsForeignService   bool
	RasApplicable      bool
	RasRate            pgtype.Numeric
	ConfidenceWeight   pgtype.Numeric
	AliasVariant       string
	ScriptType         string
	LanguageCode       string
	ConfidenceScore    pgtype.Numeric
	MatchSimilarity    float32
}

func (q *Queries) FindMerchantByFuzzyMultilingualAlias(ctx context.Context, similarity string) ([]FindMerchantByFuzzyMultilingualAliasRow, error) {
	rows, err := q.db.Query(ctx, findMerchantByFuzzyMultilingualAlias, similarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMerchantByFuzzyMultilingualAliasRow
	for rows.Next() {
		var i FindMerchantByFuzzyMultilingualAliasRow
		if err := rows.Scan(
			&i.ID,
			&i.NormalizedName,
			&i.LegalName,
			&i.CountryCode,
			&i.MerchantCategory,
			&i.Ice,
			&i.IdentifiantFiscal,
			&i.RegistreCommerce,
			&i.CnssNumber,
			&i.PrimaryDomain,
			&i.LogoUrl,
			&i.DefaultPcgmAccount,
			&i.DefaultTvaRate,
			&i.DefaultTvaAccount,
			&i.IsTvaDeductible,
			&i.IsForeignService,
			&i.RasApplicable,
			&i.RasRate,
			&i.ConfidenceWeight,
			&i.AliasVariant,
			&i.ScriptType,
			&i.LanguageCode,
			&i.ConfidenceScore,
			&i.MatchSimilarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnnualForeignServiceRunningTotal = `-- name: GetAnnualForeignServiceRunningTotal :one
SELECT COALESCE(SUM(cumulative_gross_invoiced_mad), 0)::NUMERIC(15,2) AS annual_gross_mad,
       COALESCE(SUM(cumulative_ras_withheld_mad), 0)::NUMERIC(15,2)   AS annual_ras_mad,
       COALESCE(SUM(cumulative_net_paid_mad), 0)::NUMERIC(15,2)       AS annual_net_mad,
       COALESCE(SUM(transaction_count), 0)::INT                       AS annual_transaction_count
FROM toro_core.foreign_service_running_totals
WHERE realm_id = $1 AND provider_id = $2 AND fiscal_year = $3
`

type GetAnnualForeignServiceRunningTotalParams struct {
	RealmID    string
	ProviderID pgtype.UUID
	FiscalYear int32
}

type GetAnnualForeignServiceRunningTotalRow struct {
	AnnualGrossMad         pgtype.Numeric
	AnnualRasMad           pgtype.Numeric
	AnnualNetMad           pgtype.Numeric
	AnnualTransactionCount int32
}

func (q *Queries) GetAnnualForeignServiceRunningTotal(ctx context.Context, arg GetAnnualForeignServiceRunningTotalParams) (GetAnnualForeignServiceRunningTotalRow, error) {
	row := q.db.QueryRow(ctx, getAnnualForeignServiceRunningTotal, arg.RealmID, arg.ProviderID, arg.FiscalYear)
	var i GetAnnualForeignServiceRunningTotalRow
	err := row.Scan(
		&i.AnnualGrossMad,
		&i.AnnualRasMad,
		&i.AnnualNetMad,
		&i.AnnualTransactionCount,
	)
	return i, err
}

const getForeignServiceRunningTotalForPeriod = `-- name: GetForeignServiceRunningTotalForPeriod :one
SELECT id, realm_id, provider_id, fiscal_year, fiscal_month, cumulative_gross_invoiced_mad, cumulative_ras_withheld_mad, cumulative_net_paid_mad, transaction_count, dgi_declaration_status, last_transaction_at
FROM toro_core.foreign_service_running_totals
WHERE realm_id = $1 AND provider_id = $2 AND fiscal_year = $3 AND fiscal_month = $4
`

type GetForeignServiceRunningTotalForPeriodParams struct {
	RealmID     string
	ProviderID  pgtype.UUID
	FiscalYear  int32
	FiscalMonth int32
}

type GetForeignServiceRunningTotalForPeriodRow struct {
	ID                         pgtype.UUID
	RealmID                    string
	ProviderID                 pgtype.UUID
	FiscalYear                 int32
	FiscalMonth                int32
	CumulativeGrossInvoicedMad pgtype.Numeric
	CumulativeRasWithheldMad   pgtype.Numeric
	CumulativeNetPaidMad       pgtype.Numeric
	TransactionCount           int32
	DgiDeclarationStatus       string
	LastTransactionAt          pgtype.Timestamptz
}

func (q *Queries) GetForeignServiceRunningTotalForPeriod(ctx context.Context, arg GetForeignServiceRunningTotalForPeriodParams) (GetForeignServiceRunningTotalForPeriodRow, error) {
	row := q.db.QueryRow(ctx, getForeignServiceRunningTotalForPeriod,
		arg.RealmID,
		arg.ProviderID,
		arg.FiscalYear,
		arg.FiscalMonth,
	)
	var i GetForeignServiceRunningTotalForPeriodRow
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.ProviderID,
		&i.FiscalYear,
		&i.FiscalMonth,
		&i.CumulativeGrossInvoicedMad,
		&i.CumulativeRasWithheldMad,
		&i.CumulativeNetPaidMad,
		&i.TransactionCount,
		&i.DgiDeclarationStatus,
		&i.LastTransactionAt,
	)
	return i, err
}

const getMasterMerchantByICE = `-- name: GetMasterMerchantByICE :one
SELECT id, normalized_name, legal_name, country_code, merchant_category, ice, identifiant_fiscal, registre_commerce, cnss_number, primary_domain, logo_url, default_pcgm_account, default_tva_rate, default_tva_account, is_tva_deductible, is_foreign_service, ras_applicable, ras_rate, confidence_weight, created_at, updated_at
FROM toro_core.master_merchants
WHERE ice = $1
LIMIT 1
`

func (q *Queries) GetMasterMerchantByICE(ctx context.Context, ice pgtype.Text) (ToroCoreMasterMerchant, error) {
	row := q.db.QueryRow(ctx, getMasterMerchantByICE, ice)
	var i ToroCoreMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.LegalName,
		&i.CountryCode,
		&i.MerchantCategory,
		&i.Ice,
		&i.IdentifiantFiscal,
		&i.RegistreCommerce,
		&i.CnssNumber,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.DefaultPcgmAccount,
		&i.DefaultTvaRate,
		&i.DefaultTvaAccount,
		&i.IsTvaDeductible,
		&i.IsForeignService,
		&i.RasApplicable,
		&i.RasRate,
		&i.ConfidenceWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMasterMerchantByID = `-- name: GetMasterMerchantByID :one
SELECT id, normalized_name, legal_name, country_code, merchant_category, ice, identifiant_fiscal, registre_commerce, cnss_number, primary_domain, logo_url, default_pcgm_account, default_tva_rate, default_tva_account, is_tva_deductible, is_foreign_service, ras_applicable, ras_rate, confidence_weight, created_at, updated_at
FROM toro_core.master_merchants
WHERE id = $1
`

func (q *Queries) GetMasterMerchantByID(ctx context.Context, id pgtype.UUID) (ToroCoreMasterMerchant, error) {
	row := q.db.QueryRow(ctx, getMasterMerchantByID, id)
	var i ToroCoreMasterMerchant
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.LegalName,
		&i.CountryCode,
		&i.MerchantCategory,
		&i.Ice,
		&i.IdentifiantFiscal,
		&i.RegistreCommerce,
		&i.CnssNumber,
		&i.PrimaryDomain,
		&i.LogoUrl,
		&i.DefaultPcgmAccount,
		&i.DefaultTvaRate,
		&i.DefaultTvaAccount,
		&i.IsTvaDeductible,
		&i.IsForeignService,
		&i.RasApplicable,
		&i.RasRate,
		&i.ConfidenceWeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNonResidentForeignProviderByMerchantID = `-- name: GetNonResidentForeignProviderByMerchantID :one
SELECT id, master_merchant_id, provider_name, headquarters_country, tax_residency_status, vat_withholding_rate, service_type, pcgm_expense_account, pcgm_withholding_account, is_active, statutory_legal_basis, created_at, updated_at
FROM toro_core.non_resident_foreign_providers
WHERE master_merchant_id = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetNonResidentForeignProviderByMerchantID(ctx context.Context, masterMerchantID pgtype.UUID) (ToroCoreNonResidentForeignProvider, error) {
	row := q.db.QueryRow(ctx, getNonResidentForeignProviderByMerchantID, masterMerchantID)
	var i ToroCoreNonResidentForeignProvider
	err := row.Scan(
		&i.ID,
		&i.MasterMerchantID,
		&i.ProviderName,
		&i.HeadquartersCountry,
		&i.TaxResidencyStatus,
		&i.VatWithholdingRate,
		&i.ServiceType,
		&i.PcgmExpenseAccount,
		&i.PcgmWithholdingAccount,
		&i.IsActive,
		&i.StatutoryLegalBasis,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNonResidentForeignProviders = `-- name: ListActiveNonResidentForeignProviders :many
SELECT p.id, p.master_merchant_id, p.provider_name, p.headquarters_country, p.tax_residency_status, p.vat_withholding_rate, p.service_type, p.pcgm_expense_account, p.pcgm_withholding_account, p.is_active,
       m.normalized_name, m.default_pcgm_account, m.default_tva_rate
FROM toro_core.non_resident_foreign_providers p
JOIN toro_core.master_merchants m ON p.master_merchant_id = m.id
WHERE p.is_active = TRUE
`

type ListActiveNonResidentForeignProvidersRow struct {
	ID                     pgtype.UUID
	MasterMerchantID       pgtype.UUID
	ProviderName           string
	HeadquartersCountry    string
	TaxResidencyStatus     string
	VatWithholdingRate     pgtype.Numeric
	ServiceType            string
	PcgmExpenseAccount     string
	PcgmWithholdingAccount string
	IsActive               bool
	NormalizedName         string
	DefaultPcgmAccount     string
	DefaultTvaRate         pgtype.Numeric
}

func (q *Queries) ListActiveNonResidentForeignProviders(ctx context.Context) ([]ListActiveNonResidentForeignProvidersRow, error) {
	rows, err := q.db.Query(ctx, listActiveNonResidentForeignProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveNonResidentForeignProvidersRow
	for rows.Next() {
		var i ListActiveNonResidentForeignProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterMerchantID,
			&i.ProviderName,
			&i.HeadquartersCountry,
			&i.TaxResidencyStatus,
			&i.VatWithholdingRate,
			&i.ServiceType,
			&i.PcgmExpenseAccount,
			&i.PcgmWithholdingAccount,
			&i.IsActive,
			&i.NormalizedName,
			&i.DefaultPcgmAccount,
			&i.DefaultTvaRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMultilingualAliases = `-- name: ListAllMultilingualAliases :many
SELECT a.id, a.master_merchant_id, a.alias_variant, a.script_type, a.language_code, a.is_primary, a.confidence_score,
       m.normalized_name, m.merchant_category, m.ice, m.default_pcgm_account, m.default_tva_rate, m.default_tva_account, m.is_foreign_service, m.ras_applicable, m.ras_rate
FROM toro_core.moroccan_merchant_multilingual_aliases a
JOIN toro_core.master_merchants m ON a.master_merchant_id = m.id
`

type ListAllMultilingualAliasesRow struct {
	ID                 pgtype.UUID
	MasterMerchantID   pgtype.UUID
	AliasVariant       string
	ScriptType         string
	LanguageCode       string
	IsPrimary          bool
	ConfidenceScore    pgtype.Numeric
	NormalizedName     string
	MerchantCategory   string
	Ice                pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
	DefaultTvaAccount  string
	IsForeignService   bool
	RasApplicable      bool
	RasRate            pgtype.Numeric
}

func (q *Queries) ListAllMultilingualAliases(ctx context.Context) ([]ListAllMultilingualAliasesRow, error) {
	rows, err := q.db.Query(ctx, listAllMultilingualAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMultilingualAliasesRow
	for rows.Next() {
		var i ListAllMultilingualAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.MasterMerchantID,
			&i.AliasVariant,
			&i.ScriptType,
			&i.LanguageCode,
			&i.IsPrimary,
			&i.ConfidenceScore,
			&i.NormalizedName,
			&i.MerchantCategory,
			&i.Ice,
			&i.DefaultPcgmAccount,
			&i.DefaultTvaRate,
			&i.DefaultTvaAccount,
			&i.IsForeignService,
			&i.RasApplicable,
			&i.RasRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForeignServiceRunningTotalsForTenantPeriod = `-- name: ListForeignServiceRunningTotalsForTenantPeriod :many
SELECT t.id, t.realm_id, t.provider_id, t.fiscal_year, t.fiscal_month, t.cumulative_gross_invoiced_mad, t.cumulative_ras_withheld_mad, t.cumulative_net_paid_mad, t.transaction_count, t.dgi_declaration_status, t.last_transaction_at,
       p.provider_name, p.headquarters_country, p.vat_withholding_rate, p.service_type
FROM toro_core.foreign_service_running_totals t
JOIN toro_core.non_resident_foreign_providers p ON t.provider_id = p.id
WHERE t.realm_id = $1 AND t.fiscal_year = $2 AND t.fiscal_month = $3
ORDER BY t.cumulative_gross_invoiced_mad DESC
`

type ListForeignServiceRunningTotalsForTenantPeriodParams struct {
	RealmID     string
	FiscalYear  int32
	FiscalMonth int32
}

type ListForeignServiceRunningTotalsForTenantPeriodRow struct {
	ID                         pgtype.UUID
	RealmID                    string
	ProviderID                 pgtype.UUID
	FiscalYear                 int32
	FiscalMonth                int32
	CumulativeGrossInvoicedMad pgtype.Numeric
	CumulativeRasWithheldMad   pgtype.Numeric
	CumulativeNetPaidMad       pgtype.Numeric
	TransactionCount           int32
	DgiDeclarationStatus       string
	LastTransactionAt          pgtype.Timestamptz
	ProviderName               string
	HeadquartersCountry        string
	VatWithholdingRate         pgtype.Numeric
	ServiceType                string
}

func (q *Queries) ListForeignServiceRunningTotalsForTenantPeriod(ctx context.Context, arg ListForeignServiceRunningTotalsForTenantPeriodParams) ([]ListForeignServiceRunningTotalsForTenantPeriodRow, error) {
	rows, err := q.db.Query(ctx, listForeignServiceRunningTotalsForTenantPeriod, arg.RealmID, arg.FiscalYear, arg.FiscalMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForeignServiceRunningTotalsForTenantPeriodRow
	for rows.Next() {
		var i ListForeignServiceRunningTotalsForTenantPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.RealmID,
			&i.ProviderID,
			&i.FiscalYear,
			&i.FiscalMonth,
			&i.CumulativeGrossInvoicedMad,
			&i.CumulativeRasWithheldMad,
			&i.CumulativeNetPaidMad,
			&i.TransactionCount,
			&i.DgiDeclarationStatus,
			&i.LastTransactionAt,
			&i.ProviderName,
			&i.HeadquartersCountry,
			&i.VatWithholdingRate,
			&i.ServiceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForeignServiceRunningTotal = `-- name: UpsertForeignServiceRunningTotal :one
INSERT INTO toro_core.foreign_service_running_totals (
    realm_id, provider_id, fiscal_year, fiscal_month,
    cumulative_gross_invoiced_mad, cumulative_ras_withheld_mad, cumulative_net_paid_mad,
    transaction_count, last_transaction_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    1, NOW()
) ON CONFLICT (realm_id, provider_id, fiscal_year, fiscal_month) DO UPDATE SET
    cumulative_gross_invoiced_mad = toro_core.foreign_service_running_totals.cumulative_gross_invoiced_mad + EXCLUDED.cumulative_gross_invoiced_mad,
    cumulative_ras_withheld_mad   = toro_core.foreign_service_running_totals.cumulative_ras_withheld_mad + EXCLUDED.cumulative_ras_withheld_mad,
    cumulative_net_paid_mad       = toro_core.foreign_service_running_totals.cumulative_net_paid_mad + EXCLUDED.cumulative_net_paid_mad,
    transaction_count             = toro_core.foreign_service_running_totals.transaction_count + 1,
    last_transaction_at           = NOW(),
    updated_at                    = NOW()
RETURNING id, realm_id, provider_id, fiscal_year, fiscal_month, cumulative_gross_invoiced_mad, cumulative_ras_withheld_mad, cumulative_net_paid_mad, transaction_count, dgi_declaration_status, last_transaction_at
`

type UpsertForeignServiceRunningTotalParams struct {
	RealmID                    string
	ProviderID                 pgtype.UUID
	FiscalYear                 int32
	FiscalMonth                int32
	CumulativeGrossInvoicedMad pgtype.Numeric
	CumulativeRasWithheldMad   pgtype.Numeric
	CumulativeNetPaidMad       pgtype.Numeric
}

type UpsertForeignServiceRunningTotalRow struct {
	ID                         pgtype.UUID
	RealmID                    string
	ProviderID                 pgtype.UUID
	FiscalYear                 int32
	FiscalMonth                int32
	CumulativeGrossInvoicedMad pgtype.Numeric
	CumulativeRasWithheldMad   pgtype.Numeric
	CumulativeNetPaidMad       pgtype.Numeric
	TransactionCount           int32
	DgiDeclarationStatus       string
	LastTransactionAt          pgtype.Timestamptz
}

func (q *Queries) UpsertForeignServiceRunningTotal(ctx context.Context, arg UpsertForeignServiceRunningTotalParams) (UpsertForeignServiceRunningTotalRow, error) {
	row := q.db.QueryRow(ctx, upsertForeignServiceRunningTotal,
		arg.RealmID,
		arg.ProviderID,
		arg.FiscalYear,
		arg.FiscalMonth,
		arg.CumulativeGrossInvoicedMad,
		arg.CumulativeRasWithheldMad,
		arg.CumulativeNetPaidMad,
	)
	var i UpsertForeignServiceRunningTotalRow
	err := row.Scan(
		&i.ID,
		&i.RealmID,
		&i.ProviderID,
		&i.FiscalYear,
		&i.FiscalMonth,
		&i.CumulativeGrossInvoicedMad,
		&i.CumulativeRasWithheldMad,
		&i.CumulativeNetPaidMad,
		&i.TransactionCount,
		&i.DgiDeclarationStatus,
		&i.LastTransactionAt,
	)
	return i, err
}

const upsertMasterMerchant = `-- name: UpsertMasterMerchant :one

INSERT INTO toro_core.master_merchants (
    id, normalized_name, legal_name, country_code, merchant_category,
    ice, identifiant_fiscal, registre_commerce, cnss_number, primary_domain, logo_url,
    default_pcgm_account, default_tva_rate, default_tva_account, is_tva_deductible,
    is_foreign_service, ras_applicable, ras_rate, confidence_weight
) VALUES (
    COALESCE($19::UUID, gen_random_uuid()),
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18
) ON CONFLICT (id) DO UPDATE SET
    normalized_name = EXCLUDED.normalized_name,
    legal_name = EXCLUDED.legal_name,
    merchant_category = EXCLUDED.merchant_category,
    ice = COALESCE(EXCLUDED.ice, toro_core.master_merchants.ice),
    identifiant_fiscal = COALESCE(EXCLUDED.identifiant_fiscal, toro_core.master_merchants.identifiant_fiscal),
    default_pcgm_account = EXCLUDED.default_pcgm_account,
    default_tva_rate = EXCLUDED.default_tva_rate,
    is_foreign_service = EXCLUDED.is_foreign_service,
    ras_applicable = EXCLUDED.ras_applicable,
    ras_rate = EXCLUDED.ras_rate,
    updated_at = NOW()
RETURNING id, normalized_name, legal_name, country_code, merchant_category, ice, default_pcgm_account, default_tva_rate
`

type UpsertMasterMerchantParams struct {
	NormalizedName     string
	LegalName          pgtype.Text
	CountryCode        string
	MerchantCategory   string
	Ice                pgtype.Text
	IdentifiantFiscal  pgtype.Text
	RegistreCommerce   pgtype.Text
	CnssNumber         pgtype.Text
	PrimaryDomain      pgtype.Text
	LogoUrl            pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
	DefaultTvaAccount  string
	IsTvaDeductible    bool
	IsForeignService   bool
	RasApplicable      bool
	RasRate            pgtype.Numeric
	ConfidenceWeight   pgtype.Numeric
	ID                 pgtype.UUID
}

type UpsertMasterMerchantRow struct {
	ID                 pgtype.UUID
	NormalizedName     string
	LegalName          pgtype.Text
	CountryCode        string
	MerchantCategory   string
	Ice                pgtype.Text
	DefaultPcgmAccount string
	DefaultTvaRate     pgtype.Numeric
}

// =========================================================================
// Dynamic Seeding & Continuous Learning Queries
// =========================================================================
func (q *Queries) UpsertMasterMerchant(ctx context.Context, arg UpsertMasterMerchantParams) (UpsertMasterMerchantRow, error) {
	row := q.db.QueryRow(ctx, upsertMasterMerchant,
		arg.NormalizedName,
		arg.LegalName,
		arg.CountryCode,
		arg.MerchantCategory,
		arg.Ice,
		arg.IdentifiantFiscal,
		arg.RegistreCommerce,
		arg.CnssNumber,
		arg.PrimaryDomain,
		arg.LogoUrl,
		arg.DefaultPcgmAccount,
		arg.DefaultTvaRate,
		arg.DefaultTvaAccount,
		arg.IsTvaDeductible,
		arg.IsForeignService,
		arg.RasApplicable,
		arg.RasRate,
		arg.ConfidenceWeight,
		arg.ID,
	)
	var i UpsertMasterMerchantRow
	err := row.Scan(
		&i.ID,
		&i.NormalizedName,
		&i.LegalName,
		&i.CountryCode,
		&i.MerchantCategory,
		&i.Ice,
		&i.DefaultPcgmAccount,
		&i.DefaultTvaRate,
	)
	return i, err
}
