// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fignode.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustAccuracyScore = `-- name: AdjustAccuracyScore :exec
UPDATE fignode.employee_profiles
SET ai_accuracy_score = CASE
        WHEN $1::NUMERIC > 0 THEN LEAST(1.000, ai_accuracy_score + $1)
        ELSE GREATEST(0.000, ai_accuracy_score + $1)
    END,
    updated_at = now()
WHERE user_id = $2
`

type AdjustAccuracyScoreParams struct {
	Delta  pgtype.Numeric
	UserID pgtype.UUID
}

func (q *Queries) AdjustAccuracyScore(ctx context.Context, arg AdjustAccuracyScoreParams) error {
	_, err := q.db.Exec(ctx, adjustAccuracyScore, arg.Delta, arg.UserID)
	return err
}

const clearTransaction = `-- name: ClearTransaction :exec

UPDATE fignode.staging_transactions
SET status = 'APPROVED', updated_at = now()
WHERE id = $1
`

// =========================================================================
// Status Updates (Legacy endpoints mapped to new schema)
// =========================================================================
func (q *Queries) ClearTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearTransaction, id)
	return err
}

const computeAllTimeLeaderboard = `-- name: ComputeAllTimeLeaderboard :many

SELECT
    p.user_id,
    u.email,
    p.total_cleared AS cleared,
    p.streak
FROM fignode.employee_profiles p
JOIN toro_core.users u ON u.id = p.user_id
WHERE u.is_active = TRUE
ORDER BY p.total_cleared DESC,
         p.streak DESC,
         u.email ASC
LIMIT 100
`

type ComputeAllTimeLeaderboardRow struct {
	UserID  pgtype.UUID
	Email   string
	Cleared int32
	Streak  int32
}

// =========================================================================
// Leaderboard: Snapshot computation & retrieval
// =========================================================================
func (q *Queries) ComputeAllTimeLeaderboard(ctx context.Context) ([]ComputeAllTimeLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, computeAllTimeLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputeAllTimeLeaderboardRow
	for rows.Next() {
		var i ComputeAllTimeLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Cleared,
			&i.Streak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computePeriodLeaderboard = `-- name: ComputePeriodLeaderboard :many
SELECT
    p.user_id,
    u.email,
    COUNT(t.id)::INT AS cleared,
    p.streak
FROM fignode.employee_profiles p
JOIN toro_core.users u ON u.id = p.user_id
LEFT JOIN fignode.staging_transactions t
    ON t.swiped_by = p.user_id 
    AND t.status IN ('APPROVED', 'POSTED')
    AND t.updated_at >= $1::TIMESTAMPTZ
WHERE u.is_active = TRUE
GROUP BY p.user_id, u.email, p.streak
ORDER BY COUNT(t.id) DESC,
         p.streak DESC,
         u.email ASC
LIMIT 100
`

type ComputePeriodLeaderboardRow struct {
	UserID  pgtype.UUID
	Email   string
	Cleared int32
	Streak  int32
}

func (q *Queries) ComputePeriodLeaderboard(ctx context.Context, since pgtype.Timestamptz) ([]ComputePeriodLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, computePeriodLeaderboard, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputePeriodLeaderboardRow
	for rows.Next() {
		var i ComputePeriodLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Cleared,
			&i.Streak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEmployeeProfile = `-- name: CreateEmployeeProfile :exec
INSERT INTO fignode.employee_profiles (user_id, first_name, last_name, is_manager)
VALUES ($1, $2, $3, $4)
`

type CreateEmployeeProfileParams struct {
	UserID    pgtype.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
	IsManager bool
}

func (q *Queries) CreateEmployeeProfile(ctx context.Context, arg CreateEmployeeProfileParams) error {
	_, err := q.db.Exec(ctx, createEmployeeProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.IsManager,
	)
	return err
}

const createEmployeeUser = `-- name: CreateEmployeeUser :one

INSERT INTO toro_core.users (entity_id, email, password_hash, role, user_type)
VALUES ($1, $2, $3, 'member', 'employee') RETURNING id
`

type CreateEmployeeUserParams struct {
	EntityID     pgtype.UUID
	Email        string
	PasswordHash string
}

// =========================================================================
// Auth: Employee Registration & Login
// =========================================================================
func (q *Queries) CreateEmployeeUser(ctx context.Context, arg CreateEmployeeUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEmployeeUser, arg.EntityID, arg.Email, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.entity_id,
    u.is_active,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.email = $1 AND u.user_type = 'employee'
`

type GetEmployeeByEmailRow struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EntityID        pgtype.UUID
	IsActive        pgtype.Bool
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (GetEmployeeByEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i GetEmployeeByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EntityID,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT
    u.id,
    u.email,
    u.entity_id,
    u.is_active,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.user_type = 'employee'
`

type GetEmployeeByIDRow struct {
	ID              pgtype.UUID
	Email           string
	EntityID        pgtype.UUID
	IsActive        pgtype.Bool
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeeByID(ctx context.Context, id pgtype.UUID) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EntityID,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeProfileForUpdate = `-- name: GetEmployeeProfileForUpdate :one

SELECT user_id, first_name, last_name, is_manager, ai_accuracy_score, streak, streak_last_date, total_cleared, today_cleared, today_cleared_date, created_at, updated_at FROM fignode.employee_profiles
WHERE user_id = $1
FOR UPDATE
`

// =========================================================================
// Updates
// =========================================================================
func (q *Queries) GetEmployeeProfileForUpdate(ctx context.Context, userID pgtype.UUID) (FignodeEmployeeProfile, error) {
	row := q.db.QueryRow(ctx, getEmployeeProfileForUpdate, userID)
	var i FignodeEmployeeProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.StreakLastDate,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.TodayClearedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeePublic = `-- name: GetEmployeePublic :one
SELECT
    u.id,
    u.email,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.user_type = 'employee'
`

type GetEmployeePublicRow struct {
	ID              pgtype.UUID
	Email           string
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeePublic(ctx context.Context, id pgtype.UUID) (GetEmployeePublicRow, error) {
	row := q.db.QueryRow(ctx, getEmployeePublic, id)
	var i GetEmployeePublicRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeStats = `-- name: GetEmployeeStats :one

SELECT
    p.total_cleared,
    p.today_cleared,
    p.streak,
    p.ai_accuracy_score
FROM fignode.employee_profiles p
WHERE p.user_id = $1
`

type GetEmployeeStatsRow struct {
	TotalCleared    int32
	TodayCleared    int32
	Streak          int32
	AiAccuracyScore pgtype.Numeric
}

// =========================================================================
// Stats: Employee dashboard
// =========================================================================
func (q *Queries) GetEmployeeStats(ctx context.Context, userID pgtype.UUID) (GetEmployeeStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeStats, userID)
	var i GetEmployeeStatsRow
	err := row.Scan(
		&i.TotalCleared,
		&i.TodayCleared,
		&i.Streak,
		&i.AiAccuracyScore,
	)
	return i, err
}

const getInitialEnrichedTransactionsByRealm = `-- name: GetInitialEnrichedTransactionsByRealm :many

SELECT id, session_id, realm_id, row_index, source_type, raw_description, raw_amount, raw_date, plaid_transaction_id, bank_account_id, merchant_name, logo_url, plaid_category, is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name, confidence_score, ai_reasoning, human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id, duplicate_of, is_recurring, split_suggestion, status, erp_transaction_id, error_message, reconciled_at, reconciled_by, rule_group_id, created_at, updated_at, is_ambiguous, ambiguity_reason FROM fignode.staging_transactions
WHERE status = 'ENRICHED' AND realm_id = $1 AND duplicate_of IS NULL
ORDER BY created_at DESC LIMIT 50
`

// =========================================================================
// Fignode Transactions Startup
// =========================================================================
func (q *Queries) GetInitialEnrichedTransactionsByRealm(ctx context.Context, realmID pgtype.Text) ([]FignodeStagingTransaction, error) {
	rows, err := q.db.Query(ctx, getInitialEnrichedTransactionsByRealm, realmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FignodeStagingTransaction
	for rows.Next() {
		var i FignodeStagingTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.RowIndex,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.PlaidTransactionID,
			&i.BankAccountID,
			&i.MerchantName,
			&i.LogoUrl,
			&i.PlaidCategory,
			&i.IsPending,
			&i.PredictedVendorID,
			&i.PredictedVendorName,
			&i.PredictedCustomerID,
			&i.PredictedCustomerName,
			&i.PredictedAccountID,
			&i.PredictedAccountName,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.HumanAction,
			&i.SwipedBy,
			&i.SwipedAt,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.Status,
			&i.ErpTransactionID,
			&i.ErrorMessage,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.RuleGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAmbiguous,
			&i.AmbiguityReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestLeaderboardSnapshot = `-- name: GetLatestLeaderboardSnapshot :one
SELECT entries, computed_at
FROM fignode.leaderboard_snapshots
WHERE period = $1
ORDER BY computed_at DESC
LIMIT 1
`

type GetLatestLeaderboardSnapshotRow struct {
	Entries    []byte
	ComputedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestLeaderboardSnapshot(ctx context.Context, period string) (GetLatestLeaderboardSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getLatestLeaderboardSnapshot, period)
	var i GetLatestLeaderboardSnapshotRow
	err := row.Scan(&i.Entries, &i.ComputedAt)
	return i, err
}

const getPendingFignodeTransactions = `-- name: GetPendingFignodeTransactions :many

SELECT id, session_id, realm_id, row_index, source_type, raw_description, raw_amount, raw_date, plaid_transaction_id, bank_account_id, merchant_name, logo_url, plaid_category, is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name, confidence_score, ai_reasoning, human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id, duplicate_of, is_recurring, split_suggestion, status, erp_transaction_id, error_message, reconciled_at, reconciled_by, rule_group_id, created_at, updated_at, is_ambiguous, ambiguity_reason FROM fignode.staging_transactions
WHERE status = 'PENDING_AI' 
  AND human_action IS NULL
  AND session_id IS NOT NULL -- Example: filter logic
ORDER BY created_at DESC
LIMIT 10
`

// =========================================================================
// Transactions Batch
// =========================================================================
func (q *Queries) GetPendingFignodeTransactions(ctx context.Context) ([]FignodeStagingTransaction, error) {
	rows, err := q.db.Query(ctx, getPendingFignodeTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FignodeStagingTransaction
	for rows.Next() {
		var i FignodeStagingTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.RowIndex,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.PlaidTransactionID,
			&i.BankAccountID,
			&i.MerchantName,
			&i.LogoUrl,
			&i.PlaidCategory,
			&i.IsPending,
			&i.PredictedVendorID,
			&i.PredictedVendorName,
			&i.PredictedCustomerID,
			&i.PredictedCustomerName,
			&i.PredictedAccountID,
			&i.PredictedAccountName,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.HumanAction,
			&i.SwipedBy,
			&i.SwipedAt,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.Status,
			&i.ErpTransactionID,
			&i.ErrorMessage,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.RuleGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAmbiguous,
			&i.AmbiguityReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingStagingTransactions = `-- name: GetPendingStagingTransactions :many

SELECT id, session_id, realm_id, row_index, source_type, raw_description, raw_amount, raw_date, plaid_transaction_id, bank_account_id, merchant_name, logo_url, plaid_category, is_pending, predicted_vendor_id, predicted_vendor_name, predicted_customer_id, predicted_customer_name, predicted_account_id, predicted_account_name, confidence_score, ai_reasoning, human_action, swiped_by, swiped_at, override_vendor_id, override_customer_id, override_account_id, duplicate_of, is_recurring, split_suggestion, status, erp_transaction_id, error_message, reconciled_at, reconciled_by, rule_group_id, created_at, updated_at, is_ambiguous, ambiguity_reason FROM fignode.staging_transactions
WHERE session_id = $1 AND status = 'PENDING_AI'
`

// =========================================================================
// Rule evaluation worker
// =========================================================================
func (q *Queries) GetPendingStagingTransactions(ctx context.Context, sessionID pgtype.UUID) ([]FignodeStagingTransaction, error) {
	rows, err := q.db.Query(ctx, getPendingStagingTransactions, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FignodeStagingTransaction
	for rows.Next() {
		var i FignodeStagingTransaction
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RealmID,
			&i.RowIndex,
			&i.SourceType,
			&i.RawDescription,
			&i.RawAmount,
			&i.RawDate,
			&i.PlaidTransactionID,
			&i.BankAccountID,
			&i.MerchantName,
			&i.LogoUrl,
			&i.PlaidCategory,
			&i.IsPending,
			&i.PredictedVendorID,
			&i.PredictedVendorName,
			&i.PredictedCustomerID,
			&i.PredictedCustomerName,
			&i.PredictedAccountID,
			&i.PredictedAccountName,
			&i.ConfidenceScore,
			&i.AiReasoning,
			&i.HumanAction,
			&i.SwipedBy,
			&i.SwipedAt,
			&i.OverrideVendorID,
			&i.OverrideCustomerID,
			&i.OverrideAccountID,
			&i.DuplicateOf,
			&i.IsRecurring,
			&i.SplitSuggestion,
			&i.Status,
			&i.ErpTransactionID,
			&i.ErrorMessage,
			&i.ReconciledAt,
			&i.ReconciledBy,
			&i.RuleGroupID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAmbiguous,
			&i.AmbiguityReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementEmployeeCleared = `-- name: IncrementEmployeeCleared :exec
UPDATE fignode.employee_profiles
SET total_cleared = total_cleared + 1,
    today_cleared = CASE
        WHEN today_cleared_date = CURRENT_DATE THEN today_cleared + 1
        ELSE 1
    END,
    today_cleared_date = CURRENT_DATE,
    updated_at = now()
WHERE user_id = $1
`

func (q *Queries) IncrementEmployeeCleared(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmployeeCleared, userID)
	return err
}

const insertLeaderboardSnapshot = `-- name: InsertLeaderboardSnapshot :exec
INSERT INTO fignode.leaderboard_snapshots (period, entries)
VALUES ($1, $2)
`

type InsertLeaderboardSnapshotParams struct {
	Period  string
	Entries []byte
}

func (q *Queries) InsertLeaderboardSnapshot(ctx context.Context, arg InsertLeaderboardSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertLeaderboardSnapshot, arg.Period, arg.Entries)
	return err
}

const insertSkip = `-- name: InsertSkip :exec


UPDATE fignode.staging_transactions
SET status = 'SKIPPED', updated_at = now()
WHERE id = $1
`

// =========================================================================
// Badges: Award & query (schema removed)
// =========================================================================
// =========================================================================
// Skip: Record a skip
// =========================================================================
func (q *Queries) InsertSkip(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertSkip, id)
	return err
}

const resetStaleStreaks = `-- name: ResetStaleStreaks :exec
UPDATE fignode.employee_profiles
SET streak = 0, updated_at = now()
WHERE streak > 0
  AND (streak_last_date IS NULL OR streak_last_date < CURRENT_DATE - INTERVAL '1 day')
`

func (q *Queries) ResetStaleStreaks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStaleStreaks)
	return err
}

const resetTodayCleared = `-- name: ResetTodayCleared :exec
UPDATE fignode.employee_profiles
SET today_cleared = 0, today_cleared_date = CURRENT_DATE, updated_at = now()
WHERE today_cleared_date IS NULL OR today_cleared_date < CURRENT_DATE
`

func (q *Queries) ResetTodayCleared(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTodayCleared)
	return err
}

const setTransactionInReview = `-- name: SetTransactionInReview :exec
UPDATE fignode.staging_transactions
SET status = 'PENDING', updated_at = now()
WHERE id = $1
`

func (q *Queries) SetTransactionInReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setTransactionInReview, id)
	return err
}

const updateStagingTransactionWithRule = `-- name: UpdateStagingTransactionWithRule :exec
UPDATE fignode.staging_transactions
SET rule_group_id = $2,
    predicted_account_id = $3,
    predicted_vendor_id = $4,
    predicted_customer_id = $5,
    status = $6,
    ai_reasoning = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateStagingTransactionWithRuleParams struct {
	ID                  pgtype.UUID
	RuleGroupID         pgtype.Int4
	PredictedAccountID  pgtype.UUID
	PredictedVendorID   pgtype.UUID
	PredictedCustomerID pgtype.UUID
	Status              string
	AiReasoning         pgtype.Text
}

func (q *Queries) UpdateStagingTransactionWithRule(ctx context.Context, arg UpdateStagingTransactionWithRuleParams) error {
	_, err := q.db.Exec(ctx, updateStagingTransactionWithRule,
		arg.ID,
		arg.RuleGroupID,
		arg.PredictedAccountID,
		arg.PredictedVendorID,
		arg.PredictedCustomerID,
		arg.Status,
		arg.AiReasoning,
	)
	return err
}

const updateStreak = `-- name: UpdateStreak :exec

UPDATE fignode.employee_profiles
SET streak = CASE
        WHEN streak_last_date IS NULL OR streak_last_date < CURRENT_DATE - INTERVAL '1 day'
            THEN 1
        WHEN streak_last_date = CURRENT_DATE - INTERVAL '1 day'
            THEN streak + 1
        ELSE streak
    END,
    streak_last_date = CURRENT_DATE,
    updated_at = now()
WHERE user_id = $1 AND (streak_last_date IS NULL OR streak_last_date < CURRENT_DATE)
`

// =========================================================================
// Streak: Update & midnight reset
// =========================================================================
func (q *Queries) UpdateStreak(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateStreak, userID)
	return err
}
