// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fignode.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustAccuracyScore = `-- name: AdjustAccuracyScore :exec
UPDATE fignode.employee_profiles
SET ai_accuracy_score = CASE
        WHEN $1::NUMERIC > 0 THEN LEAST(1.000, ai_accuracy_score + $1)
        ELSE GREATEST(0.000, ai_accuracy_score + $1)
    END,
    updated_at = now()
WHERE user_id = $2
`

type AdjustAccuracyScoreParams struct {
	Delta  pgtype.Numeric
	UserID pgtype.UUID
}

func (q *Queries) AdjustAccuracyScore(ctx context.Context, arg AdjustAccuracyScoreParams) error {
	_, err := q.db.Exec(ctx, adjustAccuracyScore, arg.Delta, arg.UserID)
	return err
}

const checkUserAlreadyClassified = `-- name: CheckUserAlreadyClassified :one
SELECT EXISTS (
    SELECT 1 FROM fignode.classifications
    WHERE transaction_id = $1 AND user_id = $2
) AS already_classified
`

type CheckUserAlreadyClassifiedParams struct {
	TransactionID string
	UserID        pgtype.UUID
}

func (q *Queries) CheckUserAlreadyClassified(ctx context.Context, arg CheckUserAlreadyClassifiedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserAlreadyClassified, arg.TransactionID, arg.UserID)
	var already_classified bool
	err := row.Scan(&already_classified)
	return already_classified, err
}

const clearTransaction = `-- name: ClearTransaction :exec

UPDATE fignode.transactions
SET status = 'cleared', cleared_at = now()
WHERE id = $1
`

// =========================================================================
// Status Updates
// =========================================================================
func (q *Queries) ClearTransaction(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearTransaction, id)
	return err
}

const computeAllTimeLeaderboard = `-- name: ComputeAllTimeLeaderboard :many

SELECT
    p.user_id,
    u.email,
    p.total_cleared AS cleared,
    p.streak
FROM fignode.employee_profiles p
JOIN toro_core.users u ON u.id = p.user_id
WHERE u.is_active = TRUE
ORDER BY p.total_cleared DESC,
         p.streak DESC,
         u.email ASC
LIMIT 100
`

type ComputeAllTimeLeaderboardRow struct {
	UserID  pgtype.UUID
	Email   string
	Cleared int32
	Streak  int32
}

// =========================================================================
// Leaderboard: Snapshot computation & retrieval
// =========================================================================
func (q *Queries) ComputeAllTimeLeaderboard(ctx context.Context) ([]ComputeAllTimeLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, computeAllTimeLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputeAllTimeLeaderboardRow
	for rows.Next() {
		var i ComputeAllTimeLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Cleared,
			&i.Streak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const computePeriodLeaderboard = `-- name: ComputePeriodLeaderboard :many
SELECT
    p.user_id,
    u.email,
    COUNT(c.id)::INT AS cleared,
    p.streak
FROM fignode.employee_profiles p
JOIN toro_core.users u ON u.id = p.user_id
LEFT JOIN fignode.classifications c
    ON c.user_id = p.user_id AND c.created_at >= $1::TIMESTAMPTZ
WHERE u.is_active = TRUE
GROUP BY p.user_id, u.email, p.streak
ORDER BY COUNT(c.id) DESC,
         p.streak DESC,
         u.email ASC
LIMIT 100
`

type ComputePeriodLeaderboardRow struct {
	UserID  pgtype.UUID
	Email   string
	Cleared int32
	Streak  int32
}

func (q *Queries) ComputePeriodLeaderboard(ctx context.Context, since pgtype.Timestamptz) ([]ComputePeriodLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, computePeriodLeaderboard, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputePeriodLeaderboardRow
	for rows.Next() {
		var i ComputePeriodLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Cleared,
			&i.Streak,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEmployeeProfile = `-- name: CreateEmployeeProfile :exec
INSERT INTO fignode.employee_profiles (user_id, first_name, last_name, is_manager)
VALUES ($1, $2, $3, $4)
`

type CreateEmployeeProfileParams struct {
	UserID    pgtype.UUID
	FirstName pgtype.Text
	LastName  pgtype.Text
	IsManager bool
}

func (q *Queries) CreateEmployeeProfile(ctx context.Context, arg CreateEmployeeProfileParams) error {
	_, err := q.db.Exec(ctx, createEmployeeProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.IsManager,
	)
	return err
}

const createEmployeeUser = `-- name: CreateEmployeeUser :one

INSERT INTO toro_core.users (entity_id, email, password_hash, role, user_type)
VALUES ($1, $2, $3, 'member', 'employee') RETURNING id
`

type CreateEmployeeUserParams struct {
	EntityID     pgtype.UUID
	Email        string
	PasswordHash string
}

// =========================================================================
// Auth: Employee Registration & Login
// =========================================================================
func (q *Queries) CreateEmployeeUser(ctx context.Context, arg CreateEmployeeUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEmployeeUser, arg.EntityID, arg.Email, arg.PasswordHash)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getBadgesByUserIDs = `-- name: GetBadgesByUserIDs :many
SELECT user_id, badge_key, badge_label
FROM fignode.badges
WHERE user_id = ANY($1::uuid[])
`

type GetBadgesByUserIDsRow struct {
	UserID     pgtype.UUID
	BadgeKey   string
	BadgeLabel string
}

func (q *Queries) GetBadgesByUserIDs(ctx context.Context, userIds []pgtype.UUID) ([]GetBadgesByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, getBadgesByUserIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBadgesByUserIDsRow
	for rows.Next() {
		var i GetBadgesByUserIDsRow
		if err := rows.Scan(&i.UserID, &i.BadgeKey, &i.BadgeLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchTransactions = `-- name: GetBatchTransactions :many

SELECT t.id, t.raw_description, t.vendor, t.industry, t.industry_icon, t.vendor_description, t.vendor_url, t.location, t.is_recurring, t.client_industry, t.client_industry_icon, t.business_model, t.mindset_hint, t.accent_color, t.accent_bg, t.amount, t.tx_date, t.account_type, t.tx_timestamp, t.ai_suggestion, t.ai_confidence, t.truth_category, t.status, t.cleared_at, t.owner_user_id, t.created_at
FROM fignode.transactions t
WHERE t.status = 'open'
  AND NOT EXISTS (
      SELECT 1 FROM fignode.classifications c
      WHERE c.transaction_id = t.id AND c.user_id = $1
  )
  AND NOT EXISTS (
      SELECT 1 FROM fignode.skips s
      WHERE s.transaction_id = t.id AND s.user_id = $1
  )
ORDER BY t.created_at ASC
LIMIT $2
`

type GetBatchTransactionsParams struct {
	UserID     pgtype.UUID
	BatchLimit int32
}

// =========================================================================
// Batch: Serving transactions to employees
// =========================================================================
func (q *Queries) GetBatchTransactions(ctx context.Context, arg GetBatchTransactionsParams) ([]FignodeTransaction, error) {
	rows, err := q.db.Query(ctx, getBatchTransactions, arg.UserID, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FignodeTransaction
	for rows.Next() {
		var i FignodeTransaction
		if err := rows.Scan(
			&i.ID,
			&i.RawDescription,
			&i.Vendor,
			&i.Industry,
			&i.IndustryIcon,
			&i.VendorDescription,
			&i.VendorUrl,
			&i.Location,
			&i.IsRecurring,
			&i.ClientIndustry,
			&i.ClientIndustryIcon,
			&i.BusinessModel,
			&i.MindsetHint,
			&i.AccentColor,
			&i.AccentBg,
			&i.Amount,
			&i.TxDate,
			&i.AccountType,
			&i.TxTimestamp,
			&i.AiSuggestion,
			&i.AiConfidence,
			&i.TruthCategory,
			&i.Status,
			&i.ClearedAt,
			&i.OwnerUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeBadges = `-- name: GetEmployeeBadges :many
SELECT badge_key, badge_label, earned_at
FROM fignode.badges
WHERE user_id = $1
ORDER BY earned_at ASC
`

type GetEmployeeBadgesRow struct {
	BadgeKey   string
	BadgeLabel string
	EarnedAt   pgtype.Timestamptz
}

func (q *Queries) GetEmployeeBadges(ctx context.Context, userID pgtype.UUID) ([]GetEmployeeBadgesRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeBadges, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmployeeBadgesRow
	for rows.Next() {
		var i GetEmployeeBadgesRow
		if err := rows.Scan(&i.BadgeKey, &i.BadgeLabel, &i.EarnedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT
    u.id,
    u.email,
    u.password_hash,
    u.entity_id,
    u.is_active,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.email = $1 AND u.user_type = 'employee'
`

type GetEmployeeByEmailRow struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EntityID        pgtype.UUID
	IsActive        pgtype.Bool
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (GetEmployeeByEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i GetEmployeeByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EntityID,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT
    u.id,
    u.email,
    u.entity_id,
    u.is_active,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.user_type = 'employee'
`

type GetEmployeeByIDRow struct {
	ID              pgtype.UUID
	Email           string
	EntityID        pgtype.UUID
	IsActive        pgtype.Bool
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeeByID(ctx context.Context, id pgtype.UUID) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EntityID,
		&i.IsActive,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeProfileForUpdate = `-- name: GetEmployeeProfileForUpdate :one

SELECT user_id, first_name, last_name, is_manager, ai_accuracy_score, streak, streak_last_date, total_cleared, today_cleared, today_cleared_date, created_at, updated_at FROM fignode.employee_profiles
WHERE user_id = $1
FOR UPDATE
`

// =========================================================================
// Updates
// =========================================================================
func (q *Queries) GetEmployeeProfileForUpdate(ctx context.Context, userID pgtype.UUID) (FignodeEmployeeProfile, error) {
	row := q.db.QueryRow(ctx, getEmployeeProfileForUpdate, userID)
	var i FignodeEmployeeProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.StreakLastDate,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.TodayClearedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeePublic = `-- name: GetEmployeePublic :one
SELECT
    u.id,
    u.email,
    p.first_name,
    p.last_name,
    p.is_manager,
    p.ai_accuracy_score,
    p.streak,
    p.total_cleared,
    p.today_cleared,
    p.created_at
FROM toro_core.users u
JOIN fignode.employee_profiles p ON p.user_id = u.id
WHERE u.id = $1 AND u.user_type = 'employee'
`

type GetEmployeePublicRow struct {
	ID              pgtype.UUID
	Email           string
	FirstName       pgtype.Text
	LastName        pgtype.Text
	IsManager       bool
	AiAccuracyScore pgtype.Numeric
	Streak          int32
	TotalCleared    int32
	TodayCleared    int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetEmployeePublic(ctx context.Context, id pgtype.UUID) (GetEmployeePublicRow, error) {
	row := q.db.QueryRow(ctx, getEmployeePublic, id)
	var i GetEmployeePublicRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.IsManager,
		&i.AiAccuracyScore,
		&i.Streak,
		&i.TotalCleared,
		&i.TodayCleared,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeStats = `-- name: GetEmployeeStats :one

SELECT
    p.total_cleared,
    p.today_cleared,
    p.streak,
    p.ai_accuracy_score
FROM fignode.employee_profiles p
WHERE p.user_id = $1
`

type GetEmployeeStatsRow struct {
	TotalCleared    int32
	TodayCleared    int32
	Streak          int32
	AiAccuracyScore pgtype.Numeric
}

// =========================================================================
// Stats: Employee dashboard
// =========================================================================
func (q *Queries) GetEmployeeStats(ctx context.Context, userID pgtype.UUID) (GetEmployeeStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeStats, userID)
	var i GetEmployeeStatsRow
	err := row.Scan(
		&i.TotalCleared,
		&i.TodayCleared,
		&i.Streak,
		&i.AiAccuracyScore,
	)
	return i, err
}

const getLatestLeaderboardSnapshot = `-- name: GetLatestLeaderboardSnapshot :one
SELECT entries, computed_at
FROM fignode.leaderboard_snapshots
WHERE period = $1
ORDER BY computed_at DESC
LIMIT 1
`

type GetLatestLeaderboardSnapshotRow struct {
	Entries    []byte
	ComputedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestLeaderboardSnapshot(ctx context.Context, period string) (GetLatestLeaderboardSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getLatestLeaderboardSnapshot, period)
	var i GetLatestLeaderboardSnapshotRow
	err := row.Scan(&i.Entries, &i.ComputedAt)
	return i, err
}

const getTransactionForClassify = `-- name: GetTransactionForClassify :one

SELECT id, raw_description, vendor, industry, industry_icon, vendor_description, vendor_url, location, is_recurring, client_industry, client_industry_icon, business_model, mindset_hint, accent_color, accent_bg, amount, tx_date, account_type, tx_timestamp, ai_suggestion, ai_confidence, truth_category, status, cleared_at, owner_user_id, created_at FROM fignode.transactions
WHERE id = $1 FOR UPDATE
`

// =========================================================================
// Classification: Categorizing transactions
// =========================================================================
func (q *Queries) GetTransactionForClassify(ctx context.Context, id string) (FignodeTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionForClassify, id)
	var i FignodeTransaction
	err := row.Scan(
		&i.ID,
		&i.RawDescription,
		&i.Vendor,
		&i.Industry,
		&i.IndustryIcon,
		&i.VendorDescription,
		&i.VendorUrl,
		&i.Location,
		&i.IsRecurring,
		&i.ClientIndustry,
		&i.ClientIndustryIcon,
		&i.BusinessModel,
		&i.MindsetHint,
		&i.AccentColor,
		&i.AccentBg,
		&i.Amount,
		&i.TxDate,
		&i.AccountType,
		&i.TxTimestamp,
		&i.AiSuggestion,
		&i.AiConfidence,
		&i.TruthCategory,
		&i.Status,
		&i.ClearedAt,
		&i.OwnerUserID,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmployeeCleared = `-- name: IncrementEmployeeCleared :exec
UPDATE fignode.employee_profiles
SET total_cleared = total_cleared + 1,
    today_cleared = CASE
        WHEN today_cleared_date = CURRENT_DATE THEN today_cleared + 1
        ELSE 1
    END,
    today_cleared_date = CURRENT_DATE,
    updated_at = now()
WHERE user_id = $1
`

func (q *Queries) IncrementEmployeeCleared(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmployeeCleared, userID)
	return err
}

const insertBatch = `-- name: InsertBatch :one
INSERT INTO fignode.batches (user_id, transaction_ids)
VALUES ($1, $2) RETURNING id
`

type InsertBatchParams struct {
	UserID         pgtype.UUID
	TransactionIds []string
}

func (q *Queries) InsertBatch(ctx context.Context, arg InsertBatchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertBatch, arg.UserID, arg.TransactionIds)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertClassification = `-- name: InsertClassification :one
INSERT INTO fignode.classifications (
    transaction_id, user_id, category, action, approved_by
) VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertClassificationParams struct {
	TransactionID string
	UserID        pgtype.UUID
	Category      string
	Action        string
	ApprovedBy    pgtype.UUID
}

func (q *Queries) InsertClassification(ctx context.Context, arg InsertClassificationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertClassification,
		arg.TransactionID,
		arg.UserID,
		arg.Category,
		arg.Action,
		arg.ApprovedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLeaderboardSnapshot = `-- name: InsertLeaderboardSnapshot :exec
INSERT INTO fignode.leaderboard_snapshots (period, entries)
VALUES ($1, $2)
`

type InsertLeaderboardSnapshotParams struct {
	Period  string
	Entries []byte
}

func (q *Queries) InsertLeaderboardSnapshot(ctx context.Context, arg InsertLeaderboardSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertLeaderboardSnapshot, arg.Period, arg.Entries)
	return err
}

const insertSkip = `-- name: InsertSkip :exec

INSERT INTO fignode.skips (transaction_id, user_id)
VALUES ($1, $2)
ON CONFLICT (transaction_id, user_id) DO NOTHING
`

type InsertSkipParams struct {
	TransactionID string
	UserID        pgtype.UUID
}

// =========================================================================
// Skip: Record a skip
// =========================================================================
func (q *Queries) InsertSkip(ctx context.Context, arg InsertSkipParams) error {
	_, err := q.db.Exec(ctx, insertSkip, arg.TransactionID, arg.UserID)
	return err
}

const resetStaleStreaks = `-- name: ResetStaleStreaks :exec
UPDATE fignode.employee_profiles
SET streak = 0, updated_at = now()
WHERE streak > 0
  AND (streak_last_date IS NULL OR streak_last_date < CURRENT_DATE - INTERVAL '1 day')
`

func (q *Queries) ResetStaleStreaks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStaleStreaks)
	return err
}

const resetTodayCleared = `-- name: ResetTodayCleared :exec
UPDATE fignode.employee_profiles
SET today_cleared = 0, today_cleared_date = CURRENT_DATE, updated_at = now()
WHERE today_cleared_date IS NULL OR today_cleared_date < CURRENT_DATE
`

func (q *Queries) ResetTodayCleared(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetTodayCleared)
	return err
}

const setTransactionInReview = `-- name: SetTransactionInReview :exec
UPDATE fignode.transactions
SET status = 'in_review'
WHERE id = $1
`

func (q *Queries) SetTransactionInReview(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setTransactionInReview, id)
	return err
}

const updateStreak = `-- name: UpdateStreak :exec

UPDATE fignode.employee_profiles
SET streak = CASE
        WHEN streak_last_date IS NULL OR streak_last_date < CURRENT_DATE - INTERVAL '1 day'
            THEN 1
        WHEN streak_last_date = CURRENT_DATE - INTERVAL '1 day'
            THEN streak + 1
        ELSE streak
    END,
    streak_last_date = CURRENT_DATE,
    updated_at = now()
WHERE user_id = $1 AND (streak_last_date IS NULL OR streak_last_date < CURRENT_DATE)
`

// =========================================================================
// Streak: Update & midnight reset
// =========================================================================
func (q *Queries) UpdateStreak(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateStreak, userID)
	return err
}

const upsertBadge = `-- name: UpsertBadge :exec

INSERT INTO fignode.badges (user_id, badge_key, badge_label)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, badge_key) DO NOTHING
`

type UpsertBadgeParams struct {
	UserID     pgtype.UUID
	BadgeKey   string
	BadgeLabel string
}

// =========================================================================
// Badges: Award & query
// =========================================================================
func (q *Queries) UpsertBadge(ctx context.Context, arg UpsertBadgeParams) error {
	_, err := q.db.Exec(ctx, upsertBadge, arg.UserID, arg.BadgeKey, arg.BadgeLabel)
	return err
}

const validateCategory = `-- name: ValidateCategory :one
SELECT EXISTS (
    SELECT 1 FROM fignode.categories WHERE label = $1
) AS is_valid
`

func (q *Queries) ValidateCategory(ctx context.Context, label string) (bool, error) {
	row := q.db.QueryRow(ctx, validateCategory, label)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
