// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fignode_industries.sql

package database

import (
	"context"
)

const getAllIndustries = `-- name: GetAllIndustries :many

SELECT name, icon_emoji FROM fignode.fignode_industries
`

type GetAllIndustriesRow struct {
	Name      string
	IconEmoji string
}

// =========================================================================
// Industries
// =========================================================================
func (q *Queries) GetAllIndustries(ctx context.Context) ([]GetAllIndustriesRow, error) {
	rows, err := q.db.Query(ctx, getAllIndustries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllIndustriesRow
	for rows.Next() {
		var i GetAllIndustriesRow
		if err := rows.Scan(&i.Name, &i.IconEmoji); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
