// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: marketing.sql

package database

import (
	"context"
)

const createLeadForm = `-- name: CreateLeadForm :one
INSERT INTO marketing.lead_forms (
    website,
    form_data
) VALUES (
    $1, $2
) RETURNING id, website, form_data, created_at, updated_at
`

type CreateLeadFormParams struct {
	Website  string
	FormData []byte
}

func (q *Queries) CreateLeadForm(ctx context.Context, arg CreateLeadFormParams) (MarketingLeadForm, error) {
	row := q.db.QueryRow(ctx, createLeadForm, arg.Website, arg.FormData)
	var i MarketingLeadForm
	err := row.Scan(
		&i.ID,
		&i.Website,
		&i.FormData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
