// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FignodeEmployeeProfile struct {
	UserID           pgtype.UUID
	FirstName        pgtype.Text
	LastName         pgtype.Text
	IsManager        bool
	AiAccuracyScore  pgtype.Numeric
	Streak           int32
	StreakLastDate   pgtype.Date
	TotalCleared     int32
	TodayCleared     int32
	TodayClearedDate pgtype.Date
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FignodeFignodeIndustry struct {
	Name      string
	IconEmoji string
	UpdatedAt pgtype.Timestamptz
}

type FignodeLeaderboardSnapshot struct {
	ID         pgtype.UUID
	Period     string
	ComputedAt pgtype.Timestamptz
	Entries    []byte
}

type FignodeStagingSession struct {
	ID              pgtype.UUID
	RealmID         pgtype.Text
	CreatedBy       pgtype.UUID
	FileName        pgtype.Text
	RowCount        int32
	Status          string
	IsAmbiguous     bool
	AmbiguityReason pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type FignodeStagingTransaction struct {
	ID                    pgtype.UUID
	SessionID             pgtype.UUID
	RealmID               pgtype.Text
	RowIndex              pgtype.Int4
	SourceType            string
	RawDescription        pgtype.Text
	RawAmount             string
	RawDate               pgtype.Date
	PlaidTransactionID    pgtype.Text
	BankAccountID         pgtype.Text
	MerchantName          pgtype.Text
	LogoUrl               pgtype.Text
	PlaidCategory         pgtype.Text
	IsPending             pgtype.Bool
	PredictedVendorID     pgtype.UUID
	PredictedVendorName   pgtype.Text
	PredictedCustomerID   pgtype.UUID
	PredictedCustomerName pgtype.Text
	PredictedAccountID    pgtype.UUID
	PredictedAccountName  pgtype.Text
	ConfidenceScore       pgtype.Numeric
	AiReasoning           pgtype.Text
	HumanAction           pgtype.Text
	SwipedBy              pgtype.UUID
	SwipedAt              pgtype.Timestamptz
	OverrideVendorID      pgtype.UUID
	OverrideCustomerID    pgtype.UUID
	OverrideAccountID     pgtype.UUID
	DuplicateOf           pgtype.UUID
	IsRecurring           bool
	SplitSuggestion       []byte
	Status                string
	ErpTransactionID      pgtype.Text
	ErrorMessage          pgtype.Text
	ReconciledAt          pgtype.Timestamptz
	ReconciledBy          pgtype.UUID
	RuleGroupID           pgtype.Int4
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	IsAmbiguous           bool
	AmbiguityReason       pgtype.Text
}

type MarketingLeadForm struct {
	ID        pgtype.UUID
	Website   string
	FormData  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ShadowErpAccount struct {
	ID                            pgtype.UUID
	ErpID                         string
	RealmID                       string
	Name                          string
	AccountType                   string
	AccountSubType                pgtype.Text
	Classification                pgtype.Text
	FullyQualifiedName            pgtype.Text
	Active                        pgtype.Bool
	SyncToken                     string
	Domain                        pgtype.Text
	CurrencyRefName               pgtype.Text
	CurrencyRefValue              pgtype.Text
	CurrentBalanceWithSubAccounts pgtype.Numeric
	Sparse                        pgtype.Bool
	ErpCreatedTime                pgtype.Timestamptz
	ErpUpdatedTime                pgtype.Timestamptz
	CurrentBalance                pgtype.Numeric
	SubAccount                    pgtype.Bool
	EventSource                   string
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	DeletedAt                     pgtype.Timestamptz
}

// Records when users correct AI predictions for learning and synonym updates
type ShadowErpAiCorrection struct {
	ID      pgtype.UUID
	RealmID string
	UserID  pgtype.UUID
	// The original text that AI tried to match
	RawInput     string
	AiPrediction pgtype.Text
	// The correct entity ID provided by user
	UserCorrection  string
	CorrectionType  string
	ConfidenceScore pgtype.Numeric
	EventSource     string
	CreatedAt       pgtype.Timestamptz
}

type ShadowErpAttachable struct {
	ID             pgtype.UUID
	RealmID        string
	ErpID          string
	FileName       pgtype.Text
	ContentType    pgtype.Text
	Size           pgtype.Numeric
	Note           pgtype.Text
	AttachableRefs []byte
	SyncToken      pgtype.Text
	ErpCreatedTime pgtype.Timestamptz
	ErpUpdatedTime pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ShadowErpBill struct {
	ID          pgtype.UUID
	ErpID       string
	RealmID     string
	VendorID    pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	EventSource string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

// Mirror of QBO CompanyInfo; keyed by realm_id. One row per connected QBO company.
type ShadowErpCompanyInfo struct {
	ID                   pgtype.UUID
	RealmID              string
	ErpID                string
	SyncToken            string
	CompanyName          string
	LegalName            pgtype.Text
	Domain               pgtype.Text
	Country              pgtype.Text
	FiscalYearStartMonth pgtype.Text
	CompanyStartDate     pgtype.Date
	SupportedLanguages   pgtype.Text
	CompanyAddr          []byte
	LegalAddr            []byte
	PrimaryPhone         pgtype.Text
	Email                pgtype.Text
	WebAddr              pgtype.Text
	NameValues           []byte
	EventSource          string
	ErpCreatedTime       pgtype.Timestamptz
	ErpUpdatedTime       pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Industry             pgtype.Text
	IndustryIcon         pgtype.Text
	BusinessModel        pgtype.Text
	MindsetHint          pgtype.Text
}

type ShadowErpCustomer struct {
	ID                  pgtype.UUID
	ErpID               string
	RealmID             string
	DisplayName         string
	SyncToken           string
	EventSource         string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	Industry            pgtype.Text
	IndustryIcon        pgtype.Text
	CustomerDescription pgtype.Text
	CustomerUrl         pgtype.Text
}

type ShadowErpDeposit struct {
	ID              pgtype.UUID
	ErpID           string
	RealmID         string
	SyncToken       string
	TxnDate         pgtype.Date
	TotalAmount     pgtype.Numeric
	TargetAccountID string
	Lines           []byte
	Domain          pgtype.Text
	Sparse          pgtype.Bool
	ErpCreatedTime  pgtype.Timestamptz
	ErpUpdatedTime  pgtype.Timestamptz
	RuleID          pgtype.Int4
	EventSource     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ShadowErpInvoice struct {
	ID          pgtype.UUID
	ErpID       string
	RealmID     string
	CustomerID  pgtype.UUID
	DocNumber   pgtype.Text
	TotalAmount pgtype.Numeric
	Balance     pgtype.Numeric
	DueDate     pgtype.Date
	TxnDate     pgtype.Date
	SyncToken   string
	EventSource string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ShadowErpPurchase struct {
	ID              pgtype.UUID
	ErpID           string
	RealmID         string
	SyncToken       string
	TxnDate         pgtype.Date
	TotalAmount     pgtype.Numeric
	PaymentType     pgtype.Text
	SourceAccountID string
	EntityID        pgtype.Text
	Lines           []byte
	RuleID          pgtype.Int4
	EventSource     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type ShadowErpRuleAuditLog struct {
	ID            int32
	RealmID       string
	TransactionID pgtype.UUID
	RuleGroupID   pgtype.Int4
	Matched       bool
	// Verbose match explanation: JSON containing condition-level results (maps to MatchExplanation struct)
	MatchInfo           []byte
	HumanReadableReason string
	CreatedAt           pgtype.Timestamptz
}

type ShadowErpRuleCondition struct {
	ID          int32
	RuleGroupID int32
	Field       string
	Operator    string
	Value       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ShadowErpRuleGroup struct {
	ID             int32
	RealmID        string
	Name           string
	Logic          string
	Priority       int32
	Keywords       pgtype.Text
	Active         bool
	TargetEntityID pgtype.UUID
	Allocations    []byte
	Direction      string
	RequiresReview bool
	ParentID       pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Tracks Pinecone vector database sync state per ERP realm
type ShadowErpVectorSyncState struct {
	RealmID string
	// Last Chart of Accounts sync to Pinecone
	LastCoaSync      pgtype.Timestamptz
	LastVendorSync   pgtype.Timestamptz
	LastCustomerSync pgtype.Timestamptz
	// Number of account vectors in Pinecone
	CoaVectorCount      pgtype.Int4
	VendorVectorCount   pgtype.Int4
	CustomerVectorCount pgtype.Int4
	EventSource         string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ShadowErpVendor struct {
	ID                 pgtype.UUID
	ErpID              string
	RealmID            string
	DisplayName        string
	SyncToken          string
	LastKnownAccountID pgtype.UUID
	AiSynonyms         []byte
	EventSource        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Industry           pgtype.Text
	IndustryIcon       pgtype.Text
	VendorDescription  pgtype.Text
	VendorUrl          pgtype.Text
}

type ToroCoreAgentMemoryRule struct {
	ID          pgtype.UUID
	RealmID     string
	EntityType  string
	EntityValue string
	Instruction string
	Source      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type ToroCoreAgentPerformanceHourly struct {
	Bucket        interface{}
	AgentID       interface{}
	TotalTasks    int64
	AvgConfidence float64
	TotalCost     int64
}

type ToroCoreEntity struct {
	ID          pgtype.UUID
	ParentID    pgtype.UUID
	Name        string
	EntityType  string
	ErpProvider pgtype.Text
	ErpTenantID pgtype.Text
	PlanTier    pgtype.Text
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ToroCoreErpConnection struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	ErpSystem    string
	RealmID      string
	AccessToken  string
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	// Timestamp of last successful CDC sync. Used as changedSince parameter for CDC API calls. Max lookback is 30 days per QBO limits.
	LastSyncTimestamp pgtype.Timestamptz
	// Timestamp of last successful Account webhook. Used by CDC to fetch only missed events.
	LastWebhookAccount pgtype.Timestamptz
	// Timestamp of last successful Vendor webhook. Used by CDC to fetch only missed events.
	LastWebhookVendor pgtype.Timestamptz
	// Timestamp of last successful Customer webhook. Used by CDC to fetch only missed events.
	LastWebhookCustomer pgtype.Timestamptz
	// Timestamp of last successful Invoice webhook. Used by CDC to fetch only missed events.
	LastWebhookInvoice pgtype.Timestamptz
	// Timestamp of last successful Bill webhook. Used by CDC to fetch only missed events.
	LastWebhookBill pgtype.Timestamptz
	// Timestamp of last successful Purchase/Transaction webhook. Used by CDC to fetch only missed events.
	LastWebhookTransaction pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	LastWebhookDeposit     pgtype.Timestamptz
}

type ToroCoreRefreshToken struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type ToroCoreStalledMessage struct {
	ID              pgtype.UUID
	AgentDid        string
	OriginalSubject string
	Payload         []byte
	ErrorReason     string
	CreatedAt       pgtype.Timestamptz
}

type ToroCoreTeamInvite struct {
	ID        pgtype.UUID
	Token     string
	Email     string
	TenantID  string
	FirmName  string
	IsUsed    bool
	CreatedAt pgtype.Timestamptz
}

type ToroCoreTelemetryEvent struct {
	Time       pgtype.Timestamptz
	TraceID    pgtype.UUID
	EntityID   pgtype.UUID
	Service    string
	EventType  string
	DurationMs pgtype.Int4
	Meta       []byte
}

type ToroCoreTransaction struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	ExternalID   string
	AmountMicros int64
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ToroCoreUser struct {
	ID           pgtype.UUID
	EntityID     pgtype.UUID
	Email        string
	PasswordHash string
	FullName     pgtype.Text
	Role         pgtype.Text
	UserType     string
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreWallet struct {
	ID                     pgtype.UUID
	EntityID               pgtype.UUID
	TotalPurchasedMicrions int64
	TotalBurnedMicrions    int64
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ToroCoreWalletTransaction struct {
	ID              pgtype.UUID
	WalletID        pgtype.UUID
	TransactionType string
	MicrionAmount   int64
	UsdAmount       pgtype.Int8
	StripeSessionID pgtype.Text
	NatsRevision    pgtype.Int8
	CreatedAt       pgtype.Timestamptz
}

type ToroCoreWebhooksProviderconnection struct {
	ID            pgtype.UUID
	ConnectionID  string
	WebhookSecret string
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ToroCoreWorkflow struct {
	ID         pgtype.UUID
	EntityID   pgtype.UUID
	State      []byte
	SequenceID int64
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ToroCoreWorkflowBlueprint struct {
	Name         string
	TriggerTopic string
	Definition   []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ToroCoreWorkflowHistory struct {
	ID         pgtype.UUID
	WorkflowID pgtype.UUID
	Role       string
	Content    []byte
	CreatedAt  pgtype.Timestamptz
}
