// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Status    pgtype.Text
	PlanTier  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Transaction struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	ExternalID   string
	AmountMicros int64
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WebhookksProviderconnection struct {
	ID            pgtype.UUID
	ConnectionID  string
	WebhookSecret string
	IsActive      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
