// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stalled_messages.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStalledMessage = `-- name: DeleteStalledMessage :exec
DELETE FROM toro_core.stalled_messages WHERE id = $1
`

func (q *Queries) DeleteStalledMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStalledMessage, id)
	return err
}

const getStalledMessagesByAgent = `-- name: GetStalledMessagesByAgent :many
SELECT id, agent_did, original_subject, payload, error_reason, created_at FROM toro_core.stalled_messages
WHERE agent_did = $1
ORDER BY created_at ASC
`

func (q *Queries) GetStalledMessagesByAgent(ctx context.Context, agentDid string) ([]ToroCoreStalledMessage, error) {
	rows, err := q.db.Query(ctx, getStalledMessagesByAgent, agentDid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToroCoreStalledMessage
	for rows.Next() {
		var i ToroCoreStalledMessage
		if err := rows.Scan(
			&i.ID,
			&i.AgentDid,
			&i.OriginalSubject,
			&i.Payload,
			&i.ErrorReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logStalledMessage = `-- name: LogStalledMessage :one
INSERT INTO toro_core.stalled_messages (
    agent_did, original_subject, payload, error_reason
) VALUES (
    $1, $2, $3, $4
) RETURNING id, agent_did, original_subject, payload, error_reason, created_at
`

type LogStalledMessageParams struct {
	AgentDid        string
	OriginalSubject string
	Payload         []byte
	ErrorReason     string
}

func (q *Queries) LogStalledMessage(ctx context.Context, arg LogStalledMessageParams) (ToroCoreStalledMessage, error) {
	row := q.db.QueryRow(ctx, logStalledMessage,
		arg.AgentDid,
		arg.OriginalSubject,
		arg.Payload,
		arg.ErrorReason,
	)
	var i ToroCoreStalledMessage
	err := row.Scan(
		&i.ID,
		&i.AgentDid,
		&i.OriginalSubject,
		&i.Payload,
		&i.ErrorReason,
		&i.CreatedAt,
	)
	return i, err
}
