// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: toro_threads_mappings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createThreadMapping = `-- name: CreateThreadMapping :exec
INSERT INTO toro_core.toro_threads_mappings (conversation_id, tenant_id, slack_channel_id, slack_parent_ts, email_latest_message_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateThreadMappingParams struct {
	ConversationID       pgtype.UUID
	TenantID             pgtype.UUID
	SlackChannelID       string
	SlackParentTs        string
	EmailLatestMessageID string
}

func (q *Queries) CreateThreadMapping(ctx context.Context, arg CreateThreadMappingParams) error {
	_, err := q.db.Exec(ctx, createThreadMapping,
		arg.ConversationID,
		arg.TenantID,
		arg.SlackChannelID,
		arg.SlackParentTs,
		arg.EmailLatestMessageID,
	)
	return err
}

const getThreadMappingByEmailMessageID = `-- name: GetThreadMappingByEmailMessageID :one
SELECT id, conversation_id, tenant_id, slack_channel_id, slack_parent_ts, email_latest_message_id, created_at, updated_at FROM toro_core.toro_threads_mappings
WHERE email_latest_message_id = $1
`

func (q *Queries) GetThreadMappingByEmailMessageID(ctx context.Context, emailLatestMessageID string) (ToroCoreToroThreadsMapping, error) {
	row := q.db.QueryRow(ctx, getThreadMappingByEmailMessageID, emailLatestMessageID)
	var i ToroCoreToroThreadsMapping
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.TenantID,
		&i.SlackChannelID,
		&i.SlackParentTs,
		&i.EmailLatestMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadMappingBySlackTS = `-- name: GetThreadMappingBySlackTS :one
SELECT id, conversation_id, tenant_id, slack_channel_id, slack_parent_ts, email_latest_message_id, created_at, updated_at FROM toro_core.toro_threads_mappings
WHERE slack_channel_id = $1 AND slack_parent_ts = $2
`

type GetThreadMappingBySlackTSParams struct {
	SlackChannelID string
	SlackParentTs  string
}

func (q *Queries) GetThreadMappingBySlackTS(ctx context.Context, arg GetThreadMappingBySlackTSParams) (ToroCoreToroThreadsMapping, error) {
	row := q.db.QueryRow(ctx, getThreadMappingBySlackTS, arg.SlackChannelID, arg.SlackParentTs)
	var i ToroCoreToroThreadsMapping
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.TenantID,
		&i.SlackChannelID,
		&i.SlackParentTs,
		&i.EmailLatestMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThreadMappingEmailMessageID = `-- name: UpdateThreadMappingEmailMessageID :exec
UPDATE toro_core.toro_threads_mappings
SET email_latest_message_id = $1, updated_at = NOW()
WHERE slack_channel_id = $2 AND slack_parent_ts = $3
`

type UpdateThreadMappingEmailMessageIDParams struct {
	EmailLatestMessageID string
	SlackChannelID       string
	SlackParentTs        string
}

func (q *Queries) UpdateThreadMappingEmailMessageID(ctx context.Context, arg UpdateThreadMappingEmailMessageIDParams) error {
	_, err := q.db.Exec(ctx, updateThreadMappingEmailMessageID, arg.EmailLatestMessageID, arg.SlackChannelID, arg.SlackParentTs)
	return err
}
