// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package database

import (
	"context"
)

const getWebhookSecret = `-- name: GetWebhookSecret :one
SELECT webhook_secret 
FROM webhooks_providerconnection 
WHERE connection_id = $1 AND is_active = true
`

func (q *Queries) GetWebhookSecret(ctx context.Context, connectionID string) (string, error) {
	row := q.db.QueryRow(ctx, getWebhookSecret, connectionID)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const upsertWebhookSecret = `-- name: UpsertWebhookSecret :exec
INSERT INTO webhooks_providerconnection (connection_id, webhook_secret, is_active)
VALUES ($1, $2, true)
ON CONFLICT (connection_id) 
DO UPDATE SET 
    webhook_secret = $2, 
    updated_at = NOW()
`

type UpsertWebhookSecretParams struct {
	ConnectionID  string
	WebhookSecret string
}

func (q *Queries) UpsertWebhookSecret(ctx context.Context, arg UpsertWebhookSecretParams) error {
	_, err := q.db.Exec(ctx, upsertWebhookSecret, arg.ConnectionID, arg.WebhookSecret)
	return err
}
