// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrGetWorkflow = `-- name: CreateOrGetWorkflow :one
INSERT INTO toro_core.workflows (id, entity_id, state)
VALUES ($1, $2, '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET updated_at = NOW()
RETURNING id, entity_id, state, sequence_id, status, created_at, updated_at
`

type CreateOrGetWorkflowParams struct {
	ID       pgtype.UUID
	EntityID pgtype.UUID
}

func (q *Queries) CreateOrGetWorkflow(ctx context.Context, arg CreateOrGetWorkflowParams) (ToroCoreWorkflow, error) {
	row := q.db.QueryRow(ctx, createOrGetWorkflow, arg.ID, arg.EntityID)
	var i ToroCoreWorkflow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.State,
		&i.SequenceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflowBlueprint = `-- name: DeleteWorkflowBlueprint :exec
DELETE FROM toro_core.workflow_blueprints
WHERE name = $1
`

func (q *Queries) DeleteWorkflowBlueprint(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteWorkflowBlueprint, name)
	return err
}

const getBlueprintByName = `-- name: GetBlueprintByName :one
SELECT name, trigger_topic, definition, created_at, updated_at
FROM toro_core.workflow_blueprints
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetBlueprintByName(ctx context.Context, name string) (ToroCoreWorkflowBlueprint, error) {
	row := q.db.QueryRow(ctx, getBlueprintByName, name)
	var i ToroCoreWorkflowBlueprint
	err := row.Scan(
		&i.Name,
		&i.TriggerTopic,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlueprintByNameOrTriggerTopic = `-- name: GetBlueprintByNameOrTriggerTopic :one
SELECT name, trigger_topic, definition, created_at, updated_at
FROM toro_core.workflow_blueprints
WHERE name = $1 OR trigger_topic = $1
LIMIT 1
`

func (q *Queries) GetBlueprintByNameOrTriggerTopic(ctx context.Context, name string) (ToroCoreWorkflowBlueprint, error) {
	row := q.db.QueryRow(ctx, getBlueprintByNameOrTriggerTopic, name)
	var i ToroCoreWorkflowBlueprint
	err := row.Scan(
		&i.Name,
		&i.TriggerTopic,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, entity_id, state, sequence_id, status, created_at, updated_at FROM toro_core.workflows WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (ToroCoreWorkflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i ToroCoreWorkflow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.State,
		&i.SequenceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowBlueprints = `-- name: GetWorkflowBlueprints :many
SELECT name, trigger_topic, definition, created_at, updated_at
FROM toro_core.workflow_blueprints
ORDER BY name
`

func (q *Queries) GetWorkflowBlueprints(ctx context.Context) ([]ToroCoreWorkflowBlueprint, error) {
	rows, err := q.db.Query(ctx, getWorkflowBlueprints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToroCoreWorkflowBlueprint
	for rows.Next() {
		var i ToroCoreWorkflowBlueprint
		if err := rows.Scan(
			&i.Name,
			&i.TriggerTopic,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logWorkflowHistory = `-- name: LogWorkflowHistory :one
INSERT INTO toro_core.workflow_history (workflow_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, role, content, created_at
`

type LogWorkflowHistoryParams struct {
	WorkflowID pgtype.UUID
	Role       string
	Content    []byte
}

func (q *Queries) LogWorkflowHistory(ctx context.Context, arg LogWorkflowHistoryParams) (ToroCoreWorkflowHistory, error) {
	row := q.db.QueryRow(ctx, logWorkflowHistory, arg.WorkflowID, arg.Role, arg.Content)
	var i ToroCoreWorkflowHistory
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkflowState = `-- name: UpdateWorkflowState :one
UPDATE toro_core.workflows
SET state = $1, sequence_id = $2, updated_at = NOW()
WHERE id = $3
RETURNING id, entity_id, state, sequence_id, status, created_at, updated_at
`

type UpdateWorkflowStateParams struct {
	State      []byte
	SequenceID int64
	ID         pgtype.UUID
}

func (q *Queries) UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) (ToroCoreWorkflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflowState, arg.State, arg.SequenceID, arg.ID)
	var i ToroCoreWorkflow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.State,
		&i.SequenceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkflowBlueprint = `-- name: UpsertWorkflowBlueprint :one

INSERT INTO toro_core.workflow_blueprints (name, trigger_topic, definition)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET trigger_topic = EXCLUDED.trigger_topic,
    definition    = EXCLUDED.definition,
    updated_at    = NOW()
RETURNING name, trigger_topic, definition, created_at, updated_at
`

type UpsertWorkflowBlueprintParams struct {
	Name         string
	TriggerTopic string
	Definition   []byte
}

// =========================================================================
// Workflow Blueprints (declarative definitions)
// =========================================================================
func (q *Queries) UpsertWorkflowBlueprint(ctx context.Context, arg UpsertWorkflowBlueprintParams) (ToroCoreWorkflowBlueprint, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowBlueprint, arg.Name, arg.TriggerTopic, arg.Definition)
	var i ToroCoreWorkflowBlueprint
	err := row.Scan(
		&i.Name,
		&i.TriggerTopic,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
