package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/Yankzy/usetoro/cmd/graphql/graph/model"
	"github.com/Yankzy/usetoro/internal/auth"
	"github.com/Yankzy/usetoro/internal/config"
	"github.com/Yankzy/usetoro/internal/connectors"
	"github.com/Yankzy/usetoro/internal/database"
	quickbooks "github.com/Yankzy/usetoro/qbo"
	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthPayload, error) {
	// Start Transaction
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		r.Logger.Error("Failed to start transaction", "error", err)
		return nil, fmt.Errorf("internal server error")
	}
	defer tx.Rollback(ctx)

	q := database.New(r.DB).WithTx(tx)

	// 1. Create Entity (replaces old Tenant)
	entityID, err := q.CreateEntity(ctx, database.CreateEntityParams{
		Name:       input.OrgName,
		EntityType: "client",
		PlanTier:   pgtype.Text{String: "pro", Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to create entity", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 2. Create User
	pwdHash := hashPassword(input.Password)
	userID, err := q.CreateUser(ctx, database.CreateUserParams{
		EntityID:     entityID,
		Email:        input.Email,
		PasswordHash: pwdHash,
		Role:         pgtype.Text{String: "owner", Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to create user", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 3. Generate Tokens
	user := database.ToroCoreUser{
		ID:       userID,
		EntityID: entityID,
		Role:     pgtype.Text{String: "owner", Valid: true},
	}
	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Save Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    userID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 5. Store Refresh Token in Redis (for caching/blacklisting)
	err = r.Redis.Set(ctx, "refresh_token:"+ref, userID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache refresh token in Redis", "error", err)
		// Proceed anyway, DB is source of truth
	}

	if err := tx.Commit(ctx); err != nil {
		r.Logger.Error("Failed to commit transaction", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userID.String(),
			Email:    input.Email,
			Role:     "owner",
			TenantID: entityID.String(),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	q := database.New(r.DB)

	user, err := q.GetUserByEmail(ctx, input.Email)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("invalid credentials")
		}
		r.Logger.Error("Failed to fetch user", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	if !checkPassword(input.Password, user.PasswordHash) {
		return nil, fmt.Errorf("invalid credentials")
	}

	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Save Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    user.ID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Store Refresh Token in Redis
	err = r.Redis.Set(ctx, "refresh_token:"+ref, user.ID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache refresh token in Redis", "error", err)
	}

	// Convert UUIDs to strings
	userIDStr := uuid.UUID(user.ID.Bytes).String()
	entityIDStr := uuid.UUID(user.EntityID.Bytes).String()

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userIDStr,
			Email:    user.Email,
			Role:     user.Role.String,
			TenantID: entityIDStr,
		},
	}, nil
}

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, email string) (bool, error) {
	panic(fmt.Errorf("not implemented: RequestOtp - requestOTP"))
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: VerifyOtp - verifyOTP"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	q := database.New(r.DB)

	// 1. Get Refresh Token
	tokenRec, err := q.GetRefreshToken(ctx, refreshToken)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("invalid refresh token")
		}
		r.Logger.Error("Failed to fetch refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 2. Check Expiry
	if tokenRec.ExpiresAt.Valid && tokenRec.ExpiresAt.Time.Before(time.Now()) {
		// Cleanup expired token
		_ = q.DeleteRefreshToken(ctx, refreshToken)
		return nil, fmt.Errorf("refresh token expired")
	}

	// 3. Get User
	user, err := q.GetUserByID(ctx, tokenRec.UserID)
	if err != nil {
		r.Logger.Error("Failed to fetch user for refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Generate New Tokens (Rotation)
	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 5. Delete Old Token (Rotation)
	// We do this BEFORE saving the new one to prevent reuse race conditions,
	// though in a transaction would be better. For now simple deletion is fine.
	err = q.DeleteRefreshToken(ctx, refreshToken)
	if err != nil {
		r.Logger.Warn("Failed to delete old refresh token from DB during rotation", "error", err)
	}
	// Also delete from Redis
	r.Redis.Del(ctx, "refresh_token:"+refreshToken)

	// 6. Save New Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    user.ID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save new refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 7. Store new token in Redis
	err = r.Redis.Set(ctx, "refresh_token:"+ref, user.ID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache new refresh token in Redis", "error", err)
	}

	// Return Payload
	userIDStr := uuid.UUID(user.ID.Bytes).String()
	entityIDStr := uuid.UUID(user.EntityID.Bytes).String()

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userIDStr,
			Email:    user.Email,
			Role:     user.Role.String,
			TenantID: entityIDStr,
		},
	}, nil
}

// DeleteToken is the resolver for the deleteToken field.
func (r *mutationResolver) DeleteToken(ctx context.Context, refreshToken string) (bool, error) {
	q := database.New(r.DB)

	// 1. Delete from DB
	err := q.DeleteRefreshToken(ctx, refreshToken)
	if err != nil {
		r.Logger.Error("Failed to delete refresh token from DB", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	// 2. Delete from Redis
	err = r.Redis.Del(ctx, "refresh_token:"+refreshToken).Err()
	if err != nil {
		r.Logger.Warn("Failed to delete refresh token from Redis", "error", err)
		// Not critical, eventually it will expire
	}

	return true, nil
}

// RecordCorrection is the resolver for the recordCorrection field.
func (r *mutationResolver) RecordCorrection(ctx context.Context, input model.RecordCorrectionInput) (bool, error) {
	userID, _ := ctx.Value(auth.UserIDKey).(uuid.UUID)
	// userID can be nil for anonymous corrections if supported, but here we expect it

	q := database.New(r.DB)

	conf := pgtype.Numeric{}
	if input.ConfidenceScore != nil {
		conf.Scan(fmt.Sprintf("%f", *input.ConfidenceScore))
	}

	err := q.RecordAICorrection(ctx, database.RecordAICorrectionParams{
		RealmID:         input.RealmID,
		UserID:          pgtype.UUID{Bytes: userID, Valid: userID != uuid.Nil},
		RawInput:        input.RawInput,
		AiPrediction:    pgtype.Text{String: *input.AiPrediction, Valid: input.AiPrediction != nil},
		UserCorrection:  input.UserCorrection,
		CorrectionType:  input.CorrectionType,
		ConfidenceScore: conf,
	})
	if err != nil {
		r.Logger.Error("Failed to record AI correction", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	// Active Learning: Update synonyms for better future matching
	if r.EntityResolver != nil {
		go func() {
			// Use background context to not block the response
			bgCtx := context.Background()
			if err := r.EntityResolver.Learn(bgCtx, input.RealmID, input.RawInput, input.UserCorrection, input.CorrectionType); err != nil {
				r.Logger.Warn("Failed to learn from correction", "error", err, "raw_input", input.RawInput)
			}
		}()
	}

	return true, nil
}

// SyncQboChartOfAccounts is the resolver for the syncQboChartOfAccounts field.
func (r *mutationResolver) SyncQboChartOfAccounts(ctx context.Context, realmID string) (int32, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return 0, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		if err == pgx.ErrNoRows {
			return 0, fmt.Errorf("no qbo connection")
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return 0, fmt.Errorf("internal server error")
	}

	if conn.RealmID != realmID {
		return 0, fmt.Errorf("unauthorized")
	}

	clientID := os.Getenv("QBO_CLIENT_ID")
	clientSecret := os.Getenv("QBO_CLIENT_SECRET")
	if clientID == "" || clientSecret == "" {
		return 0, fmt.Errorf("qbo client credentials not configured")
	}

	isProd := strings.EqualFold(os.Getenv("QBO_IS_PRODUCTION"), "true")
	cfg := &config.Config{
		QBOClientID:     clientID,
		QBOClientSecret: clientSecret,
		QBOIsProduction: isProd,
	}

	qboConn := connectors.NewQBOConnector(r.Logger, cfg, r.Store, nil)
	count, err := qboConn.SyncFullChartOfAccounts(ctx, entityID.String(), realmID)
	if err != nil {
		r.Logger.Error("Full CoA sync failed", "error", err, "realm_id", realmID)
		return 0, fmt.Errorf("sync failed")
	}

	return int32(count), nil
}

// CreateQboAccount is the resolver for the createQboAccount field.
func (r *mutationResolver) CreateQboAccount(ctx context.Context, input model.CreateQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	qboAccount := &quickbooks.Account{
		Name:        input.Name,
		AccountType: input.AccountType,
	}
	if input.AccountSubType != nil {
		qboAccount.AccountSubType = *input.AccountSubType
	}
	if input.Classification != nil {
		qboAccount.Classification = *input.Classification
	}
	if input.Description != nil {
		qboAccount.Description = *input.Description
	}
	if input.Active != nil {
		qboAccount.Active = *input.Active
	} else {
		qboAccount.Active = true // QBO accounts are active by default
	}
	if input.SubAccount != nil {
		qboAccount.SubAccount = *input.SubAccount
	}
	if input.ParentRefValue != nil {
		qboAccount.ParentRef = quickbooks.ReferenceType{Value: *input.ParentRefValue}
	}
	if input.CurrencyRefValue != nil {
		qboAccount.CurrencyRef = quickbooks.ReferenceType{Value: *input.CurrencyRefValue}
	}

	created, err := qboConn.CreateAccount(ctx, entityID.String(), input.RealmID, qboAccount)
	if err != nil {
		r.Logger.Error("Failed to create QBO account", "error", err, "realm_id", input.RealmID)
		return nil, fmt.Errorf("failed to create account")
	}

	// Fetch from DB to return
	dbAccount, err := r.Store.Queries.GetAccountByQBOID(ctx, database.GetAccountByQBOIDParams{
		RealmID: input.RealmID,
		QboID:   created.Id,
	})
	if err != nil {
		r.Logger.Error("Failed to fetch created QBO account from shadow db", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// UpdateQboAccount is the resolver for the updateQboAccount field.
func (r *mutationResolver) UpdateQboAccount(ctx context.Context, input model.UpdateQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	uid, err := uuid.Parse(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id format")
	}

	var qboID string
	err = r.DB.QueryRow(ctx, "SELECT qbo_id FROM shadow_erp.accounts WHERE id = $1 AND realm_id = $2 AND deleted_at IS NULL", uid, input.RealmID).Scan(&qboID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("account not found")
		}
		r.Logger.Error("Failed to fetch QBO ID for account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	qboAccount := &quickbooks.Account{
		Id: qboID,
	}
	if input.Name != nil {
		qboAccount.Name = *input.Name
	}
	if input.AccountType != nil {
		qboAccount.AccountType = *input.AccountType
	}
	if input.AccountSubType != nil {
		qboAccount.AccountSubType = *input.AccountSubType
	}
	if input.Description != nil {
		qboAccount.Description = *input.Description
	}
	if input.Active != nil {
		qboAccount.Active = *input.Active
	} else {
		// Do not set false, UpdateAccount uses sparse which omits false unless explicitly sent.
		// Wait, omitempty on Active bool means we can't send Active: false here.
		// That's why we have DeactivateAccount for explicitly setting active=false.
		// For update, if Active is true, we set it. The user shouldn't pass false to Update if we have SoftDelete!
	}

	updated, err := qboConn.UpdateAccount(ctx, entityID.String(), input.RealmID, qboAccount)
	if err != nil {
		r.Logger.Error("Failed to update QBO account", "error", err, "realm_id", input.RealmID)
		return nil, err
	}

	dbAccount, err := r.Store.Queries.GetAccountByQBOID(ctx, database.GetAccountByQBOIDParams{
		RealmID: input.RealmID,
		QboID:   updated.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated account")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// SoftDeleteQboAccount is the resolver for the softDeleteQboAccount field.
func (r *mutationResolver) SoftDeleteQboAccount(ctx context.Context, input model.SoftDeleteQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	uid, err := uuid.Parse(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id format")
	}

	var qboID string
	err = r.DB.QueryRow(ctx, "SELECT qbo_id FROM shadow_erp.accounts WHERE id = $1 AND realm_id = $2", uid, input.RealmID).Scan(&qboID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("account not found")
		}
		r.Logger.Error("Failed to fetch QBO ID for account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	deactivated, err := qboConn.SoftDeleteAccount(ctx, entityID.String(), input.RealmID, qboID)
	if err != nil {
		r.Logger.Error("Failed to deactivate QBO account", "error", err, "realm_id", input.RealmID)
		return nil, err
	}

	dbAccount, err := r.Store.Queries.GetAccountByQBOID(ctx, database.GetAccountByQBOIDParams{
		RealmID: input.RealmID,
		QboID:   deactivated.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch deactivated account")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	// Extract userID from context (requires auth middleware)
	userID, ok := ctx.Value(auth.UserIDKey).(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	// Use Data Loader
	// We need to import `github.com/Yankzy/usetoro/cmd/graphql/dataloader` here.
	// Note: imports are already there in the file header.
	return UserLoader(ctx, userID)
}

// QboConnection is the resolver for the qboConnection field.
func (r *queryResolver) QboConnection(ctx context.Context) (*model.QBOCompany, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		// handle not found as null
		if err == pgx.ErrNoRows {
			return nil, nil // No connection
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	return &model.QBOCompany{
		RealmID:     conn.RealmID,
		CompanyName: "QuickBooks Linked Company", // We might want to store this in DB later
		ConnectedAt: &conn.CreatedAt.Time,
	}, nil
}

// SuggestAccounts is the resolver for the suggestAccounts field.
func (r *queryResolver) SuggestAccounts(ctx context.Context, description string) ([]*model.AccountMatch, error) {
	if r.CoAMapper == nil {
		return nil, fmt.Errorf("AI services not configured")
	}

	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to fetch QBO connection: %w", err)
	}

	matches, err := r.CoAMapper.MapDescriptionToAccount(ctx, conn.RealmID, description, 5)
	if err != nil {
		r.Logger.Error("Failed to map description to account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.AccountMatch
	for _, m := range matches {
		results = append(results, &model.AccountMatch{
			AccountID: m.AccountID,
			Score:     m.Score,
			Name:      m.Name,
		})
	}

	return results, nil
}

// ResolveEntity is the resolver for the resolveEntity field.
func (r *queryResolver) ResolveEntity(ctx context.Context, entityType string, name string) (*model.EntityMatch, error) {
	if r.EntityResolver == nil {
		return nil, fmt.Errorf("AI services not configured")
	}

	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to fetch QBO connection: %w", err)
	}

	match, err := r.EntityResolver.ResolveEntity(ctx, conn.RealmID, entityType, name)
	if err != nil {
		r.Logger.Error("Failed to resolve entity", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	if match == nil {
		return nil, nil
	}

	return &model.EntityMatch{
		ID:         match.ID,
		Score:      match.Score,
		Name:       match.Name,
		Source:     match.Source,
		EntityType: match.EntityType,
	}, nil
}

// QboAccount is the resolver for the qbo_account field.
func (r *queryResolver) QboAccount(ctx context.Context, realmID string) ([]*model.Account, error) {
	// Fetch accounts from database
	accounts, err := r.Store.Queries.GetAllAccountsForRealms(ctx, []string{realmID})
	if err != nil {
		r.Logger.Error("Failed to fetch accounts for realm", "error", err, "realm_id", realmID)
		return nil, fmt.Errorf("internal server error")
	}

	var modelAccounts []*model.Account
	for _, a := range accounts {
		modelAccounts = append(modelAccounts, mapDatabaseAccountToModel(&a))
	}

	return modelAccounts, nil
}

// Entities is the resolver for the tenants field (now backed by toro_core.entities).
func (r *queryResolver) Tenants(ctx context.Context, limit int32, offset int32) (*model.TenantConnection, error) {
	// 1. Auth check: Requires valid user session
	userID, ok := ctx.Value(auth.UserIDKey).(uuid.UUID)
	if !ok || userID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	q := database.New(r.DB)

	// 2. Fetch Total Count
	totalCount, err := q.CountEntities(ctx)
	if err != nil {
		r.Logger.Error("Failed to count entities", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 3. Fetch Paginated Entities
	entities, err := q.GetEntities(ctx, database.GetEntitiesParams{
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		r.Logger.Error("Failed to fetch entities", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Convert and build connection
	var nodes []*model.Tenant
	for _, t := range entities {
		nodes = append(nodes, &model.Tenant{
			ID:        uuid.UUID(t.ID.Bytes).String(),
			Name:      t.Name,
			Status:    t.Status.String,
			PlanTier:  t.PlanTier.String,
			CreatedAt: t.CreatedAt.Time,
			UpdatedAt: t.UpdatedAt.Time,
		})
	}

	return &model.TenantConnection{
		Nodes:      nodes,
		TotalCount: int32(totalCount),
		PageInfo: &model.PageInfo{
			HasNextPage:     int64(offset+limit) < totalCount,
			HasPreviousPage: offset > 0,
		},
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// getQBOConnectorHelper initializes the QBO connector after validating the user
