package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"crypto/rand"
	"crypto/subtle"
	"fmt"
	"math/big"
	"os"
	"strings"
	"time"

	"github.com/Yankzy/usetoro/cmd/graphql/graph/model"
	"github.com/Yankzy/usetoro/internal/auth"
	"github.com/Yankzy/usetoro/internal/config"
	"github.com/Yankzy/usetoro/internal/connectors"
	"github.com/Yankzy/usetoro/internal/database"
	quickbooks "github.com/Yankzy/usetoro/internal/erp/adapters/quickbooks/sdk"
	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignupInput) (*model.AuthPayload, error) {
	// Start Transaction
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		r.Logger.Error("Failed to start transaction", "error", err)
		return nil, fmt.Errorf("internal server error")
	}
	defer tx.Rollback(ctx)

	q := database.New(r.DB).WithTx(tx)

	// 1. Create Entity (replaces old Tenant)
	entityID, err := q.CreateEntity(ctx, database.CreateEntityParams{
		Name:       input.OrgName,
		EntityType: "client",
		PlanTier:   pgtype.Text{String: "pro", Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to create entity", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 2. Create User
	pwdHash := hashPassword(input.Password)
	userID, err := q.CreateUser(ctx, database.CreateUserParams{
		EntityID:     entityID,
		Email:        input.Email,
		PasswordHash: pwdHash,
		Role:         pgtype.Text{String: "owner", Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to create user", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 3. Generate Tokens
	user := database.ToroCoreUser{
		ID:       userID,
		EntityID: entityID,
		Role:     pgtype.Text{String: "owner", Valid: true},
	}
	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Save Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    userID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 5. Store Refresh Token in Redis (for caching/blacklisting)
	err = r.Redis.Set(ctx, "refresh_token:"+ref, userID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache refresh token in Redis", "error", err)
		// Proceed anyway, DB is source of truth
	}

	if err := tx.Commit(ctx); err != nil {
		r.Logger.Error("Failed to commit transaction", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userID.String(),
			Email:    input.Email,
			Role:     "owner",
			TenantID: entityID.String(),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	q := database.New(r.DB)

	user, err := q.GetUserByEmail(ctx, input.Email)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("invalid credentials")
		}
		r.Logger.Error("Failed to fetch user", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	if !checkPassword(input.Password, user.PasswordHash) {
		return nil, fmt.Errorf("invalid credentials")
	}

	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Save Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    user.ID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Store Refresh Token in Redis
	err = r.Redis.Set(ctx, "refresh_token:"+ref, user.ID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache refresh token in Redis", "error", err)
	}

	// Convert UUIDs to strings
	userIDStr := uuid.UUID(user.ID.Bytes).String()
	entityIDStr := uuid.UUID(user.EntityID.Bytes).String()

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userIDStr,
			Email:    user.Email,
			Role:     user.Role.String,
			TenantID: entityIDStr,
		},
	}, nil
}

// RequestOtp is the resolver for the requestOTP field.
func (r *mutationResolver) RequestOtp(ctx context.Context, email string) (bool, error) {
	q := database.New(r.DB)

	// Look up user; ignore not-found to avoid leaking user enumeration
	_, err := q.GetUserByEmail(ctx, email)
	if err != nil && err != pgx.ErrNoRows {
		r.Logger.Error("Failed to look up user for OTP", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	// Generate cryptographically secure 6-digit OTP
	n, err := rand.Int(rand.Reader, big.NewInt(1_000_000))
	if err != nil {
		r.Logger.Error("Failed to generate OTP", "error", err)
		return false, fmt.Errorf("internal server error")
	}
	otp := fmt.Sprintf("%06d", n.Int64())

	// Store in Redis with 10-minute TTL
	if err := r.Redis.Set(ctx, "otp:"+email, otp, 10*time.Minute).Err(); err != nil {
		r.Logger.Error("Failed to store OTP in Redis", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	if err := r.EmailSender.SendOTP(email, otp); err != nil {
		r.Logger.Error("Failed to send OTP email", "email", email, "error", err)
		return false, fmt.Errorf("internal server error")
	}

	return true, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, email string, otp string) (*model.AuthPayload, error) {
	// 1. Fetch stored OTP from Redis
	stored, err := r.Redis.Get(ctx, "otp:"+email).Result()
	if err != nil {
		return nil, fmt.Errorf("OTP expired or not requested")
	}

	// 2. Constant-time compare to prevent timing attacks
	if subtle.ConstantTimeCompare([]byte(stored), []byte(otp)) != 1 {
		return nil, fmt.Errorf("invalid OTP")
	}

	// 3. Delete OTP immediately (single-use)
	r.Redis.Del(ctx, "otp:"+email)

	// 4. Fetch user
	q := database.New(r.DB)
	user, err := q.GetUserByEmail(ctx, email)
	if err != nil {
		r.Logger.Error("Failed to fetch user after OTP verification", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 5. Generate tokens
	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 6. Persist refresh token to DB
	if err := q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    user.ID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	}); err != nil {
		r.Logger.Error("Failed to save refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Cache refresh token in Redis
	if err := r.Redis.Set(ctx, "refresh_token:"+ref, user.ID.String(), 7*24*time.Hour).Err(); err != nil {
		r.Logger.Warn("Failed to cache refresh token in Redis", "error", err)
	}

	// 7. Return AuthPayload
	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       uuid.UUID(user.ID.Bytes).String(),
			Email:    user.Email,
			Role:     user.Role.String,
			TenantID: uuid.UUID(user.EntityID.Bytes).String(),
		},
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	q := database.New(r.DB)

	// 1. Get Refresh Token
	tokenRec, err := q.GetRefreshToken(ctx, refreshToken)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("invalid refresh token")
		}
		r.Logger.Error("Failed to fetch refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 2. Check Expiry
	if tokenRec.ExpiresAt.Valid && tokenRec.ExpiresAt.Time.Before(time.Now()) {
		// Cleanup expired token
		_ = q.DeleteRefreshToken(ctx, refreshToken)
		return nil, fmt.Errorf("refresh token expired")
	}

	// 3. Get User
	user, err := q.GetUserByID(ctx, tokenRec.UserID)
	if err != nil {
		r.Logger.Error("Failed to fetch user for refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Generate New Tokens (Rotation)
	acc, ref, exp, err := generateTokens(user, r.PrivateKey)
	if err != nil {
		r.Logger.Error("Failed to generate tokens", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 5. Delete Old Token (Rotation)
	// We do this BEFORE saving the new one to prevent reuse race conditions,
	// though in a transaction would be better. For now simple deletion is fine.
	err = q.DeleteRefreshToken(ctx, refreshToken)
	if err != nil {
		r.Logger.Warn("Failed to delete old refresh token from DB during rotation", "error", err)
	}
	// Also delete from Redis
	r.Redis.Del(ctx, "refresh_token:"+refreshToken)

	// 6. Save New Refresh Token
	err = q.CreateRefreshToken(ctx, database.CreateRefreshTokenParams{
		TokenHash: ref,
		UserID:    user.ID,
		ExpiresAt: pgtype.Timestamptz{Time: exp, Valid: true},
	})
	if err != nil {
		r.Logger.Error("Failed to save new refresh token", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 7. Store new token in Redis
	err = r.Redis.Set(ctx, "refresh_token:"+ref, user.ID.String(), 7*24*time.Hour).Err()
	if err != nil {
		r.Logger.Warn("Failed to cache new refresh token in Redis", "error", err)
	}

	// Return Payload
	userIDStr := uuid.UUID(user.ID.Bytes).String()
	entityIDStr := uuid.UUID(user.EntityID.Bytes).String()

	return &model.AuthPayload{
		AccessToken:  acc,
		RefreshToken: ref,
		ExpiresAt:    exp,
		User: &model.User{
			ID:       userIDStr,
			Email:    user.Email,
			Role:     user.Role.String,
			TenantID: entityIDStr,
		},
	}, nil
}

// DeleteToken is the resolver for the deleteToken field.
func (r *mutationResolver) DeleteToken(ctx context.Context, refreshToken string) (bool, error) {
	q := database.New(r.DB)

	// 1. Delete from DB
	err := q.DeleteRefreshToken(ctx, refreshToken)
	if err != nil {
		r.Logger.Error("Failed to delete refresh token from DB", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	// 2. Delete from Redis
	err = r.Redis.Del(ctx, "refresh_token:"+refreshToken).Err()
	if err != nil {
		r.Logger.Warn("Failed to delete refresh token from Redis", "error", err)
		// Not critical, eventually it will expire
	}

	return true, nil
}

// RecordCorrection is the resolver for the recordCorrection field.
func (r *mutationResolver) RecordCorrection(ctx context.Context, input model.RecordCorrectionInput) (bool, error) {
	userID, _ := ctx.Value(auth.UserIDKey).(uuid.UUID)
	// userID can be nil for anonymous corrections if supported, but here we expect it

	q := database.New(r.DB)

	conf := pgtype.Numeric{}
	if input.ConfidenceScore != nil {
		conf.Scan(fmt.Sprintf("%f", *input.ConfidenceScore))
	}

	err := q.RecordAICorrection(ctx, database.RecordAICorrectionParams{
		RealmID:         input.RealmID,
		UserID:          pgtype.UUID{Bytes: userID, Valid: userID != uuid.Nil},
		RawInput:        input.RawInput,
		AiPrediction:    pgtype.Text{String: *input.AiPrediction, Valid: input.AiPrediction != nil},
		UserCorrection:  input.UserCorrection,
		CorrectionType:  input.CorrectionType,
		ConfidenceScore: conf,
	})
	if err != nil {
		r.Logger.Error("Failed to record AI correction", "error", err)
		return false, fmt.Errorf("internal server error")
	}

	// Active Learning: Update synonyms for better future matching
	if r.EntityResolver != nil {
		go func() {
			// Use background context to not block the response
			bgCtx := context.Background()
			if err := r.EntityResolver.Learn(bgCtx, input.RealmID, input.RawInput, input.UserCorrection, input.CorrectionType); err != nil {
				r.Logger.Warn("Failed to learn from correction", "error", err, "raw_input", input.RawInput)
			}
		}()
	}

	return true, nil
}

// SyncQboChartOfAccounts is the resolver for the syncQboChartOfAccounts field.
func (r *mutationResolver) SyncQboChartOfAccounts(ctx context.Context, realmID string) (int32, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return 0, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		if err == pgx.ErrNoRows {
			return 0, fmt.Errorf("no qbo connection")
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return 0, fmt.Errorf("internal server error")
	}

	if conn.RealmID != realmID {
		return 0, fmt.Errorf("unauthorized")
	}

	clientID := os.Getenv("QBO_CLIENT_ID")
	clientSecret := os.Getenv("QBO_CLIENT_SECRET")
	if clientID == "" || clientSecret == "" {
		return 0, fmt.Errorf("qbo client credentials not configured")
	}

	isProd := strings.EqualFold(os.Getenv("QBO_IS_PRODUCTION"), "true")
	cfg := &config.Config{
		QBOClientID:     clientID,
		QBOClientSecret: clientSecret,
		QBOIsProduction: isProd,
	}

	qboConn := connectors.NewQBOConnector(r.Logger, cfg, r.Store, r.NatsConn)
	count, err := qboConn.SyncFullChartOfAccounts(ctx, entityID.String(), realmID)
	if err != nil {
		r.Logger.Error("Full CoA sync failed", "error", err, "realm_id", realmID)
		return 0, fmt.Errorf("sync failed")
	}

	return int32(count), nil
}

// SyncQboCustomers is the resolver for the syncQboCustomers field.
func (r *mutationResolver) SyncQboCustomers(ctx context.Context, realmID string) (int32, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return 0, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		if err == pgx.ErrNoRows {
			return 0, fmt.Errorf("no qbo connection")
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return 0, fmt.Errorf("internal server error")
	}

	if conn.RealmID != realmID {
		return 0, fmt.Errorf("unauthorized")
	}

	clientID := os.Getenv("QBO_CLIENT_ID")
	clientSecret := os.Getenv("QBO_CLIENT_SECRET")
	if clientID == "" || clientSecret == "" {
		return 0, fmt.Errorf("qbo client credentials not configured")
	}

	isProd := strings.EqualFold(os.Getenv("QBO_IS_PRODUCTION"), "true")
	cfg := &config.Config{
		QBOClientID:     clientID,
		QBOClientSecret: clientSecret,
		QBOIsProduction: isProd,
	}

	qboConn := connectors.NewQBOConnector(r.Logger, cfg, r.Store, r.NatsConn)
	count, err := qboConn.SyncFullCustomers(ctx, entityID.String(), realmID)
	if err != nil {
		r.Logger.Error("Full Customers sync failed", "error", err, "realm_id", realmID)
		return 0, fmt.Errorf("sync failed")
	}

	return int32(count), nil
}

// CreateQboAccount is the resolver for the createQboAccount field.
func (r *mutationResolver) CreateQboAccount(ctx context.Context, input model.CreateQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	qboAccount := &quickbooks.Account{
		Name:        input.Name,
		AccountType: input.AccountType,
	}
	if input.AccountSubType != nil {
		qboAccount.AccountSubType = *input.AccountSubType
	}
	if input.Classification != nil {
		qboAccount.Classification = *input.Classification
	}
	if input.Description != nil {
		qboAccount.Description = *input.Description
	}
	if input.Active != nil {
		qboAccount.Active = *input.Active
	} else {
		qboAccount.Active = true // QBO accounts are active by default
	}
	if input.SubAccount != nil {
		qboAccount.SubAccount = *input.SubAccount
	}
	if input.ParentRefValue != nil {
		qboAccount.ParentRef = quickbooks.ReferenceType{Value: *input.ParentRefValue}
	}
	if input.CurrencyRefValue != nil {
		qboAccount.CurrencyRef = quickbooks.ReferenceType{Value: *input.CurrencyRefValue}
	}

	created, err := qboConn.CreateAccount(ctx, entityID.String(), input.RealmID, qboAccount)
	if err != nil {
		r.Logger.Error("Failed to create QBO account", "error", err, "realm_id", input.RealmID)
		return nil, fmt.Errorf("failed to create account")
	}

	// Fetch from DB to return
	dbAccount, err := r.Store.Queries.GetAccountByERPID(ctx, database.GetAccountByERPIDParams{
		RealmID: input.RealmID,
		ErpID:   created.Id,
	})
	if err != nil {
		r.Logger.Error("Failed to fetch created QBO account from shadow db", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// UpdateQboAccount is the resolver for the updateQboAccount field.
func (r *mutationResolver) UpdateQboAccount(ctx context.Context, input model.UpdateQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	uid, err := uuid.Parse(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id format")
	}

	var qboID string
	err = r.DB.QueryRow(ctx, "SELECT erp_id FROM shadow_erp.accounts WHERE id = $1 AND realm_id = $2 AND deleted_at IS NULL", uid, input.RealmID).Scan(&qboID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("account not found")
		}
		r.Logger.Error("Failed to fetch QBO ID for account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	qboAccount := &quickbooks.Account{
		Id: qboID,
	}
	if input.Name != nil {
		qboAccount.Name = *input.Name
	}
	if input.AccountType != nil {
		qboAccount.AccountType = *input.AccountType
	}
	if input.AccountSubType != nil {
		qboAccount.AccountSubType = *input.AccountSubType
	}
	if input.Description != nil {
		qboAccount.Description = *input.Description
	}
	if input.Active != nil {
		qboAccount.Active = *input.Active
	} else {
		// Do not set false, UpdateAccount uses sparse which omits false unless explicitly sent.
		// Wait, omitempty on Active bool means we can't send Active: false here.
		// That's why we have DeactivateAccount for explicitly setting active=false.
		// For update, if Active is true, we set it. The user shouldn't pass false to Update if we have SoftDelete!
	}

	updated, err := qboConn.UpdateAccount(ctx, entityID.String(), input.RealmID, qboAccount)
	if err != nil {
		r.Logger.Error("Failed to update QBO account", "error", err, "realm_id", input.RealmID)
		return nil, err
	}

	dbAccount, err := r.Store.Queries.GetAccountByERPID(ctx, database.GetAccountByERPIDParams{
		RealmID: input.RealmID,
		ErpID:   updated.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch updated account")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// SoftDeleteQboAccount is the resolver for the softDeleteQboAccount field.
func (r *mutationResolver) SoftDeleteQboAccount(ctx context.Context, input model.SoftDeleteQboAccountInput) (*model.Account, error) {
	qboConn, entityID, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	uid, err := uuid.Parse(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id format")
	}

	var qboID string
	err = r.DB.QueryRow(ctx, "SELECT erp_id FROM shadow_erp.accounts WHERE id = $1 AND realm_id = $2", uid, input.RealmID).Scan(&qboID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("account not found")
		}
		r.Logger.Error("Failed to fetch QBO ID for account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	deactivated, err := qboConn.SoftDeleteAccount(ctx, entityID.String(), input.RealmID, qboID)
	if err != nil {
		r.Logger.Error("Failed to deactivate QBO account", "error", err, "realm_id", input.RealmID)
		return nil, err
	}

	dbAccount, err := r.Store.Queries.GetAccountByERPID(ctx, database.GetAccountByERPIDParams{
		RealmID: input.RealmID,
		ErpID:   deactivated.Id,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to fetch deactivated account")
	}

	return mapDatabaseAccountToModel(&dbAccount), nil
}

// UpdateQboCompanyInfo is the resolver for the updateQboCompanyInfo field.
func (r *mutationResolver) UpdateQboCompanyInfo(ctx context.Context, input model.UpdateQboCompanyInput) (*model.QBOCompany, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	qboConn, _, err := r.getQBOConnectorHelper(ctx, input.RealmID)
	if err != nil {
		return nil, err
	}

	// Convert input to quickbooks.CompanyInfo
	qboInfo := &quickbooks.CompanyInfo{}
	if input.CompanyName != nil {
		qboInfo.CompanyName = *input.CompanyName
	}
	if input.LegalName != nil {
		qboInfo.LegalName = *input.LegalName
	}
	if input.Domain != nil {
		qboInfo.Domain = *input.Domain
	}
	if input.Country != nil {
		qboInfo.Country = *input.Country
	}

	updatedInfo, err := qboConn.UpdateCompanyInfo(ctx, entityID.String(), input.RealmID, qboInfo)
	if err != nil {
		r.Logger.Error("Failed to update QBO Company", "realm_id", input.RealmID, "error", err)
		return nil, fmt.Errorf("failed to update company info")
	}

	// Fetch connection info for connectedAt mapping
	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	var connectedAt *time.Time
	if err == nil {
		connectedAt = &conn.CreatedAt.Time
	}

	return &model.QBOCompany{
		RealmID:     input.RealmID,
		CompanyName: updatedInfo.CompanyName,
		ConnectedAt: connectedAt,
	}, nil
}

// FignodeCategorize is the resolver for the fignodeCategorize field.
// This is used by the mobile/desktop app to swipe transactions.
func (r *mutationResolver) FignodeCategorize(ctx context.Context, rowID string, accountID *string, vendorID *string, action string) (*model.FignodeStagingRow, error) {
	rowUUID, err := uuid.Parse(rowID)
	if err != nil {
		return nil, fmt.Errorf("invalid row id")
	}
	pgRowID := pgtype.UUID{Bytes: rowUUID, Valid: true}

	// Action logic: ENRICH or SKIP. The schema.resolvers.go uses OverrideCleanupRow to approve.
	// Since action might be "SKIP", we should handle that.
	if action == "SKIP" {
		if err := r.Store.Queries.RejectCleanupRow(ctx, pgRowID); err != nil {
			return nil, fmt.Errorf("failed to skip row")
		}
		// Return the skipped row
		row, err := r.Store.Queries.GetCleanupRow(ctx, pgRowID)
		if err != nil {
			return nil, err
		}
		return mapGetCleanupRowRowToModel(row), nil
	}

	// Enriched / Approved
	arg := database.OverrideCleanupRowParams{ID: pgRowID}
	if vendorID != nil {
		if v, err := uuid.Parse(*vendorID); err == nil {
			arg.OverrideVendorID = pgtype.UUID{Bytes: v, Valid: true}
		}
	}
	if accountID != nil {
		if a, err := uuid.Parse(*accountID); err == nil {
			arg.OverrideAccountID = pgtype.UUID{Bytes: a, Valid: true}
		}
	}

	row, err := r.Store.Queries.OverrideCleanupRow(ctx, arg)
	if err != nil {
		r.Logger.Error("FignodeCategorize: db error", "row_id", rowID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// Active Learning Loop
	if r.EntityResolver != nil {
		correctionType := "account"
		correctionID := ""
		if vendorID != nil {
			correctionType = "vendor"
			correctionID = *vendorID
		} else if accountID != nil {
			correctionID = *accountID
		}
		rawInput := row.RawDescription.String
		if correctionID != "" && rawInput != "" && row.RealmID.Valid {
			if learnErr := r.EntityResolver.Learn(ctx, row.RealmID.String, rawInput, correctionID, correctionType); learnErr != nil {
				r.Logger.Warn("FignodeCategorize: learning loop failed", "error", learnErr)
			}
		}
	}

	fignodeTx := database.FignodeStagingTransaction{
		ID:                 row.ID,
		SessionID:          row.SessionID,
		SourceType:         row.SourceType,
		RawDescription:     row.RawDescription,
		RawAmount:          row.RawAmount,
		RawDate:            row.RawDate,
		PredictedVendorID:  row.PredictedVendorID,
		PredictedAccountID: row.PredictedAccountID,
		ConfidenceScore:    row.ConfidenceScore,
		AiReasoning:        row.AiReasoning,
		DuplicateOf:        row.DuplicateOf,
		IsRecurring:        row.IsRecurring,
		SplitSuggestion:    row.SplitSuggestion,
		OverrideVendorID:   row.OverrideVendorID,
		OverrideAccountID:  row.OverrideAccountID,
		Status:             row.Status,
		ErpTransactionID:   row.ErpTransactionID,
		CreatedAt:          row.CreatedAt,
		UpdatedAt:          row.UpdatedAt,
	}

	// Gamification hooks
	userID, _ := ctx.Value(auth.UserIDKey).(uuid.UUID)
	if userID != uuid.Nil {
		// In a full implementation, we would increment the EmployeeProfile stats here.
		// e.g. r.LeaderboardService.Increment(ctx, userID, 1)
	}

	out := mapStagingRowToModel(fignodeTx)
	if row.RealmID.Valid {
		realm := row.RealmID.String
		out.RealmID = &realm
	}
	return out, nil
}

// ApproveAllByVendor bulk-approves all ENRICHED rows for a given vendor within a session.
func (r *mutationResolver) ApproveAllByVendor(ctx context.Context, sessionID string, vendorID string) (int32, error) {
	sessionUUID, err := uuid.Parse(sessionID)
	if err != nil {
		return 0, fmt.Errorf("invalid session id")
	}
	vendorUUID, err := uuid.Parse(vendorID)
	if err != nil {
		return 0, fmt.Errorf("invalid vendor id")
	}

	ids, err := r.Store.Queries.BulkApproveByVendor(ctx, database.BulkApproveByVendorParams{
		SessionID:         pgtype.UUID{Bytes: sessionUUID, Valid: true},
		PredictedVendorID: pgtype.UUID{Bytes: vendorUUID, Valid: true},
	})
	if err != nil {
		r.Logger.Error("ApproveAllByVendor: db error", "session_id", sessionID, "vendor_id", vendorID, "error", err)
		return 0, fmt.Errorf("internal server error")
	}
	return int32(len(ids)), nil
}

// PostFignodeSession is the resolver for the postFignodeSession field.
func (r *mutationResolver) PostFignodeSession(ctx context.Context, sessionID string) (*model.FignodePostResult, error) {
	return r.postCleanupSessionHelper(ctx, sessionID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	// Extract userID from context (requires auth middleware)
	userID, ok := ctx.Value(auth.UserIDKey).(uuid.UUID)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	// Use Data Loader
	// We need to import `github.com/Yankzy/usetoro/cmd/graphql/dataloader` here.
	// Note: imports are already there in the file header.
	return UserLoader(ctx, userID)
}

// QboConnection is the resolver for the qboConnection field.
func (r *queryResolver) QboConnection(ctx context.Context) (*model.QBOCompany, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		// handle not found as null
		if err == pgx.ErrNoRows {
			return nil, nil // No connection
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	companyName := ""
	if info, err := r.Store.Queries.GetCompanyInfo(ctx, conn.RealmID); err == nil {
		companyName = info.CompanyName
	}

	return &model.QBOCompany{
		RealmID:     conn.RealmID,
		CompanyName: companyName,
		ConnectedAt: &conn.CreatedAt.Time,
	}, nil
}

// SuggestAccounts is the resolver for the suggestAccounts field.
func (r *queryResolver) SuggestAccounts(ctx context.Context, description string) ([]*model.AccountMatch, error) {
	if r.CoAMapper == nil {
		return nil, fmt.Errorf("AI services not configured")
	}

	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to fetch QBO connection: %w", err)
	}

	matches, err := r.CoAMapper.MapDescriptionToAccount(ctx, conn.RealmID, description, 5)
	if err != nil {
		r.Logger.Error("Failed to map description to account", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.AccountMatch
	for _, m := range matches {
		results = append(results, &model.AccountMatch{
			AccountID: m.AccountID,
			Score:     m.Score,
			Name:      m.Name,
		})
	}

	return results, nil
}

// ResolveEntity is the resolver for the resolveEntity field.
func (r *queryResolver) ResolveEntity(ctx context.Context, entityType string, name string) (*model.EntityMatch, error) {
	if r.EntityResolver == nil {
		return nil, fmt.Errorf("AI services not configured")
	}

	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to fetch QBO connection: %w", err)
	}

	match, err := r.EntityResolver.ResolveEntity(ctx, conn.RealmID, entityType, name)
	if err != nil {
		r.Logger.Error("Failed to resolve entity", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	if match == nil {
		return nil, nil
	}

	return &model.EntityMatch{
		ID:         match.ID,
		Score:      match.Score,
		Name:       match.Name,
		Source:     match.Source,
		EntityType: match.EntityType,
	}, nil
}

// QboAccount is the resolver for the qbo_account field.
func (r *queryResolver) QboAccount(ctx context.Context, realmID string) ([]*model.Account, error) {
	// Fetch accounts from database
	accounts, err := r.Store.Queries.GetAllAccountsForRealms(ctx, []string{realmID})
	if err != nil {
		r.Logger.Error("Failed to fetch accounts for realm", "error", err, "realm_id", realmID)
		return nil, fmt.Errorf("internal server error")
	}

	var modelAccounts []*model.Account
	for _, a := range accounts {
		modelAccounts = append(modelAccounts, mapDatabaseAccountToModel(&a))
	}

	return modelAccounts, nil
}

// QboCustomers is the resolver for the qboCustomers field.
func (r *queryResolver) QboCustomers(ctx context.Context, realmID string) ([]*model.Customer, error) {
	rows, err := r.Store.Queries.GetAllCustomersForRealms(ctx, []string{realmID})
	if err != nil {
		r.Logger.Error("Failed to fetch customers for realm", "error", err, "realm_id", realmID)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.Customer, 0, len(rows))
	for i := range rows {
		out = append(out, mapDatabaseCustomerToModel(&rows[i]))
	}
	return out, nil
}

// QboCustomersByTenant is the resolver for the qboCustomersByTenant field.
func (r *queryResolver) QboCustomersByTenant(ctx context.Context, tenantID string, includeChildren *bool) ([]*model.Customer, error) {
	entityUUID, err := uuid.Parse(tenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid tenant id")
	}
	pgID := pgtype.UUID{Bytes: entityUUID, Valid: true}

	var entityIDs []pgtype.UUID
	if includeChildren != nil && *includeChildren {
		entityIDs, err = r.Store.Queries.GetEntityDescendants(ctx, pgID)
		if err != nil {
			r.Logger.Error("Failed to resolve entity descendants", "error", err, "tenant_id", tenantID)
			return nil, fmt.Errorf("internal server error")
		}
	} else {
		entityIDs = []pgtype.UUID{pgID}
	}

	realmIDs, err := r.Store.Queries.GetRealmsForEntities(ctx, entityIDs)
	if err != nil {
		r.Logger.Error("Failed to resolve realms for tenant", "error", err, "tenant_id", tenantID)
		return nil, fmt.Errorf("internal server error")
	}
	if len(realmIDs) == 0 {
		return []*model.Customer{}, nil
	}

	rows, err := r.Store.Queries.GetAllCustomersForRealms(ctx, realmIDs)
	if err != nil {
		r.Logger.Error("Failed to fetch customers for tenant", "error", err, "tenant_id", tenantID)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.Customer, 0, len(rows))
	for i := range rows {
		out = append(out, mapDatabaseCustomerToModel(&rows[i]))
	}
	return out, nil
}

// Entities is the resolver for the tenants field (now backed by toro_core.entities).
func (r *queryResolver) Tenants(ctx context.Context, limit int32, offset int32) (*model.TenantConnection, error) {
	// 1. Auth check: Requires valid user session
	userID, ok := ctx.Value(auth.UserIDKey).(uuid.UUID)
	if !ok || userID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	q := database.New(r.DB)

	// 2. Fetch Total Count
	totalCount, err := q.CountEntities(ctx)
	if err != nil {
		r.Logger.Error("Failed to count entities", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 3. Fetch Paginated Entities
	entities, err := q.GetEntities(ctx, database.GetEntitiesParams{
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		r.Logger.Error("Failed to fetch entities", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	// 4. Convert and build connection
	var nodes []*model.Tenant
	for _, t := range entities {
		nodes = append(nodes, &model.Tenant{
			ID:        uuid.UUID(t.ID.Bytes).String(),
			Name:      t.Name,
			Status:    t.Status.String,
			PlanTier:  t.PlanTier.String,
			CreatedAt: t.CreatedAt.Time,
			UpdatedAt: t.UpdatedAt.Time,
		})
	}

	return &model.TenantConnection{
		Nodes:      nodes,
		TotalCount: int32(totalCount),
		PageInfo: &model.PageInfo{
			HasNextPage:     int64(offset+limit) < totalCount,
			HasPreviousPage: offset > 0,
		},
	}, nil
}

// QboVendors is the resolver for the qboVendors field.
func (r *queryResolver) QboVendors(ctx context.Context, realmID string) ([]*model.Vendor, error) {
	rows, err := r.Store.Queries.GetAllVendorsForRealms(ctx, []string{realmID})
	if err != nil {
		r.Logger.Error("Failed to fetch vendors for realm", "error", err, "realm_id", realmID)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.Vendor, 0, len(rows))
	for i := range rows {
		out = append(out, mapDatabaseVendorToModel(&rows[i]))
	}
	return out, nil
}

// QboVendorsByEntity is the resolver for the qboVendorsByEntity field.
func (r *queryResolver) QboVendorsByEntity(ctx context.Context, entityID string) ([]*model.Vendor, error) {
	entityUUID, err := uuid.Parse(entityID)
	if err != nil {
		return nil, fmt.Errorf("invalid entity id")
	}
	pgID := pgtype.UUID{Bytes: entityUUID, Valid: true}

	realmIDs, err := r.Store.Queries.GetRealmsForEntities(ctx, []pgtype.UUID{pgID})
	if err != nil {
		r.Logger.Error("Failed to resolve realms for entity", "error", err, "entity_id", entityID)
		return nil, fmt.Errorf("internal server error")
	}
	if len(realmIDs) == 0 {
		return []*model.Vendor{}, nil
	}

	rows, err := r.Store.Queries.GetAllVendorsForRealms(ctx, realmIDs)
	if err != nil {
		r.Logger.Error("Failed to fetch vendors for entity", "error", err, "entity_id", entityID)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.Vendor, 0, len(rows))
	for i := range rows {
		out = append(out, mapDatabaseVendorToModel(&rows[i]))
	}
	return out, nil
}

// QboVendorsByTenant is the resolver for the qboVendorsByTenant field.
func (r *queryResolver) QboVendorsByTenant(ctx context.Context, tenantID string) ([]*model.Vendor, error) {
	entityUUID, err := uuid.Parse(tenantID)
	if err != nil {
		return nil, fmt.Errorf("invalid tenant id")
	}
	pgID := pgtype.UUID{Bytes: entityUUID, Valid: true}

	entityIDs, err := r.Store.Queries.GetEntityDescendants(ctx, pgID)
	if err != nil {
		r.Logger.Error("Failed to resolve entity descendants", "error", err, "tenant_id", tenantID)
		return nil, fmt.Errorf("internal server error")
	}

	realmIDs, err := r.Store.Queries.GetRealmsForEntities(ctx, entityIDs)
	if err != nil {
		r.Logger.Error("Failed to resolve realms for tenant", "error", err, "tenant_id", tenantID)
		return nil, fmt.Errorf("internal server error")
	}
	if len(realmIDs) == 0 {
		return []*model.Vendor{}, nil
	}

	rows, err := r.Store.Queries.GetAllVendorsForRealms(ctx, realmIDs)
	if err != nil {
		r.Logger.Error("Failed to fetch vendors for tenant", "error", err, "tenant_id", tenantID)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.Vendor, 0, len(rows))
	for i := range rows {
		out = append(out, mapDatabaseVendorToModel(&rows[i]))
	}
	return out, nil
}

// FignodeSessions is the resolver for the fignodeSessions field.
func (r *queryResolver) FignodeSessions(ctx context.Context, realmID *string) ([]*model.FignodeSession, error) {
	arg := database.ListCleanupSessionsParams{}
	if realmID != nil && *realmID != "" {
		arg.RealmID = pgtype.Text{String: *realmID, Valid: true}
	} else {
		// Fall back to user-scoped listing.
		userID, _ := ctx.Value(auth.UserIDKey).(uuid.UUID)
		if userID != uuid.Nil {
			arg.CreatedBy = pgtype.UUID{Bytes: userID, Valid: true}
		}
	}

	rows, err := r.Store.Queries.ListCleanupSessions(ctx, arg)
	if err != nil {
		r.Logger.Error("FignodeSessions: db error", "realm_id", realmID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}
	out := make([]*model.FignodeSession, 0, len(rows))
	for _, s := range rows {
		out = append(out, mapListCleanupSessionsRowToModel(s))
	}
	return out, nil
}

// FignodeSession is the resolver for the fignodeSession field.
func (r *queryResolver) FignodeSession(ctx context.Context, sessionID string) (*model.FignodeSession, error) {
	sessionUUID, err := uuid.Parse(sessionID)
	if err != nil {
		return nil, fmt.Errorf("invalid session id")
	}
	pgSessionID := pgtype.UUID{Bytes: sessionUUID, Valid: true}

	session, err := r.Store.Queries.GetCleanupSession(ctx, pgSessionID)
	if err != nil {
		return nil, fmt.Errorf("session not found")
	}

	return mapGetCleanupSessionRowToModel(session), nil
}

// FignodeBatch is the resolver for the fignodeBatch field.
func (r *queryResolver) FignodeBatch(ctx context.Context, sessionID *string, limit int32) ([]*model.FignodeStagingRow, error) {
	var out []*model.FignodeStagingRow

	if sessionID != nil && *sessionID != "" {
		sessionUUID, errParse := uuid.Parse(*sessionID)
		if errParse != nil {
			return nil, fmt.Errorf("invalid session id")
		}
		rows, err := r.Store.Queries.GetPendingSessionRows(ctx, pgtype.UUID{Bytes: sessionUUID, Valid: true})
		if err != nil {
			r.Logger.Error("FignodeBatch error", "error", err)
			return nil, fmt.Errorf("failed to fetch batch")
		}
		max := int(limit)
		if len(rows) < max {
			max = len(rows)
		}
		for _, row := range rows[:max] {
			out = append(out, mapGetPendingSessionRowsRowToModel(row))
		}
	} else {
		// Fetch pending rows for currently authenticated user's active Realm
		entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
		if entityID == uuid.Nil {
			return nil, fmt.Errorf("unauthorized")
		}
		conn, connErr := r.Store.GetQBOConnection(ctx, entityID.String())
		if connErr != nil {
			return nil, fmt.Errorf("no qbo connection")
		}

		arg := database.GetPendingRealmRowsParams{
			RealmID: pgtype.Text{String: conn.RealmID, Valid: true},
			Limit:   limit,
		}
		realmRows, err := r.Store.Queries.GetPendingRealmRows(ctx, arg)
		if err != nil {
			r.Logger.Error("FignodeBatch error", "error", err)
			return nil, fmt.Errorf("failed fetching realm transactions")
		}
		for _, row := range realmRows {
			out = append(out, mapGetPendingRealmRowsRowToModel(row))
		}
	}

	return out, nil
}

// StagingRows is the resolver for the stagingRows field.
func (r *queryResolver) StagingRows(ctx context.Context, sessionID string, status *string) ([]*model.FignodeStagingRow, error) {
	sessionUUID, err := uuid.Parse(sessionID)
	if err != nil {
		return nil, fmt.Errorf("invalid session id")
	}
	pgSessionID := pgtype.UUID{Bytes: sessionUUID, Valid: true}

	var pgStatus pgtype.Text
	if status != nil {
		pgStatus = pgtype.Text{String: *status, Valid: true}
	}

	rows, err := r.Store.Queries.GetSessionRows(ctx, database.GetSessionRowsParams{
		SessionID: pgSessionID,
		Status:    pgStatus,
	})
	if err != nil {
		r.Logger.Error("StagingRows: db error", "session_id", sessionID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	out := make([]*model.FignodeStagingRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mapSessionRowToModel(row))
	}
	return out, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, realmID string, status *string) ([]*model.Transaction, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("no qbo connection")
		}
		r.Logger.Error("Failed to fetch QBO connection", "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	if conn.RealmID != realmID {
		return nil, fmt.Errorf("unauthorized")
	}

	txns, err := r.TransactionService.FetchUnifiedTransactions(ctx, realmID, status)
	if err != nil {
		r.Logger.Error("Failed to fetch unified transactions", "realm_id", realmID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.Transaction
	for _, t := range txns {
		var vendorName *string
		if t.VendorName != "" {
			vn := t.VendorName
			vendorName = &vn
		}

		var vendorId *string
		if t.VendorID != "" {
			vid := t.VendorID
			vendorId = &vid
		}

		var accountId *string
		if t.AccountID != "" {
			aid := t.AccountID
			accountId = &aid
		}

		var desc *string
		if t.Description != "" {
			d := t.Description
			desc = &d
		}

		var memo *string
		if t.Memo != "" {
			m := t.Memo
			memo = &m
		}

		results = append(results, &model.Transaction{
			ID:          t.ToroID,
			ExternalID:  t.ExternalID,
			Amount:      t.Amount,
			VendorName:  vendorName,
			VendorID:    vendorId,
			AccountID:   accountId,
			Date:        t.Date,
			Description: desc,
			Memo:        memo,
			SourceType:  t.SourceType,
		})
	}

	return results, nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context, realmID string, typeArg *string, active *bool) ([]*model.Account, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil || conn.RealmID != realmID {
		return nil, fmt.Errorf("unauthorized")
	}

	accs, err := r.EntityService.FetchAccounts(ctx, realmID)
	if err != nil {
		r.Logger.Error("Failed to fetch accounts", "realm_id", realmID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.Account
	for _, a := range accs {
		if typeArg != nil && *typeArg != "" && a.AccountType != *typeArg {
			continue
		}
		if active != nil && a.Active != *active {
			continue
		}

		var cls *string
		if a.Classification != "" {
			c := a.Classification
			cls = &c
		}

		var aType *string
		if a.AccountType != "" {
			t := a.AccountType
			aType = &t
		}

		var aSubType *string
		if a.AccountSubType != "" {
			s := a.AccountSubType
			aSubType = &s
		}

		var fqn *string
		if a.FullyQualifiedName != "" {
			f := a.FullyQualifiedName
			fqn = &f
		}

		act := a.Active
		bal := a.CurrentBalance
		var curr *string
		if a.Currency != "" {
			c := a.Currency
			curr = &c
		}

		cTime := a.CreatedAt
		uTime := a.UpdatedAt

		results = append(results, &model.Account{
			ID:                 a.ToroID,
			RealmID:            a.RealmID,
			Name:               a.Name,
			Classification:     cls,
			AccountType:        aType,
			AccountSubType:     aSubType,
			FullyQualifiedName: fqn,
			Active:             &act,
			SyncToken:          a.SyncToken,
			CurrencyRefValue:   curr,
			CurrentBalance:     &bal,
			CreatedAt:          cTime,
			UpdatedAt:          uTime,
		})
	}
	return results, nil
}

// Vendors is the resolver for the vendors field.
func (r *queryResolver) Vendors(ctx context.Context, realmID string, search *string) ([]*model.Vendor, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil || conn.RealmID != realmID {
		return nil, fmt.Errorf("unauthorized")
	}

	vs, err := r.EntityService.FetchVendors(ctx, realmID)
	if err != nil {
		r.Logger.Error("Failed to fetch vendors", "realm_id", realmID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.Vendor
	for _, v := range vs {
		if search != nil && *search != "" && !strings.Contains(strings.ToLower(v.DisplayName), strings.ToLower(*search)) {
			continue
		}

		cTime := v.CreatedAt
		uTime := v.UpdatedAt

		results = append(results, &model.Vendor{
			ID:          v.ToroID,
			RealmID:     v.RealmID,
			ErpID:       v.ExternalID,
			DisplayName: v.DisplayName,
			SyncToken:   v.SyncToken,
			CreatedAt:   cTime,
			UpdatedAt:   uTime,
		})
	}
	return results, nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context, realmID string, search *string) ([]*model.Customer, error) {
	entityID, _ := ctx.Value(auth.EntityIDKey).(uuid.UUID)
	if entityID == uuid.Nil {
		return nil, fmt.Errorf("unauthorized")
	}

	conn, err := r.Store.GetQBOConnection(ctx, entityID.String())
	if err != nil || conn.RealmID != realmID {
		return nil, fmt.Errorf("unauthorized")
	}

	cs, err := r.EntityService.FetchCustomers(ctx, realmID)
	if err != nil {
		r.Logger.Error("Failed to fetch customers", "realm_id", realmID, "error", err)
		return nil, fmt.Errorf("internal server error")
	}

	var results []*model.Customer
	for _, c := range cs {
		if search != nil && *search != "" && !strings.Contains(strings.ToLower(c.DisplayName), strings.ToLower(*search)) {
			continue
		}

		cTime := c.CreatedAt
		uTime := c.UpdatedAt

		results = append(results, &model.Customer{
			ID:          c.ToroID,
			RealmID:     c.RealmID,
			DisplayName: c.DisplayName,
			SyncToken:   c.SyncToken,
			CreatedAt:   cTime,
			UpdatedAt:   uTime,
		})
	}
	return results, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
