package agents

import (
	"encoding/json"
	"fmt"
	"log"
	"time"

	"github.com/Yankzy/usetoro/tap/pkg/core"
	"github.com/Yankzy/usetoro/tap/pkg/identity"
	"github.com/Yankzy/usetoro/tap/pkg/lookup"
	"github.com/Yankzy/usetoro/tap/pkg/transport"
	"github.com/nats-io/nats.go"
)

func TruckerAgent() {
	// 1. Setup Identity
	kp, _ := identity.KeyPairFromSeed("agents.trucker")
	did := identity.CreateDID(kp.Public)
	log.Printf("🚚 Trucker Agent Online. DID: %s", did)

	// 2. Connect
	nc, err := transport.Connect(nats.DefaultURL)
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	// 3. Register with Almanac (So we can be found directly)
	register(nc, kp, did)

	// 4. Subscribe to Direct Messages (For Negotiation)
	myInbox := core.BuildAgentInbox(did)
	nc.Subscribe(myInbox, func(msg *nats.Msg) {
		handleDirectMessage(nc, kp, did, msg)
	})

	// 5. Subscribe to Work (We want Accounting work for the demo, or Trucking)
	// Let's listen to the Accounting topic generated by the Validator above
	// In a real Trucker app, this would be "tasks.logistics.10.>"
	// We use ">" to subscribe to multiple subtopics (NATS syntax)
	// To subscribe to all levels of accounting, use "tasks.accounting.*.>"
	workTopic := "tasks.accounting.1.>"
	nc.Subscribe(workTopic, func(msg *nats.Msg) {
		handleNewWork(nc, kp, did, msg)
	})

	log.Printf("👂 Listening for work on %s...", workTopic)
	select {} // Block forever
}

// register sends a heartbeat to the Almanac
func register(nc *nats.Conn, kp *identity.KeyPair, did string) {
	payload := lookup.RegistrationPayload{
		DID:       did,
		Endpoints: []string{core.BuildAgentInbox(did)},
		Capabilities: []lookup.RegistrationCapability{
			{Type: "logistics.trucking"},
		},
		Expiry: time.Now().Add(1 * time.Hour),
	}
	data, _ := json.Marshal(payload)
	nc.Publish("almanac.register", data)
}

// handleNewWork processes broadcast CFPs
func handleNewWork(nc *nats.Conn, kp *identity.KeyPair, myDID string, msg *nats.Msg) {
	var env core.Envelope
	if err := json.Unmarshal(msg.Data, &env); err != nil {
		return
	}

	if env.Performative == core.CFP {
		log.Printf("📦 Found Job: %s (from %s)", env.ConversationID, env.SenderDID)

		// 1. Analyze Task (Simulated)
		time.Sleep(500 * time.Millisecond)

		// 2. Send PROPOSE
		// We offer to do it.
		proposalBody := map[string]interface{}{
			"price": 500,
			"eta":   "10m",
		}

		replyEnv, _ := core.NewEnvelope(
			fmt.Sprintf("msg_%d", time.Now().UnixNano()),
			myDID,
			env.SenderDID,
			env.ConversationID,
			core.PROPOSE,
			proposalBody,
		)
		replyEnv.Signature = kp.Sign(replyEnv.Body)

		replyBytes, _ := json.Marshal(replyEnv)
		nc.Publish(core.BuildAgentInbox(env.SenderDID), replyBytes)

		log.Printf("📨 Sent Proposal for %s", env.ConversationID)
	}
}

// handleDirectMessage processes ACCEPT/REJECT
func handleDirectMessage(nc *nats.Conn, kp *identity.KeyPair, myDID string, msg *nats.Msg) {
	var env core.Envelope
	if err := json.Unmarshal(msg.Data, &env); err != nil {
		return
	}

	switch env.Performative {
	case core.ACCEPT_PROPOSAL:
		log.Printf("🤝 BID ACCEPTED! Job %s started.", env.ConversationID)

		// 1. Extract the Contract from the Body
		var contract core.Contract
		json.Unmarshal(env.Body, &contract)

		// 2. Sign the Contract (Worker side)
		contract.Signatures[myDID] = kp.Sign([]byte(contract.TermsHash))

		// 3. Send to Hive (Notary) to Lock it
		// In a full flow, we send this to "contracts.request"
		contractBytes, _ := json.Marshal(contract)
		nc.Publish("contracts.request", contractBytes)
		log.Printf("📝 Contract sent to Hive for locking.")

		// 4. Simulate Work (Driving/Swiping)
		go performJob(nc, kp, myDID, contract.ID)
	}
}

func performJob(nc *nats.Conn, kp *identity.KeyPair, myDID, contractID string) {
	log.Printf("🚛 Working on %s...", contractID)
	time.Sleep(2 * time.Second) // Driving...

	// 5. Submit Proof to Hive
	proof := core.Proof{
		TaskID:    contractID,
		Type:      core.ProofClassification, // or ProofGPS
		Timestamp: time.Now().Unix(),
		Data:      json.RawMessage(`{"result": "success"}`),
	}
	// Sign the proof
	proofData, _ := json.Marshal(proof.Data)
	proof.Signature = kp.Sign(proofData)

	finalBytes, _ := json.Marshal(proof)
	nc.Publish("proof.submit", finalBytes)

	log.Printf("🏁 Job Done. Proof submitted for %s", contractID)
}
