package ruleEngine

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
)

type noopRuleCreator struct{}

func (noopRuleCreator) CreateRule(ctx context.Context, req CreateRuleRequest) error {
	return nil
}

// NOTE: Since the Bootstrapper is tightly coupled to *database.Queries,
// and we don't have a database mocking layer in place for this package,
// these tests are intended to be ran against a test database in a CI pipeline.
// For now, we perform a basic sanity check of the struct and types.

func TestBootstrapper_RunDepositOnboarding_Safety(t *testing.T) {
	// Ensure the Bootstrapper can be initialized.
	b := NewBootstrapper(nil, nil, noopRuleCreator{})
	assert.NotNil(t, b)

	// We can't easily run real DB queries here, but we've verified compilation.
}

func TestFieldCustomerUsage(t *testing.T) {
	// Verify that our constants used in bootstrap_deposit.go are correct.
	assert.Equal(t, Field("customer"), FieldCustomer)
}

func TestBootstrapper_GeneratedRulesEvaluation(t *testing.T) {
	t.Run("Purchase consensus rule evaluation", func(t *testing.T) {
		// Simulate the rule generated by GenerateRulesFromHistory for a safe vendor.
		// bootstrap_purchase.go now uses OpContainsCS because tx.Vendor holds raw bank
		// descriptions like "AMAZON Mktp US A1B2C3D4", not the clean DisplayName.
		// OpContainsCS uses whole-word token matching, so the vendor display name
		// must appear as a complete token in the raw description.
		vendorName := "AMAZON"

		group := &RuleGroup{
			ID:       1,
			Name:     "Auto-Generated: " + vendorName,
			Logic:    LogicAnd,
			Priority: 10,
			Active:   true,
			Conditions: []*RuleCondition{
				{
					ID:       1,
					Field:    FieldVendor,
					Operator: OpContainsCS,
					Value:    vendorName,
				},
			},
		}

		err := group.Compile()
		assert.NoError(t, err)
		group.Keywords = group.DeriveKeywords()

		// Simulate a raw bank feed transaction that contains the vendor name as a token
		tx := Transaction{
			Vendor: "AMAZON Mktp US A1B2C3D4",
		}

		candidates := FilterCandidates(tx, []*RuleGroup{group})
		assert.Len(t, candidates, 1, "The rule should be selected as a candidate")

		matched, exp := candidates[0].Evaluate(tx)
		assert.True(t, matched, "The transaction should match the auto-generated vendor rule")
		assert.True(t, exp.FinalResult)
	})

	t.Run("Deposit consensus rule evaluation", func(t *testing.T) {
		// Simulate the rule generated by RunDepositOnboarding for a customer.
		// bootstrap_deposit.go now uses OpContainsCS because tx.Customer holds raw bank
		// descriptions, not the clean DisplayName. OpContainsCS uses whole-word token
		// matching, so the customer name must appear as a complete token.
		customerName := "Stripe"

		group := &RuleGroup{
			ID:       2,
			Name:     "Auto-Generated Deposit: " + customerName,
			Logic:    LogicAnd,
			Priority: 10,
			Active:   true,
			Conditions: []*RuleCondition{
				{
					ID:       2,
					Field:    FieldCustomer,
					Operator: OpContainsCS,
					Value:    customerName,
				},
			},
		}

		err := group.Compile()
		assert.NoError(t, err)
		group.Keywords = group.DeriveKeywords()

		tx := Transaction{
			Customer: "Stripe Transfer 12345",
		}

		candidates := FilterCandidates(tx, []*RuleGroup{group})
		assert.Len(t, candidates, 1, "The rule should be selected as a candidate")

		matched, exp := candidates[0].Evaluate(tx)
		assert.True(t, matched, "The transaction should match the auto-generated customer rule")
		assert.True(t, exp.FinalResult)
	})

	t.Run("Splitter review rule evaluation", func(t *testing.T) {
		// Simulate the rule generated by GenerateSplitReviewRules.
		// Now uses OpContainsCS to match clean names inside raw bank descriptions.
		// OpContainsCS uses whole-word token matching, so the vendor name must
		// appear as a complete token in the raw description.
		vendorName := "Gusto"

		group := &RuleGroup{
			ID:             3,
			Name:           "Auto-Generated Split Review: " + vendorName,
			Logic:          LogicAnd,
			Priority:       5,
			Active:         true,
			RequiresReview: true,
			Conditions: []*RuleCondition{
				{
					ID:       3,
					Field:    FieldVendor,
					Operator: OpContainsCS,
					Value:    vendorName,
				},
			},
		}

		err := group.Compile()
		assert.NoError(t, err)
		group.Keywords = group.DeriveKeywords()

		tx := Transaction{
			Vendor: "Gusto Payroll 1234",
		}

		candidates := FilterCandidates(tx, []*RuleGroup{group})
		assert.Len(t, candidates, 1)

		matched, _ := candidates[0].Evaluate(tx)
		assert.True(t, matched)
		assert.True(t, candidates[0].RequiresReview, "The matched rule must enforce manual review")
	})
}
